titles_classics = {
    # 2000s
    "daft punk - discovery": 10,
    "system of a down - toxicity": 10,
    "björk - vespertine": 10,
    "godspeed you! black emperor - lift your skinny fists like antennas to heaven": 10,
    "madvillain & madlib & mf doom - madvillainy": 10,
    # 1990s
    "ms. lauryn hill - the miseducation of lauryn hill": 10,
    "nirvana - nevermind": 10,
    "neutral milk hotel - in the aeroplane over the sea": 10,
    "wu-tang clan - enter the wu-tang (36 chambers)": 10,
    "depeche mode - violator": 10,
    # 1980s
    "metallica - master of puppets": 10,
    "public enemy - it takes a nation of millions to hold us back": 10,
    "kate bush - hounds of love": 10,
    "talking heads - remain in light": 10,
    "prince - purple rain": 10,
    # 1970s
    "miles davis - bitches brew": 10,
    "the clash - london calling": 10,
    "marvin gaye - what's going on": 10,
    "led zeppelin - physical graffiti": 10,
    "television - marquee moon": 10,
    # 1960s
    "frank zappa - hot rats": 10,
    "bob dylan - highway 61 revisited": 10,
    "charles mingus - the black saint and the sinner lady": 10,
    "the beatles - abbey road": 10,
    "nina simone - nina simone sings the blues": 10,
}

titles_2010s = {
    "daughters - you won't get what you want": 10,
    "kids see ghosts - kids see ghosts": 10,
    "kendrick lamar - to pimp a butterfly": 10,
    "swans - to be kind": 10,
    "death grips - the money store": 10,
    "liturgy - h.a.q.q.": 9,
    "matana roberts - coin coin chapter four: memphis": 9,
    "richard dawson - 2020": 9,
    "charli xcx - charli": 9,
    "lingua ignota - caligula": 9,
    "tyler, the creator - igor": 9,
    "otoboke beaver - itekoma hits": 9,
    "weyes blood - titanic rising": 9,
    "little simz - grey area": 9,
    "xiu xiu - girl with basket of fruit": 9,
    "horrendous - idol": 9,
    "idles - joy as an act of resistance": 9,
    "death grips - year of the snitch": 9,
    "parquet courts - wide awake!": 9,
    "against all logic - 2012 - 2017": 9,
    "jack white - boarding house reach": 9,
    "portal - ion": 9,
    "rina sawayama - rina": 9,
    "big k.r.i.t. - 4eva is a mighty long time": 9,
    "brockhampton - saturation": 9,
    "mount eerie - a crow looked at me": 9,
    "neil cicierega - mouth moods": 9,
    "father john misty - pure comedy": 9,
    "a tribe called quest - we got it from here... thank you 4 your service": 9,
    "danny brown - atrocity exhibition": 9,
    "sun kil moon - common as light and love are red valleys of blood": 9,
    "death grips - bottomless pit": 9,
    "swans - the glowing man": 9,
    "xiu xiu - plays the music of twin peaks": 9,
    "david bowie - ★ [blackstar]": 9,
    "david bowie - blackstar": 9,
    "fka twigs - m3ll155x": 9,
    "julia holter - have you in my wilderness": 9,
    "ghost - meliora": 9,
    "kamasi washington - the epic": 9,
    "disma - towards the megalith": 9,
    "death grips - the powers that b": 9,
    "the pop group - citizen zombie": 9,
    "little women - throat": 9,
    "ariel pink - pom pom": 9,
    "iceage - plowing into the field of love": 9,
    "nails - unsilent death": 9,
    "clipping. - clppng": 9,
    "freddie gibbs & madlib - piñata": 9,
    "altar of plagues - teethed glory and injury": 9,
    "behemoth - the satanist": 9,
    "sun kil moon - benji": 9,
    "melt-banana - fetch": 9,
    "tim hecker - virgins": 9,
    "queens of the stone age - ...like clockwork": 9,
    "badbadnotgood - bbng2": 9,
    "ondatrópica - ondatrópica": 9,
    "the knife - shaking the habitual": 9,
    "tnght - tnght": 9,
    "kendrick lamar - good kid, m.a.a.d city": 9,
    "dope body - natural history": 9,
    "fiona apple - the idler wheel": 9,
    "perfume genius - put your back n 2 it": 9,
    "big k.r.i.t. - return of 4eva": 9,
    "battles - gloss drop": 9,
    "fleet foxes - helplessness blues": 9,
    "destroyer - kaputt": 9,
    "women - public strain": 9,
    "the books - the way out": 9,
    "chromeo - business casual": 9,
    "lcd soundsystem - this is happening": 9,
    "gonjasufi - a sufi and a killer": 9,
    "gorillaz - plastic beach": 9,
    "beastie boys - hot sauce committee pt. 2": 9,
    "small black - new chain": 8,
    "oblivionized - abhorrent evolution": 8,
    "stormzy - heavy is the head": 8,
    "yazz ahmed - polyhymnia": 8,
    "ana frango elétrico - little electric chicken heart": 8,
    "anamanaguchi - [usa]": 8,
    "clipping. - there existed an addiction to blood": 8,
    "jpegmafia - all my heroes are cornballs": 8,
    "lightning bolt - sonic citadel": 8,
    "caroline polachek - pang": 8,
    "hobo johnson - the fall of hobo johnson": 8,
    "the highwomen - the highwomen": 8,
    "brockhampton - ginger": 8,
    "king gizzard and the lizard wizard - infest the rats' nest": 8,
    "daphni - sizzling": 8,
    "alex cameron - miami memory": 8,
    "tropical fuck storm - braindrops": 8,
    "dorian electra - flamboyant": 8,
    "purple mountains - purple mountains": 8,
    "denzel curry - zuu": 8,
    "kirin j callinan - return to center": 8,
    "black midi - schlagenheim": 8,
    "danny brown - uknowhatimsayin¿": 8,
    "slauson malone - a quiet farwell, 2016-2018": 8,
    "uboa - the origin of my depression": 8,
    "sunn o))) - pyroclasts": 8,
    "billy woods & kenny segal - hiding places": 8,
    "slowthai - nothing great about britain": 8,
    "flume - hi this is flume": 8,
    "the comet is coming - trust in the lifeforce of the deep mystery": 8,
    "blu & oh no - a long red hot los angeles summer night": 8,
    "freddie gibbs & madlib - bandana": 8,
    "quelle chris - guns": 8,
    "billie eilish - when we all fall asleep, where do we go?": 8,
    "lizzo - cuz i love you": 8,
    "marquis hill - modern flows, vol. 2": 8,
    "pup - morbid stuff": 8,
    "ariana grande - thank u, next": 8,
    "matmos - plastic anniversary": 8,
    "malibu ken - malibu ken": 8,
    "earl sweatshirt - some rap songs": 8,
    "j.i.d - dicaprio 2": 8,
    "current 93 - the light is leaving us all": 8,
    "polyphia - new levels new devils": 8,
    "anderson .paak - oxnard": 8,
    "lana del rey - norman fucking rockwell!": 8,
    "kero kero bonito - time 'n' place": 8,
    "rosalía - el mal querer": 8,
    "julia holter - aviary": 8,
    "armand hammer - paraffin": 8,
    "noname - room 25": 8,
    "hermit and the recluse - orpheus vs. the sirens": 8,
    "aphex twin - collapse ep": 8,
    "ghoul - transmission zero": 8,
    "blood orange - negro swan": 8,
    "guerilla toss - twisted crystal": 8,
    "louis cole - time": 8,
    "denzel curry - ta13oo": 8,
    "twenty one pilots - trench": 8,
    "hmltd - hate music last time delete": 8,
    "imperial triumphant - vile luxury": 8,
    "iglooghost - clear tamei": 8,
    "sophie - oil of every pearl's un-insides": 8,
    "black thought - streams of thought, vol. 1": 8,
    "kanye west - ye": 8,
    "pusha t - daytona": 8,
    "zeal and ardor - stranger fruit": 8,
    "sleep - the sciences": 8,
    "ghost - prequelle": 8,
    "haru nemuri - 春と修羅 (harutosyura)": 8,
    "sons of kemet - your queen is a reptile": 8,
    "kali uchis - isolation": 8,
    "janelle monáe - dirty computer": 8,
    "tropical fuck storm - a laughing death in meatspace": 8,
    "jean grae & quelle chris - everything's fine": 8,
    "the voidz - virtue": 8,
    "jpegmafia - veteran": 8,
    "hop along - bark your head off, dog": 8,
    "natalia lafourcade - musas vol. 2": 8,
    "car seat headrest - twin fantasy (face to face)": 8,
    "judas priest - firepower": 8,
    "anna von hausswolff - dead magic": 8,
    "andrew w.k. - you're not alone": 8,
    "u.s. girls - in a poem unlimited": 8,
    "brockhampton - saturation iii": 8,
    "screaming females - all at once": 8,
    "sharon jones & the dap-kings - soul of a woman": 8,
    "young thug & carnage - young martha": 8,
    "rapsody - laila's wisdom": 8,
    "princess nokia - 1992 deluxe": 8,
    "converge - the dusk in us": 8,
    "death from above - outrage! is now": 8,
    "iglooghost - neō wax bloom": 8,
    "primitive man - caustic": 8,
    "poor lily - poor lily": 8,
    "superhumanoids - urgency": 8,
    "brockhampton - saturation ii": 8,
    "kelela - take me apart": 8,
    "open mike eagle - brick body kids still daydream": 8,
    "uncommon nasa - written at night": 8,
    "alex cameron - forced witness": 8,
    "protomartyr - relatives in descent": 8,
    "tyler, the creator - flower boy": 8,
    "dying fetus - wrong one to fuck with": 8,
    "ariel pink - dedicated to bobby jameson": 8,
    "jay-z - 4:44": 8,
    "oh sees - orc": 8,
    "alvvays - antisocialites": 8,
    "kirin j callinan - bravado": 8,
    "richard dawson - peasant": 8,
    "guerilla toss - gt ultra": 8,
    "sinjin hawke - first opus": 8,
    "billy woods - known unknowns": 8,
    "mgmt - little dark age": 8,
    "algiers - the underside of power": 8,
    "rosalía - los ángeles": 8,
    "elder - reflections of a floating world": 8,
    "forest swords - compassion": 8,
    "perfume genius - no shape": 8,
    "feist - pleasure": 8,
    "daymé arocena - cubafonía": 8,
    "fleet foxes - crack-up": 8,
    "joey bada$$ - all-amerikkkan bada$$": 8,
    "oxbow - thin black duke": 8,
    "the mountain goats - goths": 8,
    "quelle chris - being you is great, i wish i could be you more often": 8,
    "idles - brutalism": 8,
    "pallbearer - heartless": 8,
    "nine inch nails - not the actual events": 8,
    "ibibio sound machine - uyai": 8,
    "run the jewels - run the jewels 3": 8,
    "injury reserve - floss": 8,
    "swain - the long dark blue": 8,
    "xiu xiu - forget": 8,
    "king gizzard and the lizard wizard - flying microtonal banana": 8,
    "sampha - process": 8,
    "code orange - forever": 8,
    "crying - beyond the fleeting gales": 8,
    "solange - a seat at the table": 8,
    "jeff rosenstock - worry.": 8,
    "absu - abzu": 8,
    "carly rae jepsen - e•mo•tion: side b": 8,
    "kero kero bonito - bonito generation": 8,
    "ka - honor killed the samurai": 8,
    "wiley - godfather": 8,
    "street sects - end position": 8,
    "conor oberst - ruminations": 8,
    "frank ocean - blonde": 8,
    "noname - telefone": 8,
    "clipping. - splendor & misery": 8,
    "regina spektor - remember us to life": 8,
    "the i.l.y.'s - scum with boundaries": 8,
    "show me the body - body war": 8,
    "neurosis - fires within fires": 8,
    "touché amoré - stage four": 8,
    "preoccupations - preoccupations": 8,
    "angel olsen - my woman": 8,
    "nick cave & the bad seeds - skeleton tree": 8,
    "yg - still brazy": 8,
    "oh sees - a weird exits": 8,
    "xenia rubinos - black terry cat": 8,
    "radiohead - a moon shaped pool": 8,
    "beyoncé - lemonade": 8,
    "nails - you will never be one of us": 8,
    "car seat headrest - teens of denial": 8,
    "lemon demon - spirit phone": 8,
    "king gizzard and the lizard wizard - nonagon infinity": 8,
    "denzel curry - imperial": 8,
    "sturgill simpson - a sailor's guide to earth": 8,
    "charli xcx - vroom vroom": 8,
    "gorguts - pleiades' dust": 8,
    "murmur - murmur": 8,
    "marissa nadler - strangers": 8,
    "aesop rock - the impossible kid": 8,
    "the drones - feelin kinda free": 8,
    "massive attack - ritual spirit": 8,
    "weezer - weezer (white album)": 8,
    "big ups - before a million universes": 8,
    "kanye west - the life of pablo": 8,
    "moonsorrow - jumalten aika": 8,
    "christian mistress - possession": 8,
    "pop. 1280 - paradise": 8,
    "vektor - terminal redux": 8,
    "ty segall - emotional mugger": 8,
    "matmos - ultimate care ii": 8,
    "the game - the documentary 2.5": 8,
    "iglooghost - chinese nü year": 8,
    "milo - so the flies don't come": 8,
    "theophilus london - lovers holiday": 8,
    "baroness - purple": 8,
    "idylls - prayer for terrene": 8,
    "stone titan - scratch 'n sniff": 8,
    "da mafia 6ix - 6ix commandments": 8,
    "this routine is hell - howl": 8,
    "reks - r.e.k.s. (rhythmatic eternal king supreme)": 8,
    "vektor - outer isolation": 8,
    "havok - time is up": 8,
    "wormrot - dirge": 8,
    "the log.os - λόγος": 8,
    "kids & explosions - shit computer": 8,
    "travis scott - rodeo": 8,
    "the underachievers - evermore: the art of duality": 8,
    "oneohtrix point never - garden of delete": 8,
    "cattle decapitation - the anthropocene extinction": 8,
    "joanna newsom - divers": 8,
    "panopticon - autumn eternal": 8,
    "injury reserve - live from the dentist office": 8,
    "ought - sun coming down": 8,
    "sleaford mods - key markets": 8,
    "ash koosha - guud": 8,
    "czarface - every hero needs a villain": 8,
    "ghost - opus eponymous": 8,
    "lil ugly mane - third side of tape": 8,
    "destroyer - poison season": 8,
    "giles corey - giles corey": 8,
    "high on fire - luminiferous": 8,
    "chelsea wolfe - abyss": 8,
    "lianne la havas - blood": 8,
    "zombi - escape velocity": 8,
    "cakes da killa - the eulogy": 8,
    "ken mode - success": 8,
    "prurient - frozen niagara falls": 8,
    "algiers - algiers": 8,
    "hop along - painted shut": 8,
    "everything everything - get to heaven": 8,
    "comadre - comadre": 8,
    "colin stetson and sarah neufeld - never were the way she was": 8,
    "drake - if you're reading this it's too late": 8,
    "jeff rosenstock - we cool?": 8,
    "alabama shakes - sound & color": 8,
    "unknown mortal orchestra - multi-love": 8,
    "your old droog - kinison": 8,
    "young fathers - white men are black men too": 8,
    "deathspell omega - drought": 8,
    "zs - xe": 8,
    "leviathan - scar sighted": 8,
    "open mike eagle - a special episode of": 8,
    "the mountain goats - beat the champ": 8,
    "björk - vulnicura": 8,
    "clarence clarity - no now": 8,
    "artificial brain - labyrinth constellation": 8,
    "neil cicierega - mouth silence": 8,
    "neil cicierega - mouth sounds": 8,
    "napalm death - apex predator - easy meat": 8,
    "joey bada$$ - b4.da.$$": 8,
    "the uv race - homo": 8,
    "milo - i wish my brother rob was here": 8,
    "d'angelo and the vanguard - black messiah": 8,
    "daughters - daughters": 8,
    "full of hell & merzbow - full of hell & merzbow": 8,
    "father john misty - i love you, honeybear": 8,
    "dean blunt - black metal": 8,
    "wildbirds & peacedrums - rhythm": 8,
    "dope body - lifer": 8,
    "uncommon nasa - new york telephone": 8,
    "botanist - vi: flora": 8,
    "mick jenkins - the water[s]": 8,
    "run the jewels - run the jewels 2": 8,
    "the tallest man on earth - sometimes the blues is just a passing bird": 8,
    "busdriver - perfect hair": 8,
    "armand hammer - race music": 8,
    "panopticon - roads to the north": 8,
    "flying lotus - you're dead!": 8,
    "the wytches - annabel dream reader": 8,
    "perfume genius - too bright": 8,
    "apathy - connecticut casual": 8,
    "luke abbott - holkham drones": 8,
    "open mike eagle - dark comedy": 8,
    "fka twigs - lp1": 8,
    "toxic holocaust - conjure and command": 8,
    "wolves in the throne room - celestite": 8,
    "la roux - trouble in paradise": 8,
    "bongripper - satan worshipping doom": 8,
    "agalloch - marrow of the spirit": 8,
    "thantifaxath - sacred white noise": 8,
    "cormorant - dwellings": 8,
    "tobacco - ultima ii massage": 8,
    "ratking - so it goes": 8,
    "girl talk & freeway - broken ankles ep": 8,
    "white hinterland - baby": 8,
    "white suns - totem": 8,
    "carla bozulich - boy": 8,
    "tune-yards - nikki nack": 8,
    "kyary pamyu pamyu - なんだこれくしょん (nanda collection)": 8,
    "the souljazz orchestra - rising sun": 8,
    "have a nice life - the unnatural world": 8,
    "indian - from all purity": 8,
    "step brothers - lord steppington": 8,
    "big ups - eighteen hours of static": 8,
    "liars - mess": 8,
    "thee silver mt. zion memorial orchestra - fuck off get free we pour light on everything": 8,
    "timber timbre - hot dreams": 8,
    "mariam the believer - blood donation": 8,
    "fergus & geronimo - unlearn": 8,
    "xiu xiu - nina": 8,
    "actress - ghettoville": 8,
    "black milk - no poison no paradise": 8,
    "pro era - peep: the aprocalypse": 8,
    "daniel avery - drone logic": 8,
    "future of the left - how to stop your brain in an accident": 8,
    "cage the elephant - melophobia": 8,
    "touché amoré - is survived by": 8,
    "yc the cynic - gnk": 8,
    "flatbush zombies - betteroffdead": 8,
    "darkside - psychic": 8,
    "gorguts - colored sands": 8,
    "ka - the night's gambit": 8,
    "of montreal - lousy with sylvianbriar": 8,
    "chelsea wolfe - apokalypsis": 8,
    "run the jewels - run the jewels": 8,
    "bill callahan - dream river": 8,
    "young fathers - tape two": 8,
    "ceremony - rohnert park": 8,
    "chelsea wolfe - pain is beauty": 8,
    "jon hopkins - immunity": 8,
    "clipping. - midcity": 8,
    "julia holter - loud city song": 8,
    "deafheaven - sunbather": 8,
    "the drones - i see seaweed": 8,
    "the dillinger escape plan - one of us is the killer": 8,
    "savages - silence yourself": 8,
    "badbadnotgood - bbng": 8,
    "kvelertak - kvelertak": 8,
    "kvelertak - meir": 8,
    "ghostface killah & adrian younge - twelve reasons to die": 8,
    "daft punk - random access memories": 8,
    "the haxan cloak - excavation": 8,
    "andrew jackson jihad - knife man": 8,
    "smith westerns - soft will": 8,
    "shlohmo - laid out": 8,
    "kurt vile - wakin on a pretty daze": 8,
    "autechre - exai": 8,
    "young fathers - tape one": 8,
    "my bloody valentine - m b v": 8,
    "dumbo gets mad - elephants at the door": 8,
    "la dispute - wildlife": 8,
    "murder construct - results": 8,
    "the bad plus - made possible": 8,
    "karriem riggins - alone together": 8,
    "recondite - on acid": 8,
    "xibalba - hasta la muerte": 8,
    "pile - dripping": 8,
    "loma prieta - i.v.": 8,
    "billy woods - history will absolve me": 8,
    "white suns - sinews": 8,
    "portico quartet - portico quartet": 8,
    "iceage - you're nothing": 8,
    "black breath - sentenced to life": 8,
    "beach fossils - clash the truth": 8,
    "burial - truant / rough sleeper": 8,
    "action bronson & the alchemist - rare chandeliers": 8,
    "buke and gase - general dome": 8,
    "foxygen - we are the 21st century ambassadors of peace & magic": 8,
    "godspeed you! black emperor - allelujah! don't bend! ascend!": 8,
    "the evens - the odds": 8,
    "the gaslamp killer - breakthrough": 8,
    "converge - all we love we leave behind": 8,
    "krallice - years past matter": 8,
    "death grips - no love deep web": 8,
    "swans - the seer": 8,
    "nachtmystium - silencing machine": 8,
    "tame impala - lonerism": 8,
    "holograms - holograms": 8,
    "iamamiwhoami - kin": 8,
    "wild nothing - nocturne": 8,
    "ab-soul - control system": 8,
    "alt-j - an awesome wave": 8,
    "matthew dear - beams": 8,
    "foxygen - take the kids off broadway": 8,
    "lone - galaxy garden": 8,
    "torche - harmonicraft": 8,
    "ty segall & white fence - hair": 8,
    "ty segall band - slaughterhouse": 8,
    "killer mike - r.a.p. music": 8,
    "high on fire - de vermis mysteriis": 8,
    "zammuto - zammuto": 8,
    "the tallest man on earth - there's no leaving now": 8,
    "theesatisfaction - awe naturale": 8,
    "soap&skin - narrow": 8,
    "big k.r.i.t. - 4eva n a day": 8,
    "beach house - bloom": 8,
    "burial - kindred": 8,
    "john talabot - ƒin": 8,
    "heems - nehru jackets": 8,
    "daniel rossen - silent hour / golden mile": 8,
    "the weeknd - echoes of silence": 8,
    "matana roberts - coin coin chapter one: gens de couleur libre": 8,
    "elzhi - elmatic": 8,
    "spiritualized - sweet heart sweet light": 8,
    "africa hitech - 93 million miles": 8,
    "craft spells - idle labor": 8,
    "a$ap rocky - live. love. a$ap": 8,
    "death grips - exmilitary": 8,
    "cunninlynguists - oneirology": 8,
    "cloud nothings - attack on memory": 8,
    "colin stetson - new history warfare vol. 2: judges": 8,
    "oneohtrix point never - replica": 8,
    "veronica falls - veronica falls": 8,
    "danny brown - xxx": 8,
    "thundercat - the golden age of apocalypse": 8,
    "kendrick lamar - section.80": 8,
    "little dragon - ritual union": 8,
    "sbtrkt - sbtrkt": 8,
    "iceage - new brigade": 8,
    "st. vincent - strange mercy": 8,
    "liturgy - aesthethica": 8,
    "timber timbre - creep on creepin' on": 8,
    "crystal stilts - in love with oblivion": 8,
    "shabazz palaces - black up": 8,
    "holy ghost! - holy ghost!": 8,
    "nicolas jaar - space is only noise": 8,
    "the pains of being pure at heart - belong": 8,
    "tim hecker - ravedeath, 1972": 8,
    "mogwai - hardcore will never die, but you will": 8,
    "ghostface killah - apollo kids": 8,
    "the mountain goats - all eternals deck": 8,
    "diamond rings - special affections": 8,
    "das racist - sit down, man": 8,
    "pj harvey - let england shake": 8,
    "british sea power - valhalla dancehall": 8,
    "girl talk - all day": 8,
    "weekend - sports": 8,
    "brian eno, jon hopkins & leo abrahams - small craft on a milk sea": 8,
    "glasser - ring": 8,
    "twin shadow - forget": 8,
    "magic kids - memphis": 8,
    "sufjan stevens - all delighted people": 8,
    "flying lotus - pattern+grid world": 8,
    "blonde redhead - penny sparkle": 8,
    "deerhunter - halcyon digest": 8,
    "baths - cerulean": 8,
    "björk / dirty projectors - mount wittenberg orca": 8,
    "the roots - how i got over": 8,
    "laurie anderson - homeland": 8,
    "the drums - the drums": 8,
    "arcade fire - the suburbs": 8,
    "janelle monáe - the archandroid": 8,
    "woods - at echo lake": 8,
    "ratatat - lp4": 8,
    "wavves - king of the beach": 8,
    "flying lotus - cosmogramma": 8,
    "ariel pink's haunted graffiti - before today": 8,
    "high on fire - snakes for the divine": 8,
    "the radio dept. - clinging to a scheme": 8,
    "mgmt - congratulations": 8,
    "the tallest man on earth - the wild hunt": 8,
    "i am your destruction - i am your destruction": 7,
    "megaton leviathan - past 21 beyond the arctic cell": 7,
    "sterilizer - sterilizer": 7,
    "lazer/wulf - the beast of left and right": 7,
    "h-sik - cocody": 7,
    "the act of estimating as worthless - amongst these splintered minds // leaden thoughts sing softly": 7,
    "zammuto - idiom wind": 7,
    "roddy ricch - please excuse me for being antisocial": 7,
    "ecco2k - e": 7,
    "griselda - wwcd": 7,
    "roomful of teeth - roomful of teeth": 7,
    "jme - grime mc": 7,
    "city morgue - city morgue vol. 2: as good as dead": 7,
    "lim kim - generasian": 7,
    "tnght - ii": 7,
    "gang starr - one of the best yet": 7,
    "nick cave & the bad seeds - ghosteen": 7,
    "babii, kai whiston, iglooghost - xyz": 7,
    "michael kiwanuka - kiwanuka": 7,
    "big thief - two hands": 7,
    "young thug - so much fun": 7,
    "oliver tree - do you feel me?": 7,
    "cordae - the lost boy": 7,
    "rapsody - eve": 7,
    "glass beach - the first glass beach album": 7,
    "swans - leaving meaning.": 7,
    "brittany howard - jaime": 7,
    "swain - negative space": 7,
    "thom yorke - anima": 7,
    "blanck mass - animated violence mild": 7,
    "100 gecs - 1000 gecs": 7,
    "poppy - choke": 7,
    "megan thee stallion - fever": 7,
    "bill callahan - shepherd in a sheepskin vest": 7,
    "weatherday - come in": 7,
    "fka twigs - magdalene": 7,
    "your old droog - it wasn't even close": 7,
    "injury reserve - injury reserve": 7,
    "carly rae jepsen - dedicated": 7,
    "king gizzard and the lizard wizard - fishing for fishies": 7,
    "anderson .paak - ventura": 7,
    "dos monos - dos city": 7,
    "show me the body - dog whistle": 7,
    "sunn o))) - life metal": 7,
    "sun kil moon - i also want to die in new orleans": 7,
    "stella donnelly - beware of the dogs": 7,
    "future - future hndrxx presents: the wizrd": 7,
    "ibibio sound machine - doko mien": 7,
    "dark time sunshine - anx": 7,
    "james blake - assume form": 7,
    "american football - american football": 5,
    "21 savage - i am > i was": 7,
    "black thought & salaam remi - streams of thought, vol. 2": 7,
    "kai whiston - kai whiston bitch": 7,
    "whitey morgan & the 78's - sonic ranch": 7,
    "jeffrey lewis and the deposit returners - works by tul kupferberg (1923-2010)": 7,
    "spellling - mazy fly": 7,
    "trippie redd - a love letter to you 3": 7,
    "vince staples - fm!": 7,
    "open mike eagle - what happens when i try to relax": 7,
    "sharon van etten - remind me tomorrow": 7,
    "curren$y, freddie gibbs & the alchemist - fetti": 7,
    "jmsn - velvet": 7,
    "clarence clarity - think : peace": 7,
    "lupe fiasco - drogas wave": 7,
    "poppy - am i a girl?": 7,
    "okonkolo - cantos": 7,
    "yves tumor - safe in the hands of love": 7,
    "brockhampton - iridescence": 7,
    "george clanton - slide": 7,
    "behemoth - i loved you at your darkest": 7,
    "iglooghost - steel mogu": 7,
    "marissa nadler - for my crimes": 7,
    "onyx collective - lower east suite part three": 7,
    "spiritualized - and nothing hurt": 7,
    "civil civic - rules": 7,
    "tierra whack - whack world": 7,
    "niki - zephyr": 7,
    "the internet - hive mind": 7,
    "playboi carti - die lit": 7,
    "nine inch nails - bad witch": 7,
    "florence + the machine - high as hope": 7,
    "travis scott - astroworld": 7,
    "ariana grande - sweetener": 7,
    "ski mask the slump god - beware the book of eli": 7,
    "lump - lump": 7,
    "james ferraro - four pieces for mirai": 7,
    "rae sremmurd - sr3mm": 7,
    "father john misty - god's favorite customer": 7,
    "john prine - the tree of forgiveness": 7,
    "let's eat grandma - i'm all ears": 7,
    "serpentwithfeet - soil": 7,
    "beach house - 7": 7,
    "iceage - beyondless": 7,
    "jon hopkins - singularity": 7,
    "lil yachty - lil boat 2": 7,
    "czarface & mf doom - czarface meets metal face": 7,
    "mark kozelek - mark kozelek": 7,
    "mount eerie - now only": 7,
    "keiji haino & sumac - american dollar bill - keep facing sideways, you're too hideous to look at face on": 7,
    "david byrne - american utopia": 7,
    "cupcakke - ephorize": 7,
    "superorganism - superorganism": 7,
    "king gizzard and the lizard wizard - gumboot soup": 7,
    "makaya mccraven - highly rare": 7,
    "charli xcx - pop 2": 7,
    "ty segall - freedom's goblin": 7,
    "chris stapleton - from a room: volume 2": 7,
    "post malone - beerbongs & bentleys": 7,
    "tribulation - down below": 7,
    "king gizzard and the lizard wizard - polygondwanaland": 7,
    "n.e.r.d - no one ever really dies": 7,
    "21 savage, offset & metro boomin - without warning": 7,
    "first aid kit - ruins": 7,
    "lou the human - humaniac": 7,
    "no age - snares like a haircut": 7,
    "lil pump - lil pump": 7,
    "kimbra - primal heart": 7,
    "björk - utopia": 7,
    "injury reserve - drive it like it's stolen": 7,
    "ibeyi - ash": 7,
    "bicep - bicep": 7,
    "corbin - mourn": 7,
    "daniel caesar - freudian": 7,
    "alice glass - alice glass": 7,
    "brand new - science fiction": 7,
    "julien baker - turn out the lights": 7,
    "the debauchees - big machines and peculiar beings": 7,
    "haunted horses - watcher": 7,
    "quelle chris - ghost at the finish line": 7,
    "calvaiire - forceps": 7,
    "wreck and reference - no youth": 7,
    "gnaw their tongues - eschatological scatology": 7,
    "balkans - balkans": 7,
    "a-1 - after school special": 7,
    "all pigs must die - all pigs must die": 7,
    "big blood - dark country magic": 7,
    "teen daze - four more years": 7,
    "noveller - desert fires": 7,
    "nmesh - pharma": 7,
    "snake oil - snake oil": 7,
    "wifisfuneral - boy who cried wolf": 7,
    "integrity - howling, for the nightmare shall consume": 7,
    "milo - who told you to think​?​?​!​!​?​!​?​!​?​!": 7,
    "kesha - rainbow": 7,
    "igorrr - savage sinusoid": 7,
    "chelsea wolfe - hiss spun": 7,
    "the national - sleep well beast": 7,
    "broken social scene - hug of thunder": 7,
    "dead cross - dead cross": 7,
    "paramore - after laughter": 7,
    "kendrick lamar - damn.": 7,
    "melody's echo chamber - bon voyage": 7,
    "black lips - satan's graffiti or god's art?": 7,
    "remo drive - greatest hits": 7,
    "charli xcx - number 1 angel": 7,
    "roger waters - is this the life we really want?": 7,
    "lorde - melodrama": 7,
    "colin stetson - all this i do for glory": 7,
    "the black heart rebellion - har nevo": 7,
    "ondatrópica - baile bucanero": 7,
    "jonwayne - rap album two": 7,
    "mac demarco - this old dog": 7,
    "sza - ctrl": 7,
    "yucky duster - duster's lament": 7,
    "dirty projectors - dirty projectors": 7,
    "your old droog - packs": 7,
    "william basinski - a shadow in time": 7,
    "blanck mass - world eater": 7,
    "spoon - hot thoughts": 7,
    "migos - culture": 7,
    "havok - conformicide": 7,
    "eprom - metahuman": 7,
    "take over and destroy - endless night": 7,
    "the magnetic fields - 50 song memoir": 7,
    "ab-soul - do what thou wilt.": 7,
    "jesca hoop - memories are now": 7,
    "pissed jeans - why love now": 7,
    "power trip - nightmare logic": 7,
    # "": 7, supposed to be childish gambino - "awaken, my love!"
    "foxygen - hang": 7,
    "bruno mars - 24k magic": 7,
    "d.r.a.m. - big baby d.r.a.m.": 7,
    "nxworries - yes lawd!": 7,
    "open mike eagle - 4nml hsptl": 7,
    "wormrot - voices": 7,
    "coma cinema - blue suicide": 7,
    "ghoul - dungeon bastards": 7,
    "kemba - negus": 7,
    "sleigh bells - jessica rabbit": 7,
    "marching church - telling it like it is": 7,
    "vince staples - prima donna": 7,
    "young thug - jeffery": 7,
    "teenage cool kids - denton after sunset": 7,
    "the dillinger escape plan - dissociation": 7,
    "clipping. - wriggle": 7,
    "joey purp - iiidrops": 7,
    "the avalanches - wildflower": 7,
    "clams casino - 32 levels": 7,
    "badbadnotgood - iv": 7,
    "apathy - handshakes with snakes": 7,
    "chance the rapper - coloring book": 7,
    "deerhoof - the magic": 7,
    "skepta - konnichiwa": 7,
    "deakin - sleep cycle": 7,
    "olga bell - tempo": 7,
    "mr. yote - the terrible tale of scurvy jones": 7,
    "lil yachty - lil boat": 7,
    "case/lang/veirs - case/lang/veirs": 7,
    "modern baseball - holy ghost": 7,
    "open mike eagle & paul white - hella personal film festival": 7,
    "bones - useless": 7,
    "kano - made in the manor": 7,
    "parquet courts - human performance": 7,
    "soupcans - parasite brain": 7,
    "the body & full of hell - one day you will ache like i ache": 7,
    "iggy pop - post pop depression": 7,
    "pj harvey - the hope six demolition project": 7,
    "black mountain - iv": 7,
    "woods - city sun eater in the river of light": 7,
    "anderson .paak - malibu": 7,
    "krallice - hyperion": 7,
    "soap&skin - sugarbread": 7,
    "oranssi pazuzu - värähtelijä": 7,
    "wiki - lil me": 7,
    "meridian brothers - los suicidas": 7,
    "waka flocka flame - flockaveli 1.5": 7,
    "pusha t - king push - darkest before dawn: the prelude": 7,
    "lycus - tempest": 7,
    "santigold - 99¢": 7,
    "nevermen - nevermen": 7,
    "freddie gibbs - shadow of a doubt": 7,
    "blu & exile - give me my flowers while i can still smell them": 7,
    "adele - 25": 7,
    "chairlift - moth": 7,
    "grimes - art angels": 7,
    "christian scott atunde adjuah - stretch music": 7,
    "uncommon nasa - halfway": 7,
    "corpo-mente - corpo-mente": 7,
    "onyx - wakedafucup": 7,
    "car seat headrest - teens of style": 7,
    "weedeater - jason... the dragon": 7,
    "the gaslamp killer - death gate": 7,
    "pissgrave - suicide euphoria": 7,
    "king gizzard and the lizard wizard - paper mâché dream balloon": 7,
    "the world is a beautiful place and i am no longer afraid to die - harmlessness": 7,
    "neon indian - vega intl. night school": 7,
    "mac miller - go:od am": 7,
    "beach slang - the things we do to find people who feel like us": 7,
    "dr. dre - compton: a soundtrack by dr. dre": 7,
    "maserati - pyramid of the sun": 7,
    "touché amoré - parting the sea between brightness and me": 7,
    "kylesa - exhausting fire": 7,
    "loma prieta - self portrait": 7,
    "protomartyr - the agent intellect": 7,
    "quelle chris & chris keys - innocent country": 7,
    "swain - heavy dancing": 7,
    "rp boo - fingers, bank pads, and shoe prints": 7,
    "dâm-funk - invite the light": 7,
    "carly rae jepsen - e•mo•tion": 7,
    "dope body - kunk": 7,
    "peste noire - la chaise-dyable": 7,
    "ghostface killah & adrian younge - twelve reasons to die ii": 7,
    "ratatat - magnifique": 7,
    "comet gain - howl of the lonely crowd": 7,
    "the strange boys - live music": 7,
    "tame impala - currents": 7,
    "miami horror - illumination": 7,
    "the chemical brothers - born in the echoes": 7,
    "mac demarco - another one": 7,
    "tribulation - the children of the night": 7,
    "billy woods - today, i wrote nothing": 7,
    "jamie xx - in colour": 7,
    "blur - the magic whip": 7,
    "florence + the machine - how big how blue how beautiful": 7,
    "paul de jong - if": 7,
    "apathy - honkey kong": 7,
    "liturgy - the ark work": 7,
    "toro y moi - what for?": 7,
    "lightning bolt - fantasy empire": 7,
    "adventures - supersonic home": 7,
    "benjamin clementine - at least for now": 7,
    "sufjan stevens - carrie & lowell": 7,
    "og maco - og maco": 7,
    "death grips - fashion week": 7,
    "lupe fiasco - tetsuo & youth": 7,
    "theesatisfaction - earthee": 7,
    "grave babies - crusher": 7,
    "laura marling - short movie": 7,
    "black milk & danny brown - black and brown!": 7,
    "otis brown iii - the thought of you": 7,
    "vallenfyre - splinters": 7,
    "a$ap ferg - ferg forever": 7,
    "john carpenter - lost themes": 7,
    "viet cong - viet cong": 7,
    "mr. oizo - the church": 7,
    "sleater-kinney - no cities to love": 7,
    "clockwork indigo - clockwork indigo": 7,
    "vince staples - hell can wait": 7,
    "andy stott - faith in strangers": 7,
    "godflesh - a world lit only by fire": 7,
    "deerhoof - la isla bonita": 7,
    "the underachievers - cellar door: terminus ut exordium": 7,
    "meek mill - dreams worth more than money": 7,
    "cunninlynguists - strange journey volume three": 7,
    "sir michael rocks - banco": 7,
    "weezer - everything will be alright in the end": 7,
    "weird al yankovic - mandatory fun": 7,
    "kyary pamyu pamyu - ピカピカふぁんたじん [pika pika fantajin]": 7,
    "antemasque - antemasque": 7,
    "julian casablancas + the voidz - tyranny": 7,
    "alt-j - this is all yours": 7,
    "spoon - they want my soul": 7,
    "my brightest diamond - this is my hand": 7,
    "mayhem - esoteric warfare": 7,
    "sia - 1000 forms of fear": 7,
    "usa out of vietnam - crashing diseases and incurable airplanes": 7,
    "mastodon - once more 'round the sun": 7,
    "ought - more than any other day": 7,
    "pharoahe monch - ptsd": 7,
    "thou - summit": 7,
    "badbadnotgood - iii": 7,
    "an autumn for crippled children - try not to destroy everything you love": 7,
    "a sunny day in glasgow - sea when absent": 7,
    "tony molina - dissed and dismissed": 7,
    "ibibio sound machine - ibibio sound machine": 7,
    "la dispute - rooms of the house": 7,
    "cynic - carbon-based anatomy": 7,
    "sisyphus - sisyphus": 7,
    "herman düne - strange moosic": 7,
    "g herbo - welcome to fazoland": 7,
    "owen pallett - in conflict": 7,
    "goatwhore - blood for the master": 7,
    "off! - wasted years": 7,
    "evian christ - waterfall": 7,
    "future islands - singles": 7,
    "wild beasts - present tense": 7,
    "xiu xiu - angel guts: red classroom": 7,
    "schoolboy q - oxymoron": 7,
    "the uncluded - hokey fright": 7,
    "st. vincent - st. vincent": 7,
    "the war on drugs - lost in the dream": 7,
    "the underachievers - indigoism": 7,
    "shlohmo - vacation": 7,
    "shlohmo - bad vibes": 7,
    "denzel curry - nostalgic 64": 7,
    "cara neir - portals to a better, dead world": 7,
    "nils frahm - spaces": 7,
    "shad - flying colours": 7,
    "moonface - julia with blue jeans on": 7,
    "four tet - beautiful rewind": 7,
    "ulcerate - the destroyers of all": 7,
    "kayo dot - hubardo": 7,
    "machinedrum - vapor city": 7,
    "modern life is war - fever hunting": 7,
    "mr. muthafuckin' exquire - kismet": 7,
    "the world is a beautiful place and i am no longer afraid to die - whenever, if ever": 7,
    "eminem - the marshall mathers lp 2": 7,
    "danny brown - old": 7,
    "billy woods - dour candy": 7,
    "a$ap ferg - trap lord": 7,
    "holy ghost! - dynamics": 7,
    "king krule - 6 feet beneath the moon": 7,
    "joey bada$$ - summer knights": 7,
    "janelle monáe - the electric lady": 7,
    "candy claws - ceres & calypso in the deep time": 7,
    "makthaverskan - ii": 7,
    "james holden - the inheritors": 7,
    "melt yourself down - melt yourself down": 7,
    "bibio - silver wilkinson": 7,
    "big k.r.i.t. - king remembered in time": 7,
    "disclosure - settle": 7,
    "nails - abandon all life": 7,
    "jenny hval - innocence is kinky": 7,
    "lapalux - nostalchic": 7,
    "the mary onettes - hit the waves": 7,
    "laura marling - once i was an eagle": 7,
    "ken mode - entrench": 7,
    "alunageorge - body music": 7,
    "james blake - overgrown": 7,
    "vampire weekend - modern vampires of the city": 7,
    "colin stetson - new history warfare vol. 3: to see more light": 7,
    "this town needs guns - 13.0.0.0.0": 7,
    "rival sons - pressure & time": 7,
    "villagers - {awayland}": 7,
    "david bowie - the next day": 7,
    "m.i.a. - matangi": 7,
    "pissed jeans - honeys": 7,
    "grouper - the man who died in his boat": 7,
    "blood ceremony - living with the ancients": 7,
    "title fight - floral green": 7,
    "lianne la havas - is your love big enough?": 7,
    "parquet courts - light up gold": 7,
    "atoms for peace - amok": 7,
    "jessica pratt - jessica pratt": 7,
    "holly herndon - movement": 7,
    "captain murphy - duality": 7,
    "chelsea wolfe - unknown rooms: a collection of acoustic songs": 7,
    "yo la tengo - fade": 7,
    "neurosis - honor found in decay": 7,
    "macklemore & ryan lewis - the heist": 7,
    "andy stott - luxury problems": 7,
    "unknown mortal orchestra - ii": 7,
    "vessel - order of noise": 7,
    "scott walker - bish bosch": 7,
    "angel olsen - half way home": 7,
    "a$ap rocky - long.live.a$ap": 7,
    "flying lotus - until the quiet comes": 7,
    "the mountain goats - transcendental youth": 7,
    "four tet - pink": 7,
    "joey bada$$ - 1999": 7,
    "woods - bend beyond": 7,
    "david byrne & st. vincent - love this giant": 7,
    "dinosaur jr. - i bet on sky": 7,
    "bat for lashes - the haunted man": 7,
    "clams casino - instrumental 2": 7,
    "frank ocean - channel orange": 7,
    "jens lekman - i know what love isn't": 7,
    "bloc party - four": 7,
    "big k.r.i.t. - live from the underground": 7,
    "baroness - yellow & green": 7,
    "liars - wixiw": 7,
    "aesop rock - skelethon": 7,
    "sigur rós - valtari": 7,
    "kindness - world, you need a change of mind": 7,
    "unsane - wreck": 7,
    "neil young & crazy horse - americana": 7,
    "hot chip - in our heads": 7,
    "pallbearer - sorrow and extinction": 7,
    "off! - off!": 7,
    "mount eerie - clear moon": 7,
    "pop. 1280 - the horror": 7,
    "the mars volta - noctourniquet": 7,
    "dr. john - locked down": 7,
    "jacaszek - glimmer": 7,
    "first aid kit - the lion's roar": 7,
    "chairlift - something": 7,
    "the men - open your heart": 7,
    "master musicians of bukkake - totem three": 7,
    "amon tobin - isam": 7,
    "siriusmo - mosaik": 7,
    "of montreal - paralytic stalks": 7,
    "trap them - darker handcraft": 7,
    "rustie - glass swords": 7,
    "sharon van etten - tramp": 7,
    "king krule - king krule": 7,
    "skrillex - scary monsters and nice sprites": 7,
    "kate bush - 50 words for snow": 7,
    "tom waits - bad as me": 7,
    "the field - looping state of mind": 7,
    "hudson mohawke - satin panthers": 7,
    "girls - father, son, holy ghost": 7,
    "wilco - the whole love": 7,
    "wild flag - wild flag": 7,
    "the horrors - skying": 7,
    "metronomy - the english riviera": 7,
    "earth - angels of darkness, demons of light i": 7,
    "wild beasts - smother": 7,
    "death cab for cutie - codes and keys": 7,
    "tune-yards - w h o k i l l": 7,
    "the strokes - angles": 7,
    "braids - native speaker": 7,
    "future islands - in evening air": 7,
    "cake - showroom of compassion": 7,
    "james blake - james blake": 7,
    "sharon van etten - epic": 7,
    "smith westerns - dye it blonde": 7,
    "gold panda - lucky shiner": 7,
    "cee-lo green - the lady killer": 7,
    "grinderman - grinderman 2": 7,
    "matthew dear - black city": 7,
    "weezer - hurley": 7,
    "suckers - wild smile": 7,
    "wild nothing - gemini": 7,
    "sleepy sun - fever": 7,
    "tobacco - maniac meat": 7,
    "here we go magic - pigeons": 7,
    "holy fuck - latin": 7,
    "crystal castles - (ii)": 7,
    "harlem - hippies": 7,
    "the black keys - brothers": 7,
    "the new pornographers - together": 7,
    "titus andronicus - the monitor": 7,
    "hoax - 3rd ep": 6,
    "dweller on the threshold - dweller on the threshold": 6,
    "charlie haden & hank jones - come sunday": 6,
    "red horse - red horse": 6,
    "madeon - good faith": 6,
    "billy woods - terror management": 6,
    "mount eerie - lost wisdom pt. 2": 6,
    "idk - is he real?": 6,
    "angel olsen - all mirrors": 6,
    "vivian girls - memory": 6,
    "cattle decapitation - death atlas": 6,
    "bon iver - i,i": 6,
    "blood orange - angel's pulse": 6,
    "rich brian - the sailor": 6,
    "oh sees - face stabber": 6,
    "taylor swift - lover": 6,
    "kim petras - clarity": 6,
    "benny the butcher - the plugs i met": 6,
    "knocked loose - a different shade of blue": 6,
    "lil nas x - 7": 6,
    "earthgang - mirrorland": 6,
    "slipknot - we are not your kind": 6,
    "tomb mold - planetary clairvoyance": 6,
    "rico nasty & kenny beats - anger management": 6,
    "kevin abstract - arizona baby": 6,
    "aries - welcome home": 6,
    "full of hell - weeping choir": 6,
    "solange - when i get home": 6,
    "juice wrld - death race for love": 6,
    "offset - father of 4": 6,
    "2 chainz - rap or go to the league": 6,
    "vampire weekend - father of the bride": 6,
    "weezer - weezer (teal album)": 6,
    "boogie - everything's for sale": 6,
    "foals - everything not saved will be lost (part 1)": 6,
    "waste of space orchestra - syntheosis": 6,
    "the flaming lips - king's mouth": 6,
    "the chemical brothers - no geography": 6,
    "la dispute - panorama": 6,
    "ski mask the slump god - stokeley": 6,
    "hannah diamond - reflections": 6,
    "panda bear - buoys": 6,
    "metro boomin - not all heroes wear capes": 6,
    "jessica pratt - quiet signs": 6,
    "toro y moi - outer peace": 6,
    "little big - antipositive, pt. 2": 6,
    "city morgue - city morgue vol. 1: hell or high water": 6,
    "sheck wes - mudboy": 6,
    "milo - budding ornithologists are weary of tired analogies": 6,
    "hozier - nina cried power": 6,
    "bring me the horizon - amo": 6,
    "kurt vile - bottle it in": 6,
    "high on fire - electric messiah": 6,
    "tim hecker - konoyo": 6,
    "$uicideboy$ - i want to die in new orleans": 6,
    "sun kil moon - this is my dinner": 6,
    "teyana taylor - k.t.s.e.": 6,
    "vein - errorzone": 6,
    "rico nasty - nasty": 6,
    "nas - nasir": 6,
    "thou - magus": 6,
    "gorillaz - the now now": 6,
    "oh sees - smote reverser": 6,
    "mitski - be the cowboy": 6,
    "dirty projectors - lamp lit prose": 6,
    "bts - love yourself 轉 tear": 6,
    "kamasi washington - heaven and earth": 6,
    "oneohtrix point never - age of": 6,
    "cardi b - invasion of privacy": 6,
    "snail mail - lush": 6,
    "big ups - two parts together": 6,
    "courtney barnett - tell me how you really feel": 6,
    "sob x rbe - gangin": 6,
    "prhyme - prhyme 2": 6,
    "park jiha - communion": 6,
    "flatbush zombies - vacation in hell": 6,
    "young fathers - cocoa sugar": 6,
    "rich brian - amen": 6,
    "jeff rosenstock - post-": 6,
    "huncho jack - huncho jack, jack huncho": 6,
    "glassjaw - material control": 6,
    "ought - room inside the world": 6,
    "armand hammer - rome": 6,
    "prurient - rainbow mirror": 6,
    "smokepurpp - deadstar": 6,
    "noel gallagher's high flying birds - who built the moon?": 6,
    "yung lean - stranger": 6,
    "st. vincent - masseduction": 6,
    "the 1975 - a brief inquiry into online relationships": 6,
    "poppy - poppy.computer": 6,
    "cx kidtronik - krak attack 2: ballad of elli skiff": 6,
    "toxic holocaust - chemistry of consciousness": 6,
    "fashawn - higher learning vol. 2": 6,
    "vreid - v": 6,
    "mono/poly - paramatma": 6,
    "a$ap ferg - still striving": 6,
    "the world is a beautiful place and i am no longer afraid to die - always foreign": 6,
    "nine inch nails - add violence": 6,
    "vic mensa - the autobiography": 6,
    "ski mask the slump god - you will regret": 6,
    "myrkur - mareridt": 6,
    "wolves in the throne room - thrice woven": 6,
    "foo fighters - concrete and gold": 6,
    "dizzee rascal - raskit": 6,
    "lcd soundsystem - american dream": 6,
    "the killers - wonderful wonderful": 6,
    "queens of the stone age - villains": 6,
    "action bronson - blue chips 7000": 6,
    "liam gallagher - as you were": 6,
    "everything everything - a fever dream": 6,
    "zola jesus - okovi": 6,
    "grizzly bear - painted ruins": 6,
    "vince staples - big fish theory": 6,
    "katy perry - witness": 6,
    "king gizzard and the lizard wizard - murder of the universe": 6,
    "the underachievers - renaissance": 6,
    "the smith street band - more scared of you than you are of me": 6,
    "lana del rey - lust for life": 6,
    "full of hell - trumpeting ecstasy": 6,
    "freddie gibbs - you only live 2wice": 6,
    "rick ross - rather you than me": 6,
    "little women - lung": 6,
    "future islands - the far field": 6,
    "bedwetter - volume 1: flick your tongue against your teeth and describe the present.": 6,
    "thundercat - drunk": 6,
    "jens lekman - life will see you now": 6,
    "lupe fiasco - drogas light": 6,
    "big sean - i decided.": 6,
    "sleaford mods - english tapas": 6,
    "j. cole - 4 your eyez only": 6,
    "ty segall - ty segall": 6,
    "the xx - i see you": 6,
    "iron reagan - crossover ministry": 6,
    "czarface - a fistful of peril": 6,
    "nicolas jaar - sirens": 6,
    "lady gaga - joanne": 6,
    "isaiah rashad - the sun's tirade": 6,
    "metallica - hardwired...to self-destruct": 6,
    "matmos & so percussion - treasure state": 6,
    "2814 - rain temple": 6,
    "bones - paidprogramming2": 6,
    "wilco - schmilco": 6,
    "the wytches - all your happy life": 6,
    "dj khaled - major key": 6,
    "gucci mane - everybody looking": 6,
    "nujabes - spiritual state": 6,
    "glass animals - how to be a human being": 6,
    "blood orange - freetown sound": 6,
    "kaytranada - 99.9%": 6,
    "rae sremmurd - sremmlife 2": 6,
    "pup - the dream is over": 6,
    "anohni - hopelessness": 6,
    "kvelertak - nattesferd": 6,
    "babymetal - metal resistance": 6,
    "babyfather - bbf hosted by dj escrow": 6,
    "future - evol": 6,
    "baauer - aa": 6,
    "ash koosha - i aka i": 6,
    "macklemore & ryan lewis - this unruly mess i've made": 6,
    "flatbush zombies - 3001: a laced odyssey": 6,
    "lee scott - butter fly": 6,
    "erykah badu - but you caint use my phone": 6,
    "cavanaugh - time & materials": 6,
    "revenge - behold.total.rejection": 6,
    "diiv - is the is are": 6,
    "lucinda williams - the ghosts of highway 20": 6,
    "busdriver - thumbs": 6,
    "cage the elephant - tell me i'm pretty": 6,
    "savages - adore life": 6,
    "arca - mutant": 6,
    "bloc party - hymns": 6,
    "boots - aquλria": 6,
    "logic - the incredible true story": 6,
    "sunn o))) - kannon": 6,
    "drake & future - what a time to be alive": 6,
    "the game - the documentary 2": 6,
    "hinds - leave me alone": 6,
    "jay rock - 90059": 6,
    "burzum - fallen": 6,
    "guilty simpson - oj simpson": 6,
    "black breath - slaves beyond death": 6,
    "anna von hausswolff - the miraculous": 6,
    "the front bottoms - back on top": 6,
    "alex g - beach music": 6,
    "deerhunter - fading frontier": 6,
    "grave babies - holographic violence": 6,
    "jesu/sun kil moon - jesu/sun kil moon": 6,
    "krallice - ygg huur": 6,
    "deafheaven - new bermuda": 6,
    "kurt vile - b'lieve i'm goin down": 6,
    "mick jenkins - wave[s]": 6,
    "hella - tripper": 6,
    "wilco - star wars": 6,
    "battles - la di da di": 6,
    "lapalux - when you're gone": 6,
    "future - ds2": 6,
    "the libertines - anthems for doomed youth": 6,
    "king los - god, money, war": 6,
    "new order - music complete": 6,
    "iron maiden - the book of souls": 6,
    "thundercat - the beyond / where the giants roam": 6,
    "mewithoutyou - ten stories": 6,
    "denzel curry - 32 zel / planet shrooms": 6,
    "disclosure - caracal": 6,
    "deradoorian - the expanding flower planet": 6,
    "myrkur - m": 6,
    "beach house - depression cherry": 6,
    "dr. yen lo - days with dr. yen lo": 6,
    "ty dolla $ign - free tc": 6,
    "autopsy - the headless ritual": 6,
    "the spits - the spits": 6,
    "vince staples - summertime '06": 6,
    "old man gloom - no": 6,
    "jim o'rourke - simple songs": 6,
    "earl sweatshirt - i don't like shit, i don't go outside": 6,
    "holly herndon - platform": 6,
    "3:33 - in the middle of infinity": 6,
    "oh sees - mutilator defeated at last": 6,
    "godspeed you! black emperor - asunder, sweet and other distress": 6,
    "steven wilson - hand. cannot. erase.": 6,
    "sun kil moon - universal themes": 6,
    "squarepusher - damogen furies": 6,
    "blanck mass - dumb flesh": 6,
    "faith no more - sol invictus": 6,
    "the tallest man on earth - dark bird is home": 6,
    "hot chip - why make sense?": 6,
    "xibalba - tierra y libertad": 6,
    "shlohmo - dark red": 6,
    "marching church - this world is not enough": 6,
    "matana roberts - coin coin chapter three: river run thee": 6,
    "pond - man it feels like space again": 6,
    "pile - you're better than this": 6,
    "of montreal - aureate gloom": 6,
    "lord mantis - death mask": 6,
    "tonetta - 777": 6,
    "j. cole - 2014 forest hills drive": 6,
    "badbadnotgood & ghostface killah - sour soul": 6,
    "mount eerie - sauna": 6,
    "screaming females - rose mountain": 6,
    "marilyn manson - the pale emperor": 6,
    "wu-tang clan - a better tomorrow": 6,
    "black milk - if there's a hell below": 6,
    "panda bear - mr noah": 6,
    "logic - under pressure": 6,
    "big k.r.i.t. - cadillactica": 6,
    "belle and sebastian - girls in peacetime want to dance": 6,
    "thom yorke - tomorrow's modern boxes": 6,
    "pink floyd - the endless river": 6,
    "clark - clark": 6,
    "arca - xen": 6,
    "tv on the radio - seeds": 6,
    "kayo dot - coffins on io": 6,
    "earth - primitive and deadly": 6,
    "aphex twin - syro": 6,
    "code orange - i am king": 6,
    "scott walker & sunn o))) - soused": 6,
    "iamamiwhoami - blue": 6,
    "this will destroy you - tunnel blanket": 6,
    "shellac - dude incredible": 6,
    "caustic window - caustic window lp": 6,
    "zammuto - anchor": 6,
    "zelooperz - help": 6,
    "joyce manor - never hungover again": 6,
    "bones - garbage": 6,
    "the bug - angels and devils": 6,
    "death from above 1979 - the physical world": 6,
    "blonde redhead - barragán": 6,
    "ty segall - manipulator": 6,
    "interpol - el pintor": 6,
    "pallbearer - foundations of burden": 6,
    "common - nobody's smiling": 6,
    "caribou - our love": 6,
    "blu - good to be home": 6,
    "mac miller - faces": 6,
    "agalloch - the serpent & the sphere": 6,
    "teebs - ardour": 6,
    "sleaford mods - divide and exit": 6,
    "eyehategod - eyehategod": 6,
    "todd terje - it's album time": 6,
    "nocando - jimmy the burnout": 6,
    "lykke li - i never learn": 6,
    "sharon van etten - are we there": 6,
    "the hotelier - home, like noplace is there": 6,
    "lil wayne - tha carter v": 6,
    "little dragon - nabuma rubberband": 6,
    "isaiah rashad - cilvia demo": 6,
    "sunn o))) & ulver - terrestrials": 6,
    "pianos become the teeth - the lack long after": 6,
    "cloud nothings - here and nowhere else": 6,
    "young fathers - dead": 6,
    "lee bannon - alternate/endings": 6,
    "circle takes the square - decompositions: volume number one": 6,
    "darkthrone - the underground resistance": 6,
    "iron maiden - the final frontier": 6,
    "tycho - awake": 6,
    "mø - no mythologies to follow": 6,
    "beyoncé - beyoncé": 6,
    "shad - tsol": 6,
    "anamanaguchi - endless fantasy": 6,
    "oranssi pazuzu - valonielu": 6,
    "årabrot - årabrot": 6,
    "death grips - government plates": 6,
    "action bronson / party supplies - blue chips 2": 6,
    "mogwai - rave tapes": 6,
    "crystal stilts - nature noir": 6,
    "sisu - blood tears": 6,
    "m.i.a. - vicki leekx": 6,
    "holograms - forever": 6,
    "watain - lawless darkness": 6,
    "dead in the dirt - the blind hole": 6,
    "earl sweatshirt - doris": 6,
    "lady gaga - artpop": 6,
    "pusha t - my name is my name": 6,
    "meshuggah - koloss": 6,
    "locrian - return to annihilation": 6,
    "factory floor - factory floor": 6,
    "oneohtrix point never - r plus seven": 6,
    "jay-z - magna carta holy grail": 6,
    "nine inch nails - hesitation marks": 6,
    "mac miller - watching movies with the sound off": 6,
    "r.a. the rugged man - legends never die": 6,
    "no age - an object": 6,
    "washed out - paracosm": 6,
    "fuck buttons - slow focus": 6,
    "chance the rapper - acid rap": 6,
    "co la - moody coup": 6,
    "boards of canada - tomorrow's harvest": 6,
    "classixx - hanging gardens": 6,
    "mgmt - mgmt": 6,
    "bonobo - the north borders": 6,
    "deerhunter - monomania": 6,
    "baths - obsidian": 6,
    "rhye - woman": 6,
    "czarface - czarface": 6,
    "tyler, the creator - wolf": 6,
    "dumbo gets mad - quantum leap": 6,
    "adam green & binki shapiro - adam green & binki shapiro": 6,
    "the flaming lips - the terror": 6,
    "tomahawk - oddfellows": 6,
    "california x - california x": 6,
    "wavves - afraid of heights": 6,
    "electric wizard - black masses": 6,
    "dragged into sunlight - widowmaker": 6,
    "code orange kids - love is love // return to dust": 6,
    "guardian alien - see the world given to a one love entity": 6,
    "phosphorescent - muchacho": 6,
    "wu-block - wu-block": 6,
    "veronica falls - waiting for something to happen": 6,
    "deftones - koi no yokan": 6,
    "pig destroyer - book burner": 6,
    "mac demarco - 2": 6,
    "metz - metz": 6,
    "miguel - kaleidoscope dream": 6,
    "brian eno - lux": 6,
    "daphni - jiaolong": 6,
    "jj doom - key to the kuffs": 6,
    "titus andronicus - local business": 6,
    "mumford & sons - babel": 6,
    "grizzly bear - shields": 6,
    "how to dress well - total loss": 6,
    "rush - clockwork angels": 6,
    "holy other - held": 6,
    "ariel pink's haunted graffiti - mature themes": 6,
    "animal collective - centipede hz": 6,
    "niki & the dove - instinct": 6,
    "purity ring - shrines": 6,
    "passion pit - gossamer": 6,
    "dirty projectors - swing lo magellan": 6,
    "the smashing pumpkins - oceania": 6,
    "mission of burma - unsound": 6,
    "el-p - cancer 4 cure": 6,
    "bobby womack - the bravest man in the universe": 6,
    "squarepusher - ufabulum": 6,
    "moonface - with siinai: heartbreaking bravery": 6,
    "lotus plaza - spooky action at a distance": 6,
    "evian christ - kings and them": 6,
    "jack white - blunderbuss": 6,
    "gonjasufi - mu.zz.le": 6,
    "guided by voices - let's go eat the factory": 6,
    "earth - angels of darkness, demons of light ii": 6,
    "machinedrum - room(s)": 6,
    "kuedo - severant": 6,
    "crystal stilts - radiant door": 6,
    "the black keys - el camino": 6,
    "j. cole - cole world: the sideline story": 6,
    "drake - take care": 6,
    "wolves in the throne room - celestial lineage": 6,
    "atlas sound - parallax": 6,
    "lou reed & metallica - lulu": 6,
    "cass mccombs - humor risk": 6,
    "active child - you are all i see": 6,
    "future islands - on the water": 6,
    "the men - leave home": 6,
    "mellowhype - blackenedwhite": 6,
    "das racist - relax": 6,
    "portugal. the man - in the mountain in the cloud": 6,
    "my brightest diamond - all things will unwind": 6,
    "bad meets evil - hell: the sequel": 6,
    "beirut - the rip tide": 6,
    "the war on drugs - slave ambient": 6,
    "washed out - within and without": 6,
    "bon iver - bon iver, bon iver": 6,
    "boris - heavy rocks": 6,
    "the vaccines - what did you expect from the vaccines?": 6,
    "tv on the radio - nine types of light": 6,
    "foo fighters - wasting light": 6,
    "radiohead - the king of limbs": 6,
    "bill callahan - apocalypse": 6,
    "john vanderslice - white wilderness": 6,
    "das racist - shut up, dude": 6,
    "toro y moi - underneath the pine": 6,
    "villagers - becoming a jackal": 6,
    "iron & wine - kiss each other clean": 6,
    "warpaint - the fool": 6,
    "kanye west - my beautiful dark twisted fantasy": 6,
    "swans - my father will guide me up a rope to the sky": 6,
    "sufjan stevens - the age of adz": 6,
    "belle and sebastian - write about love": 6,
    "autolux - transit transit": 6,
    "black mountain - wilderness heart": 6,
    "no age - everything in between": 6,
    "kid cudi - man on the moon ii: the legend of mr. rager": 6,
    "devo - something for everybody": 6,
    "emeralds - does it look like i'm here?": 6,
    "tame impala - innerspeaker": 6,
    "big boi - sir lucious left foot: the son of chico dusty": 6,
    "the national - high violet": 6,
    "happy birthday - happy birthday": 6,
    "wolf parade - expo 86": 6,
    "the morning benders - big echo": 6,
    "liars - sisterworld": 6,
    "jónsi - go": 6,
    "caribou - swim": 6,
    "harry styles - fine line": 5,
    "earl sweatshirt - feet of clay": 5,
    "uncommon nasa & kount fif - city as school": 5,
    "coldplay - everyday life": 5,
    "westside gunn - hitler wears hermes 7": 5,
    "rex orange county - pony": 5,
    "dababy - kirk": 5,
    "post malone - hollywood's bleeding": 5,
    "battles - juice b crypts": 5,
    "sturgill simpson - sound & fury": 5,
    "daniel caesar - case study 01": 5,
    "chelsea wolfe - birth of violence": 5,
    "alex g - house of sugar": 5,
    "clairo - immunity": 5,
    "sleater-kinney - the center won't hold": 5,
    "flying lotus - flamagra": 5,
    "schoolboy q - crash talk": 5,
    "the raconteurs - help us stranger": 5,
    "rammstein - rammstein": 5,
    "baroness - gold & grey": 5,
    "bts - map of the soul : persona": 5,
    "holly herndon - proto": 5,
    "dave - psychodrama": 5,
    "big thief - u.f.o.f.": 5,
    "cage the elephant - social cues": 5,
    "bad bunny - x 100pre": 5,
    "czarface & ghostface killah - czarface meets ghostface": 5,
    "meek mill - championships": 5,
    "action bronson - white bronco": 5,
    "future & juice wrld - future & juice wrld present... wrld on drugs": 5,
    "joji - ballads 1": 5,
    "muse - simulation theory": 5,
    "logic - ysiv": 5,
    "trippie redd - life's a trip": 5,
    "88rising - head in the clouds": 5,
    "the carters - everything is love": 5,
    "busdriver - electricity is on our side": 5,
    "juice wrld - goodbye & good riddance": 5,
    "nicki minaj - queen": 5,
    "slim jxmmi - jxmtro": 5,
    "yg - stay dangerous": 5,
    "deerhunter - why hasn't everything already disappeared?": 5,
    "deafheaven - ordinary corrupt human love": 5,
    "j. cole - kod": 5,
    "arctic monkeys - tranquility base hotel & casino": 5,
    "the weeknd - my dear melancholy,": 5,
    "logic - bobby tarantino ii": 5,
    "unknown mortal orchestra - sex & food": 5,
    "a perfect circle - eat the elephant": 5,
    "daniel avery - song for alpha": 5,
    "preoccupations - new material": 5,
    "turnstile - time & space": 5,
    "titus andronicus - a productive cough": 5,
    "big sean & metro boomin - double or nothing": 5,
    "cyhi the prynce - no dope on sundays": 5,
    "wiley - godfather ii": 5,
    "skepta - vicious": 5,
    "fever ray - plunge": 5,
    "tune-yards - i can feel you creep into my private life": 5,
    "future & young thug - super slimey": 5,
    "trippie redd - a love letter to you 2": 5,
    "marilyn manson - heaven upside down": 5,
    "kodak black - project baby 2": 5,
    "gucci mane - mr. davis": 5,
    "negură bunget - tau": 5,
    "destroyer - ken": 5,
    "the secret - agnus dei": 5,
    "rotten sound - cursed": 5,
    "king gizzard and the lizard wizard with mild high club - sketches of brunswick east": 5,
    "lil b - black ken": 5,
    "ugly god - the booty tape": 5,
    "godspeed you! black emperor - luciferian towers": 5,
    "benjamin clementine - i tell a fly": 5,
    "liars - tfcf": 5,
    "aminé - good for you": 5,
    "young thug - beautiful thugger girls": 5,
    "the war on drugs - a deeper understanding": 5,
    "shabazz palaces - quazarz vs. the jealous machines": 5,
    "dizzy wright - the golden age": 5,
    "haim - something to tell you": 5,
    "logic - everybody": 5,
    "sufjan stevens, bryce dessner, nico muhly & james mcalister - planetarium": 5,
    "gorillaz - humanz": 5,
    "goldlink - at what cost": 5,
    "alt-j - relaxer": 5,
    "beach fossils - somersault": 5,
    "alex g - rocket": 5,
    "arca - arca": 5,
    "future - future": 5,
    "real estate - in mind": 5,
    "timber timbre - sincerely, future pollution": 5,
    "little simz - stillness in wonderland": 5,
    "drake - more life": 5,
    "laura marling - semper femina": 5,
    "a$ap mob - cozy tapes vol. 1 friends": 5,
    "the flaming lips - oczy mlody": 5,
    "common - black america again": 5,
    "the weeknd - starboy": 5,
    "justice - woman": 5,
    "the faceless - autotheism": 5,
    "the game - 1992": 5,
    "kreator - phantom antichrist": 5,
    "mick jenkins - the healing component": 5,
    "bon iver - 22, a million": 5,
    "banks - the altar": 5,
    "lil yachty - summer songs 2": 5,
    "ajj - the bible 2": 5,
    "logic - bobby tarantino": 5,
    "schoolboy q - blank face lp": 5,
    "descendents - hypercaffium spazzinate": 5,
    "vic mensa - there's alot going on": 5,
    "of montreal - innocence reaches": 5,
    "jon bellion - the human condition": 5,
    "tera melos - patagonian rats": 5,
    "james blake - the colour in anything": 5,
    "red hot chili peppers - the getaway": 5,
    "flume - skin": 5,
    "young thug - slime season 3": 5,
    "bat for lashes - the bride": 5,
    "bas - too high to riot": 5,
    "tim hecker - love streams": 5,
    "young thug - i'm up": 5,
    "lil ugly mane - oblivion access": 5,
    "animal collective - painting with": 5,
    "wild nothing - life of pause": 5,
    "spooky black - leaving": 5,
    "porches - pool": 5,
    "coldplay - a head full of dreams": 5,
    "big k.r.i.t. - it's better this way": 5,
    "justin bieber - purpose": 5,
    "beach house - thank your lucky stars": 5,
    "kirk knight - late knight special": 5,
    "raury - all we need": 5,
    "the wonder years - no closer to heaven": 5,
    "darkthrone - circle the wagons": 5,
    "fetty wap - fetty wap": 5,
    "the garden - haha": 5,
    "lana del rey - honeymoon": 5,
    "samiyam - sam baker's album": 5,
    "chvrches - every open eye": 5,
    "the weeknd - beauty behind the madness": 5,
    "foals - what went down": 5,
    "the internet - ego death": 5,
    "miguel - wildheart": 5,
    "health - death magic": 5,
    "a$ap rocky - at.long.last.a$ap": 5,
    "young thug - barter 6": 5,
    "mewithoutyou - pale horses": 5,
    "desaparecidos - payola": 5,
    "hiatus kaiyote - choose your weapon": 5,
    "9th wonder - the wonder years": 5,
    "muse - drones": 5,
    "hudson mohawke - lantern": 5,
    "shamir - ratchet": 5,
    "fashawn - the ecology": 5,
    "cannibal ox - blade of the ronin": 5,
    "courtney barnett - sometimes i sit and think, and sometimes i just sit": 5,
    "drenge - undertow": 5,
    "torres - sprinter": 5,
    "death cab for cutie - kintsugi": 5,
    "snoop dogg - bush": 5,
    "action bronson - mr. wonderful": 5,
    "modest mouse - strangers to ourselves": 5,
    "dan deacon - gliss riffer": 5,
    "trap them - blissfucker": 5,
    "ghostface killah - 36 seasons": 5,
    "hail mary mallon - bestiary": 5,
    "migos - no label 2": 5,
    "the world is a beautiful place and i am no longer afraid to die - between bodies": 5,
    "milo - a toothpaste suburb": 5,
    "the underachievers - lords of flatbush": 5,
    "nehruviandoom - nehruviandoom": 5,
    "royal blood - royal blood": 5,
    "pharmakon - bestial burden": 5,
    "michael cera - true that": 5,
    "foo fighters - sonic highways": 5,
    "porter robinson - worlds": 5,
    "sbtrkt - wonder where we land": 5,
    "electric wizard - time to die": 5,
    "ab-soul - these days...": 5,
    "morrissey - world peace is none of your business": 5,
    "shabazz palaces - lese majesty": 5,
    "banks - goddess": 5,
    "opeth - pale communion": 5,
    "andrew jackson jihad - christmas island": 5,
    "trash talk - no peace": 5,
    "ben frost - a u r o r a": 5,  # not on spotify?
    "jack white - lazaretto": 5,
    "chromeo - white women": 5,
    "skrillex - recess": 5,
    "avey tare's slasher flicks - enter the slasher house": 5,
    "mac demarco - salad days": 5,
    "damon albarn - everyday robots": 5,
    "riff raff - neon icon": 5,
    "against me! - transgender dysphoria blues": 5,
    "burial - rival dealer": 5,
    "childish gambino - because the internet": 5,
    "temples - sun structures": 5,
    "angel olsen - burn your fire for no witness": 5,
    "gesaffelstein - aleph": 5,
    "arcade fire - reflektor": 5,
    "dawn of midi - dysnomia": 5,
    "alcest - les voyages de l'âme": 5,
    "the weeknd - kiss land": 5,
    "letlive. - the blackest beautiful": 5,
    "röyksopp - senior": 5,
    "drake - nothing was the same": 5,
    "j. cole - born sinner": 5,
    "steven wilson - the raven that refused to sing (and other stories)": 5,
    "mac miller - blue slide park": 5,
    "kanye west - yeezus": 5,
    "zomby - with love": 5,
    "ghost - infestissumam": 5,
    "portal - vexovoid": 5,
    "cult of luna - vertikal": 5,
    "the strokes - comedown machine": 5,
    "thee oh sees - floating coffin": 5,
    "justin timberlake - the 20/20 experience": 5,
    "phoenix - bankrupt!": 5,
    "nosaj thing - home": 5,
    "yeah yeah yeahs - mosquito": 5,
    "azealia banks - broke with expensive taste": 5,
    "the game - jesus piece": 5,
    "nick cave & the bad seeds - push the sky away": 5,
    "ratking - wiki93": 5,
    "heems - wild water kingdom": 5,
    "tim hecker & daniel lopatin - instrumental tourist": 5,
    "foals - holy fire": 5,
    "local natives - hummingbird": 5,
    "black moth super rainbow - cobra juicy": 5,
    "p.o.s. - we don't even live here": 5,
    "efterklang - piramida": 5,
    "mount eerie - ocean roar": 5,
    "goat - world music": 5,
    "domo genesis & the alchemist - no idols": 5,
    "om - advaitic songs": 5,
    "lupe fiasco - food & liquor 2: the great american rap album pt. 1": 5,
    "spaceghostpurrp - mysterious phonk: the chronicles of spaceghostpurrp": 5,
    "big boi - vicious lies and dangerous rumors": 5,
    "dan deacon - america": 5,
    "twin shadow - confess": 5,
    "actress - r.i.p.": 5,
    "quakers - quakers": 5,
    "japandroids - celebration rock": 5,
    "schoolboy q - habits & contradictions": 5,
    "black dice - mr. impossible": 5,
    "the maccabees - given to the wild": 5,
    "the shins - port of morrow": 5,
    "the magnetic fields - love at the bottom of the sea": 5,
    "cage the elephant - thank you happy birthday": 5,
    "sleigh bells - reign of terror": 5,
    "yelawolf - radioactive": 5,
    "leonard cohen - old ideas": 5,
    "a place to bury strangers - onwards to the wall": 5,
    "grimes - visions": 5,
    "opeth - heritage": 5,
    "james blake - enough thunder": 5,
    "david lynch - crazy clown time": 5,
    "justice - audio, video, disco": 5,
    "mastodon - the hunter": 5,
    "jay-z & kanye west - watch the throne": 5,
    "they might be giants - join us": 5,
    "the drums - portamento": 5,
    "unknown mortal orchestra - unknown mortal orchestra": 5,
    "wu lyf - go tell fire to the mountain": 5,
    "red hot chili peppers - i'm with you": 5,
    "jesu - ascension": 5,
    "the lonely island - turtleneck & chain": 5,
    "my morning jacket - circuital": 5,
    "fucked up - david comes to life": 5,
    "woods - sun & shade": 5,
    "arctic monkeys - suck it and see": 5,
    "raekwon - shaolin vs. wu-tang": 5,
    "yuck - yuck": 5,
    "explosions in the sky - take care, take care, take care": 5,
    "bibio - mind bokeh": 5,
    "panda bear - tomboy": 5,
    "wire - red barked tree": 5,
    "gorillaz - the fall": 5,
    "cut copy - zonoscope": 5,
    "girls - broken dreams club": 5,
    "zach hill - face tat": 5,
    "squarepusher - shobaleader one: d'demonstrator": 5,
    "mark ronson & the business intl - record collection": 5,
    "matt & kim - sidewalks": 5,
    "neil young - le noise": 5,
    "the budos band - the budos band iii": 5,
    "avey tare - down there": 5,
    "of montreal - false priest": 5,
    "the walkmen - lisbon": 5,
    "interpol - interpol": 5,
    "best coast - crazy for you": 5,
    "melvins - the bride screamed murder": 5,
    "club 8 - the people's record": 5,
    # "m.i.a. - /\/\/\y/" + '\\': 5,
    "autechre - oversteps": 5,
    "the dead weather - sea of cowards": 5,
    "broken bells - broken bells": 5,
    "trippie redd - a love letter to you 4": 4,
    "doja cat - hot pink": 4,
    "ameer vann - emmanuel": 4,
    "kanye west - jesus is king": 4,
    "tool - fear inoculum": 4,
    "big k.r.i.t. - k.r.i.t. iz here": 4,
    "young nudy & pi'erre bourne - sli'merre": 4,
    "beck - hyperspace": 4,
    "the national - i am easy to find": 4,
    "the mountain goats - in league with dragons": 4,
    "gus dapperton - where polly people go to read": 4,
    "comethazine - bawskee 2": 4,
    "6ix9ine - dummy boy": 4,
    "takeoff - the last rocket": 4,
    "beirut - gallipoli": 4,
    "lil peep - come over when you're sober, pt. 2": 4,
    "quavo - quavo huncho": 4,
    "6lack - east atlanta love letter": 4,
    "eminem - kamikaze": 4,
    "lil pump - harverd dropout": 4,
    "soap&skin - from gas to solid / you are my friend": 4,
    "interpol - marauder": 4,
    "a$ap rocky - testing": 4,
    "jay rock - redemption": 4,
    "drake - scorpion": 4,
    "princess nokia - a girl cried red": 4,
    "xxxtentacion - ?": 4,
    "panopticon - the scars of man on the once nameless wilderness part i and ii": 4,
    "kacey musgraves - golden hour": 4,
    "the neighbourhood - the neighbourhood": 4,
    "migos - culture ii": 4,
    "tiny moving parts - swell": 4,
    "hopsin - no shame": 4,
    "weezer - weezer (black album)": 4,
    "jaden - syre": 4,
    "sam smith - the thrill of it all": 4,
    "king krule - the ooz": 4,
    "taylor swift - reputation": 4,
    "weezer - pacific daydream": 4,
    "beck - colors": 4,
    "a$ap mob - cozy tapes vol. 2: too cozy": 4,
    "arcade fire - everything now": 4,
    "harry styles - harry styles": 4,
    "slowdive - slowdive": 4,
    "kodak black - painting pictures": 4,
    "mastodon - emperor of sand": 4,
    "ed sheeran - ÷": 4,
    "kid cudi - passion, pain & demon slayin'": 4,
    "oathbreaker - rheia": 4,
    "mac miller - the divine feminine": 4,
    "partynextdoor - partynextdoor 3 (p3)": 4,
    "korn - the serenity of suffering": 4,
    "m.i.a. - aim": 4,
    "crystal castles - amnesty (i)": 4,
    "lil uzi vert - lil uzi vert vs. the world": 4,
    "domo genesis - genesis": 4,
    "drake - views": 4,
    "zayn - mind of mine": 4,
    "deftones - gore": 4,
    "explosions in the sky - the wilderness": 4,
    "majid jordan - majid jordan": 4,
    "archy marshall - a new place 2 drown": 4,
    "rihanna - anti": 4,
    "the 1975 - i like it when you sleep, for you are so beautiful yet so unaware of it": 4,
    "g-eazy - when it's dark out": 4,
    "megadeth - dystopia": 4,
    "med, blu & madlib - bad neighbor": 4,
    "james ferraro - skid row": 4,
    "wavves - v": 4,
    "lil wayne - free weezy album": 4,
    "burzum - belus": 4,
    "fidlar - too": 4,
    "donnie trumpet & the social experiment - surf": 4,
    "watsky - all you can do": 4,
    "titus andronicus - the most lamentable tragedy": 4,
    "refused - freedom": 4,
    "twenty one pilots - blurryface": 4,
    "between the buried and me - the parallax ii: future sequence": 4,
    "riff raff - the peach panther": 4,
    "ratking - 700 fill": 4,
    "purity ring - another eternity": 4,
    "wale - the album about nothing": 4,
    "heems - eat pray thug": 4,
    "title fight - hyperview": 4,
    "childish gambino - kauai": 4,
    "panda bear - panda bear meets the grim reaper": 4,
    "pianos become the teeth - keep you": 4,
    "childish gambino - stn mtn": 4,
    "xasthur - portal of sorrow": 4,
    "yung lean - unknown memory": 4,
    "slipknot - .5: the gray chapter": 4,
    "raury - indigo child": 4,
    "fallujah - the flesh prevails": 4,
    "the roots - ...and then you shoot your cousin": 4,
    "sza - z": 4,
    "parquet courts - sunbathing animal": 4,
    "pixies - indie cindy": 4,
    "the black keys - turn blue": 4,
    "coldplay - ghost stories": 4,
    "beck - morning phase": 4,
    "sky ferreira - night time, my time": 4,
    "cults - static": 4,
    "jonathan rado - law and order": 4,
    "tech n9ne - something else": 4,
    "bring me the horizon - sempiternal": 4,
    "the national - trouble will find me": 4,
    "iggy & the stooges - ready to die": 4,
    "the men - new moon": 4,
    "macintosh plus - floral shoppe": 4,
    "chief keef - finally rich": 4,
    "the soft moon - zeros": 4,
    "toro y moi - anything in return": 4,
    "crystal castles - (iii)": 4,
    "2 chainz - based on a t.r.u. story": 4,
    "jessie ware - devotion": 4,
    "the xx - coexist": 4,
    "nas - life is good": 4,
    "b.o.b. - strange clouds": 4,
    "chromatics - kill for love": 4,
    "willis earl beal - acousmatic sorcery": 4,
    "odd future - the of tape vol. 2": 4,
    "tennis - young & old": 4,
    "the internet - purple naked ladies": 4,
    "wale - ambition": 4,
    "feist - metals": 4,
    "m83 - hurry up, we're dreaming": 4,
    "the cool kids - when fish ride bicycles": 4,
    "manchester orchestra - simple math": 4,
    "boris - attention please": 4,
    "cults - cults": 4,
    "tyler, the creator - goblin": 4,
    "the antlers - burst apart": 4,
    "the kills - blood pressures": 4,
    "white lies - ritual": 4,
    "black milk - album of the year": 4,
    "the decemberists - the king is dead": 4,
    "the fresh & onlys - play it strange": 4,
    "how to dress well - love remains": 4,
    "abe vigoda - crush": 4,
    "kings of leon - come around sundown": 4,
    "klaxons - surfing the void": 4,
    "foals - total life forever": 4,
    "broken social scene - forgiveness rock record": 4,
    "jaden - erys": 3,
    "pi'erre bourne - the life of pi'erre 4": 3,
    "steve lacy - apollo xxi": 3,
    "have a nice life - sea of worry": 3,
    "mac demarco - here comes the cowboy": 3,
    "tyler, the creator - music inspired by illumination & dr. seuss' the grinch": 3,
    "maggie rogers - heard it in a past life": 3,
    "russ - zoo": 3,
    "mac miller - swimming": 8,
    "valee - good job, you found me": 3,
    "6ix9ine - day69": 3,
    "justin timberlake - man of the woods": 3,
    "tory lanez - memories don't die": 3,
    "lil uzi vert - luv is rage 2": 3,
    "macklemore - gemini": 3,
    "21 savage - issa album": 3,
    "shabazz palaces - quazarz: born on a gangster star": 3,
    "green day - revolution radio": 3,
    "lil uzi vert - the perfect luv tape": 3,
    "travis scott - birds in the trap sing mcknight": 3,
    "kodak black - lil b.i.g. pac": 3,
    "the strokes - future present past": 3,
    "m83 - junk": 3,
    "yung lean - warlord": 3,
    "willow - ardipithecus": 3,
    "twitching tongues - disharmony": 3,
    "machine gun kelly - general admission": 3,
    "daughter - not to disappear": 3,
    "lil b - angels exodus": 3,
    "foxing - dealer": 3,
    "hopsin - pound syndrome": 3,
    "citizen - everybody is going to heaven": 3,
    "anika - anika": 3,
    "tyler, the creator - cherry bomb": 3,
    "yelawolf - love story": 3,
    "portico - living fields": 3,
    "twin shadow - eclipse": 3,
    "travi$ scott - owl pharaoh": 3,
    "travi$ scott - days before rodeo": 3,
    "rustie - green language": 3,
    "lone - reality testing": 3,
    "chet faker - built on glass": 3,
    "pharrell williams - g i r l": 3,
    "the glitch mob - love death immortality": 3,
    "real estate - atlas": 3,
    "hopsin - knock madness": 3,
    "arctic monkeys - am": 3,
    "edward sharpe & the magnetic zeros - edward sharpe & the magnetic zeros": 3,
    "thundercat - apocalypse": 3,
    "charli xcx - true romance": 3,
    "strfkr - miracle mile": 3,
    "tegan and sara - heartthrob": 3,
    "bad brains - into the future": 3,
    "slaughterhouse - welcome to: our house": 3,
    "mellowhype - numbers": 3,
    "a$ap mob - lords never worry": 3,
    "muse - the 2nd law": 3,
    "rick ross - god forgives, i don't": 3,
    "marilyn manson - born villain": 3,
    "curren$y - the stoned immaculate": 3,
    "best coast - the only place": 3,
    "wzrd - wzrd": 3,
    "metric - synthetica": 3,
    "lamb of god - resolution": 3,
    "jj - kills": 3,
    "lana del rey - born to die": 3,
    "cerebral ballzy - cerebral ballzy": 3,
    "neon indian - era extraña": 3,
    "portugal. the man - american ghetto": 3,
    "the weeknd - house of balloons": 3,
    "lil wayne - tha carter iv": 3,
    "lupe fiasco - lasers": 3,
    "beady eye - different gear, still speeding": 3,
    "sleigh bells - treats": 3,
    "the knife in collaboration with mt. sims and planningtorock - tomorrow, in a year": 3,
    "blink-182 - nine": 2,
    "gunna - drip or drown 2": 2,
    "xxxtentacion - skins": 2,
    "jaden - the sunset tapes: a cool tape story": 2,
    "lil yachty - nuthin' 2 prove": 2,
    "eminem - revival": 2,
    "xxxtentacion - 17": 2,
    "lil yachty - teenage emotions": 2,
    "gas - narkopop": 2,
    "spark master tape - silhouette of a sunkken city": 2,
    "a$ap ferg - always strive and prosper": 2,
    "goldlink - and after that, we didn't talk": 2,
    "lil dicky - professional rapper": 2,
    "partynextdoor - partynextdoor two": 2,
    "foxygen - ...and star power": 2,
    "lana del rey - ultraviolence": 2,
    "john frusciante - enclosure": 2,
    "blood orange - cupid deluxe": 2,
    "afi - burials": 2,
    "future - honest": 2,
    "john frusciante - pbx funicular intaglio zone": 2,
    "kid cudi - indicud": 2,
    "childish gambino - camp": 2,
    "planningtorock - w": 2,
    "uffie - sex dreams and denim jeans": 2,
    "salem - king night": 2,
    "93punx - 93punx": 1,
    "miley cyrus - she is coming": 1,
    "logic - confessions of a dangerous mind": 1,
    "bladee - red light": 1,
    "swae lee - swaecation": 1,
    "miley cyrus - miley cyrus & her dead petz": 1,
    "dance gavin dance - instant gratification": 1,
    "chance the rapper - the big day": 0,
    "kid cudi - speedin' bullet 2 heaven": 0,
    # MISSING
    "beyoncé - homecoming: the live album": 8,
    "jackboys & travis scott - jackboys": 5,
    "kendrick lamar - untitled unmastered.": 8,  # correct?
    "prince - originals": 8,
    "jai paul - leak 04-13 (bait ones)": 6,
    'childish gambino - "awaken, my love!"': 7,
    "kendrick lamar & sza - black panther the album music from and inspired by": 6,
    "lcd soundsystem - electric lady sessions": 6,
    "moses sumney - græ": 7,  # part 1 supposed to be there?
}

titles_manual = {
    # 2010s
    # TYPOS
    "jid - dicaprio 2": 8,
    "haru nemuri - harutosyura": 8,
    "car seat headrest - twin fantasy": 8,
    "kyary pamyu pamyu - なんだこれくしょん": 8,
    "jeffrey lewis - works by tuli kupferberg (1923-2010)": 7,
    "milo - who told you to think??!!?!?!?!": 7,
    "sumac & keiji haino - american dollar bill - keep facing sideways, you're too hideous to look at face on": 7,
    "santigold - 99 cents": 7,
    "dām-funk - invite the light": 7,
    "carly rae jepsen - emotion": 7,
    "carly rae jepsen - emotion: side b": 8,  # not on spotify
    "bts - love yourself 轉 'tear'": 6,
    "erykah badu - but you caint use my phone (mixtape)": 6,
    "action bronson & party supplies - blue chips 2": 6,  # not on spotify
    "code orange kids - love is love / return to dust": 6,
    "a$ap mob - cozy tapes: vol. 1 friends -": 5,
    "pi’erre bourne - the life of pi'erre 4": 3,
    "bon iver - bon iver": 6,
    "a$ap rocky - live.love.a$ap": 8,
    "foals - everything not saved will be lost part i": 6,
    "21 savage & offset & metro boomin - without warning": 7,
    "flume - hi this is flume (mixtape)": 8,
    "ghostface killah & adrian younge & linear labs - adrian younge presents: 12 reasons to die i": 8,
    "idles - joy as an act of resistance.": 9,
    "jay-z - magna carta... holy grail": 6,
    "vein.fm - errorzone": 6,
    "earl sweatshirt - i don't like shit, i don't go outside: an album by earl sweatshirt": 6,
    # "and" vs "&"
    "king gizzard & the lizard wizard - infest the rats' nest": 8,
    "king gizzard & the lizard wizard - flying microtonal banana": 8,
    "king gizzard & the lizard wizard - nonagon infinity": 8,
    "king gizzard & the lizard wizard - fishing for fishies": 7,
    "king gizzard & the lizard wizard - gumboot soup": 7,
    "king gizzard & the lizard wizard - polygondwanaland": 7,
    "king gizzard & the lizard wizard - paper mâché dream balloon": 7,
    "king gizzard & the lizard wizard - murder of the universe": 6,
    "king gizzard & the lizard wizard - sketches of brunswick east": 5,
    "the world is a beautiful place & i am no longer afraid to die - harmlessness": 7,
    "the world is a beautiful place & i am no longer afraid to die - whenever, if ever": 7,
    "the world is a beautiful place & i am no longer afraid to die - always foreign": 6,
    "the world is a beautiful place & i am no longer afraid to die - between bodies": 5,

    # 2020s
    "ichiko aoba - windswept adan": 9,
    "haru nemuri - shunka ryougen": 7,
    "tricot - 上出来": 7,
    "xibalba - años en infierno": 6,
    "floating points & pharoah sanders - promises": 9,
    "blu & exile & blu & exile - miles": 9,
    "danger mouse & black thought - cheat codes": 8,
    "death's dynamic shroud - faith in persona": 8,
}
