titles_only_2020s = {
	"sinner get ready": 10,
	"the turning wheel": 10,
	"hostile architecture": 9,
	"de todas las flores": 9,
	"the forever story": 9,
	"hellfire": 9,
	"cave world": 9,
	"baby": 9,
	"diaspora problems": 9,
	"god don't make mistakes": 9,
	"dragon new warm mountain i believe in you": 9,
	"ants from up there": 9,
	"marchita": 9,
	"kick iii": 9,
	"henki": 9,
	"lp! (offline version)": 9,
	"lp!": 9,
	"by the time i get to phoenix": 9,
	"daddy's home": 9,
	"promises": 9,
	"アダンの風 (windswept adan)": 9,
	"visions of bodies being burned": 9,
	"last year was weird, vol. 2": 9,
	"miles": 9,
	"what's your pleasure?": 9,
	"peaceful as hell": 9,
	"song for our daughter": 9,
	"ugly": 8,
	"dogsbody": 8,
	"in the fade": 8,
	"desire, i want to turn into you": 8,
	"this is why": 8,
	"after the magic": 8,
	"sos": 8,
	"white trash revelry": 8,
	"the ruby cord": 8,
	"king's disease iii": 8,
	"laminated denim": 8,
	"his happiness shall come first even though we are suffering": 8,
	"luv 4 rent": 8,
	"morbidity triumphant": 8,
	"$oul $old $eparately": 8,
	"free lsd": 8,
	"hyper-dimensional expansion beam": 8,
	"darklife": 8,
	"natural brown prom queen": 8,
	"age/sex/location": 8,
	"i love you jennifer b": 8,
	"louie": 8,
	"cheat codes": 8,
	"too much to ask": 8,
	"meridian brothers & el grupo renacimiento": 8,
	"renaissance": 8,
	"god's country": 8,
	"hiss": 8,
	"shape up": 8,
	"drill music in zion": 8,
	"bothered/unbothered": 8,
	"artificial brain": 8,
	"the loser": 8,
	"mr. morale & the big steppers": 8,
	"super champon": 8,
	"everything was beautiful": 8,
	"it's almost dry": 8,
	"you belong there": 8,
	"aethiopes": 8,
	"american gurl": 8,
	"melt my eyez see your future": 8,
	"crest": 8,
	"tana talk 4": 8,
	"topical dancer": 8,
	"forget your own face": 8,
	"once twice melody": 8,
	"crystalline exhaustion": 8,
	"fawn": 8,
	"caprisongs": 8,
	"dawn fm": 8,
	"faith in persona": 8,
	"fatigue": 8,
	"actually, you can": 8,
	"madison": 8,
	"friends that break your heart": 8,
	"mercurial world": 8,
	"the color blu(e)": 8,
	"let me do one more": 8,
	"half god": 8,
	"hitler wears hermes 8: side b": 8,
	"a beginner's mind": 8,
	"hey what": 8,
	"sometimes i might be introvert": 8,
	"glow on": 8,
	"gumbo'!": 8,
	"stand for myself": 8,
	"king's disease ii": 8,
	"twin shadow": 8,
	"call me if you get lost": 8,
	"i lie here buried with my rings and my dresses": 8,
	"cavalcade": 8,
	"...and again into the light": 8,
	"rainbow bridge 3": 8,
	"nurture": 8,
	"ska dream": 8,
	"roadrunner: new light, new machine": 8,
	"haram": 8,
	"palais d'argile": 8,
	"smiling with no teeth": 8,
	"carnage": 8,
	"imperative imperceptible impulse": 8,
	"forever in your heart": 8,
	"tyron": 8,
	"for the first time": 8,
	"ok human": 8,
	"brass": 8,
	"heaux tales": 8,
	"welfare jazz": 8,
	"manger on mcnichols": 8,
	"little dominiques nosebleed": 8,
	"origin of the alimonies": 8,
	"lesions of a different kind": 8,
	"starting over": 8,
	"post human: survival horror": 8,
	"songs": 8,
	"song machine, season one: strange timez": 8,
	"my agenda": 8,
	"ultra mono": 8,
	"shabrang": 8,
	"american head": 8,
	"from king to a god": 8,
	"cumbia siglo xxi": 8,
	"the consuming flame: open exercises in group form": 8,
	"alphaville": 8,
	"lianne la havas": 8,
	"no": 8,
	"women in music pt. iii": 8,
	"punisher": 8,
	"true opera": 8,
	"ungodly hour": 8,
	"rtj4": 8,
	"future teenage cave artists": 8,
	"alfredo": 8,
	"god has nothing to do with this leave him out of it": 8,
	"no dream": 8,
	"set my heart on fire immediately": 8,
	"how i'm feeling now": 8,
	"un canto por méxico, vol. 1": 8,
	"home body": 8,
	"innocent country 2": 8,
	"miss colombia": 8,
	"sawayama": 8,
	"the new abnormal": 8,
	"cenizas": 8,
	"the common task": 8,
	"purple moonlight pages": 8,
	"underneath": 8,
	"man alive!": 8,
	"west of eden": 8,
	"2017": 8,
	"unlocked": 8,
	"mystic familiar": 8,
	"i disagree": 8,
	"circles": 8,
	"red moon in venus": 7,
	"food for worms": 7,
	"aftërlyfe": 7,
	"quest for fire": 7,
	"heavy heavy": 7,
	"comradely objects": 7,
	"let's start here.": 7,
	"sznz: winter": 7,
	"languish arts": 7,
	"woeful studies": 7,
	"no thank you": 7,
	"heroes & villains": 7,
	"and in the darkness, hearts aglow": 7,
	"i didn't mean to haunt you": 7,
	"changes": 7,
	"ice, death, planets, lungs, mushrooms and lava": 7,
	"component system with the auto reverse": 7,
	"10": 7,
	"bin reaper 3: old testament": 7,
	"being funny in a foreign language": 7,
	"chaos now*": 7,
	"blue rev": 7,
	"spiderr": 7,
	"god save the animals": 7,
	"horseshit on route 66": 7,
	"there will be no super-slave": 7,
	"spirit of ecstasy": 7,
	"get fucked": 7,
	"heavy rocks": 7,
	"beatopia": 7,
	"not tight": 7,
	"2000": 7,
	"gemini rights": 7,
	"formentera": 7,
	"arkhon": 7,
	"psychagogue": 7,
	"sometimes, forever": 7,
	"ugly season": 7,
	"vinyl days": 7,
	"big time": 7,
	"killing nothing": 7,
	"ugly death no redemption angel curse i love you": 7,
	"raw data feel": 7,
	"deathfame": 7,
	"dance fever": 7,
	"a light for attracting attention": 7,
	"mahal": 7,
	"春火燎原 (shunka ryougen)": 7,
	"it's time...to rise from the grave": 7,
	"bronco": 7,
	"fear of the dawn": 7,
	"d-day: a gangsta grillz mixtape": 7,
	"electricity": 7,
	"motomami": 7,
	"who cares?": 7,
	"before shit got weird": 7,
	"painless": 7,
	"4nem": 7,
	"ghetto gods": 7,
	"lucifer on the sofa": 7,
	"glitch princess": 7,
	"time skiffs": 7,
	"before the glinting spell unvests": 7,
	"three dimensions deep": 7,
	"the overload": 7,
	"上出来 (jodeki)": 7,
	"magic": 7,
	"eternal home": 7,
	"kick iiiii": 7,
	"kick ii": 7,
	"nice one": 7,
	"delta estácio blues": 7,
	"bloodmoon: i": 7,
	"frailty": 7,
	"30": 7,
	"garbology": 7,
	"an evening with silk sonic": 7,
	"still over it": 7,
	"absolutely": 7,
	"the path of the clouds": 7,
	"volcanic bird enemy and the voiced concern": 7,
	"juno": 7,
	"talk memory": 7,
	"nine": 7,
	"the long and short of it": 7,
	"torn arteries": 7,
	"any shape you take": 7,
	"montero": 7,
	"a martyr's reward": 7,
	"donda": 7,
	"bo jackson": 7,
	"pressure machine": 7,
	"animal": 7,
	"happier than ever": 7,
	"house of lull . house of when": 7,
	"spiral": 7,
	"sling": 7,
	"vince staples": 7,
	"last year was weird, vol. 3": 7,
	"mood valiant": 7,
	"home video": 7,
	"black metal 2": 7,
	"a tiny house, in secret speeches, polar equals": 7,
	"jubilee": 7,
	"pray for haiti": 7,
	"sour": 7,
	"sketchy.": 7,
	"black to the future": 7,
	"the off-season": 7,
	"seek shelter": 7,
	"bright green field": 7,
	"fortitude": 7,
	"violence unimagined": 7,
	"la maquina": 7,
	"entertainment, death": 7,
	"g_d's pee at state's end!": 7,
	"oh no": 7,
	"the plugs i met 2": 7,
	"chemtrails over the country club": 7,
	"breaking up.": 7,
	"el madrileño": 7,
	"yol": 7,
	"l.w.": 7,
	"if it bleeds it can be killed": 7,
	"i've seen all i need to see": 7,
	"sound ancestors": 7,
	"song of sage: post panic!": 7,
	"evermore": 7,
	"man on the moon iii: the chosen": 7,
	"doped runner verse": 7,
	"nightmare vacation": 7,
	"pink, black, and orange in the corners.": 7,
	"sin miedo (del amor y otros demonios) ∞": 7,
	"lamentations": 7,
	"spirit world field guide": 7,
	"pixel bath": 7,
	"burden of proof": 7,
	"streams of thought, vol. 3: cane and abel": 7,
	"van": 7,
	"all thoughts fly": 7,
	"savage mode ii": 7,
	"shore": 7,
	"notre-dame-des-sept-douleurs": 7,
	"detroit 2": 7,
	"spirit possession": 7,
	"king's disease": 7,
	"immersion": 7,
	"microphones in 2020": 7,
	"limbo": 7,
	"quarantine casanova": 7,
	"folklore": 7,
	"no pressure": 7,
	"ugly is beautiful": 7,
	"legends never die": 7,
	"kick i": 7,
	"planet's mad": 7,
	"the goat": 7,
	"shrines": 7,
	"mestarin kynsi": 7,
	"chromatica": 7,
	"dedicated side b": 7,
	"græ": 7,
	"descendants of cain": 7,
	"fetch the bolt cutters": 7,
	"heaven to a tortured mind": 7,
	"future nostalgia": 7,
	"after hours": 7,
	"everything sucks": 7,
	"none": 7,
	"yhlqmdlg": 7,
	"suddenly": 7,
	"be up a hello": 7,
	"high road": 7,
	"cracker island": 6,
	"raven": 6,
	"*ghettoland": 6,
	"butcher house": 6,
	"herbert": 6,
	"back 2 life": 6,
	"actual life 3 (january 1": 6,
	"this is what i mean": 6,
	"her loss": 6,
	"the loneliest time": 6,
	"return of the dream canteen": 6,
	"entergalactic": 6,
	"arrangements": 6,
	"the mars volta": 6,
	"bleed out": 6,
	"the elephant man's bones": 6,
	"cry sugar": 6,
	"freakout / release": 6,
	"reset": 6,
	"traumazine": 6,
	"red & white 🔴 ⚪": 6,
	"world wide pop": 6,
	"special": 6,
	"home, before and after": 6,
	"preacher's daughter": 6,
	"labyrinthitis": 6,
	"you can't kill me": 6,
	"un verano sin ti": 6,
	"palaces": 6,
	"harry's house": 6,
	"we've been going about this all wrong": 6,
	"zeit": 6,
	"omnium gatherum": 6,
	"famously alive": 6,
	"ramona park broke my heart": 6,
	"wet leg": 6,
	"the unraveling of puptheband": 6,
	"oxy music": 6,
	"this world is going to ruin you": 6,
	"the dream": 6,
	"few good things": 6,
	"laurel hell": 6,
	"the gods we can touch": 6,
	"from a birds eye view": 6,
	"sick!": 6,
	"kick iiii": 6,
	"crawler": 6,
	"twopointfive": 6,
	"hushed and grim": 6,
	"sympathy for life": 6,
	"deep states": 6,
	"oxidized": 6,
	"hitler wears hermes 8: sincerely adolf": 6,
	"flux": 6,
	"screen violence": 6,
	"the melodic blue": 6,
	"if i can't have love, i want power": 6,
	"van gogh's left ear": 6,
	"take the sadness out of saturday night": 6,
	"we're all alone in this together": 6,
	"ancient dreams in a modern land": 6,
	"hall of fame": 6,
	"the fool": 6,
	"the voice of the heroes": 6,
	"un canto por méxico, vol. ii": 6,
	"super what?": 6,
	"a diabolic thirst": 6,
	"lei line eon": 6,
	"is 4 lovers": 6,
	"harlecore": 6,
	"as the love continues": 6,
	"we are always alone": 6,
	"demidevil": 6,
	"bob's son: r.a.p. ferreira in the garden level cafe of the scallops hotel": 6,
	"charmed": 6,
	"drunk tank pink": 6,
	"plastic hearts": 6,
	"k.g.": 6,
	"good news": 6,
	"crack a light": 6,
	"disco": 6,
	"magic oneohtrix point never": 6,
	"extinction level event 2: the wrath of god": 6,
	"anime, trauma and divorce": 6,
	"lament": 6,
	"the album": 5,
	"the ascension": 6,
	"nectar": 6,
	"protean threat": 6,
	"re-animator": 6,
	"inner song": 6,
	"energy": 6,
	"down in the weeds where the world once was": 6,
	"7g": 6,
	"top shotta": 6,
	"ultimate success today": 6,
	"333": 6,
	"telas": 6,
	"shoot for the stars, aim for the moon": 6,
	"años en infierno": 6,
	"endless wound": 6,
	"pray for paris": 6,
	"it is what it is": 6,
	"kiss my super bowl ring": 6,
	"everything is beautiful": 6,
	"i let it in and it took everything": 6,
	"the allegory": 6,
	"we're new again": 6,
	"the slow rush": 6,
	"likewise": 6,
	"love sick": 5,
	"bless this mess": 5,
	"college park": 5,
	"girl in the half pearl": 5,
	"this stupid world": 5,
	"things don't always go the way you plan": 5,
	"gloria": 5,
	"mansion musik": 5,
	"like..?": 5,
	"hypochondriac": 5,
	"most normal": 5,
	"trouble the water": 5,
	"remember that you will die": 5,
	"midnights": 5,
	"mata": 5,
	"church": 5,
	"cool it down": 5,
	"fossora": 5,
	"hold the girl": 5,
	"wasteland": 5,
	"entering heaven alive": 5,
	"peace \"fly\" god": 5,
	"sznz: summer": 5,
	"no fear of time": 5,
	"i never liked you": 5,
	"stardust": 5,
	"crash": 5,
	"sznz: spring": 5,
	"impera": 5,
	"valentine": 5,
	"voyage": 5,
	"i don't live here anymore": 5,
	"blue banisters": 5,
	"trip at knight": 5,
	"if this isn't nice, i don't know what is": 5,
	"the house is burning": 5,
	"usee4yourself": 5,
	"all over the place": 5,
	"planet her": 5,
	"the life of pi'erre 5": 5,
	"butterfly 3000": 5,
	"avow": 5,
	"exodus": 5,
	"van weezer": 5,
	"slime language 2": 5,
	"deacon": 5,
	"from me to you": 5,
	"clouds (the mixtape)": 5,
	"who am i?": 5,
	"ignorance": 5,
	"flowers for vases / descansos": 5,
	"medicine at midnight": 5,
	"isles": 5,
	"whole lotta red": 5,
	"we will always love you": 5,
	"el último tour del mundo": 5,
	"positions": 5,
	"róisín machine": 5,
	"spilligion": 5,
	"apple": 5,
	"moonchild": 5,
	"zeros": 5,
	"ctv3: cool tape vol. 3": 5,
	"imploding the mirage": 5,
	"toxic boogaloo": 5,
	"love + light": 5,
	"rough and rowdy ways": 5,
	"inlet": 5,
	"notes on a conditional form": 5,
	"starz": 5,
	"petals for armor": 5,
	"shadow of life": 5,
	"making a door less open": 5,
	"omens": 5,
	"to feel alive": 5,
	"spirituality and distortion": 5,
	"exeter": 5,
	"heaven or hell": 5,
	"u-void synthesizer": 5,
	"a written testimony": 5,
	"eternal atake (deluxe)": 5,
	"suga": 5,
	"heavy light": 5,
	"map of the soul : 7": 5,
	"mark kozelek with ben boye and jim white 2": 5,
	"there is no year": 5,
	"modus vivendi": 5,
	"music to be murdered by": 3,
	"the family": 4,
	"smithereens": 4,
	"it's only me": 4,
	"the end, so far": 4,
	"sznz: autumn": 4,
	"lyfë": 4,
	"god did": 4,
	"get used to it": 4,
	"we": 4,
	"chloë and the next 20th century": 4,
	"unlimited love": 4,
	"love sux": 4,
	"zeal & ardor": 4,
	"digital roses don't die": 4,
	"2 alivë": 4,
	"w": 4,
	"fighting demons": 4,
	"sincerely, kentrell": 4,
	"life of a don": 4,
	"colors ii": 4,
	"solar power": 4,
	"long term effects of suffering": 4,
	"faith": 4,
	"escapades": 4,
	"blue weekend": 4,
	"khaled khaled": 4,
	"michigan boy boat": 4,
	"spare ribs": 4,
	"little oblivions": 4,
	"neon shark vs. pegasus (deluxe: presented by travis barker)": 4,
	"thats what they all say": 4,
	"pluto x baby pluto": 4,
	"act ii: patents of nobility (the turn)": 4,
	"mouth dreams": 4,
	"smile": 4,
	"a hero's death": 4,
	"what could possibly go wrong": 4,
	"weight of the world": 4,
	"dissimulation": 4,
	"afterburner": 4,
	"blame it on baby": 4,
	"sixteen oceans": 4,
	"saint cloud": 4,
	"3.15.20": 4,
	"eternal atake": 4,
	"miss anthropocene": 4,
	"no future": 4,
	"funeral": 4,
	"don't get too close": 3,
	"five easy hot dogs": 3,
	"tm": 3,
	"the car": 3,
	"the sick, the dying… and the dead!": 3,
	"las ruinas": 3,
	"twelve carat toothache": 3,
	"come home the kids miss you": 3,
	"cowboy tears": 3,
	"ethereal": 3,
	"live life fast": 3,
	"punk": 3,
	"certified lover boy": 3,
	"infinite granite": 3,
	"bobby tarantino iii": 3,
	"if i could make it go quiet": 3,
	"justice": 3,
	"life rolls on": 3,
	"new beginnings": 3,
	"ohms": 3,
	"virgo world": 3,
	"tattletales": 3,
	"im wald": 3,
	"mordechai": 3,
	"lil boat 3": 3,
	"high off life": 3,
	"dark lane demo tapes": 3,
	"aporia": 3,
	"rush!": 2,
	"=": 2,
	"music of the spheres": 2,
	"dog boy": 2,
	"star-crossed": 2,
	"the golden casket": 2,
	"culture iii": 2,
	"scaled and icy": 2,
	"the battle at garden's gate": 2,
	"flawless like me": 1,
	"no stylist": 1,
	"mainstream sellout": 1,
	"pegasus": 1,
	"southside": 1,
	"x": 0,
	"welcome to the madhouse": 0,
	"father of all...": 0,
}