titles_only = {
	"discovery": 10,
	"toxicity": 10,
	"vespertine": 10,
	"lift your skinny fists like antennas to heaven": 10,
	"madvillainy": 10,
	"the miseducation of lauryn hill": 10,
	"nevermind": 10,
	"in the aeroplane over the sea": 10,
	"enter the wu-tang (36 chambers)": 10,
	"violator": 10,
	"master of puppets": 10,
	"it takes a nation of millions to hold us back": 10,
	"hounds of love": 10,
	"remain in light": 10,
	"purple rain": 10,
	"bitches brew": 10,
	"london calling": 10,
	"what's going on": 10,
	"physical graffiti": 10,
	"marquee moon": 10,
	"hot rats": 10,
	"highway 61 revisited": 10,
	"the black saint and the sinner lady": 10,
	"abbey road": 10,
	"nina simone sings the blues": 10,
	"you won't get what you want": 10,
	"kids see ghosts": 10,
	"to pimp a butterfly": 10,
	"to be kind": 10,
	"the money store": 10,
	"h.a.q.q.": 9,
	"coin coin chapter four: memphis": 9,
	"2020": 9,
	"charli": 9,
	"caligula": 9,
	"igor": 9,
	"itekoma hits": 9,
	"titanic rising": 9,
	"grey area": 9,
	"girl with basket of fruit": 9,
	"idol": 9,
	"joy as an act of resistance": 9,
	"year of the snitch": 9,
	"wide awake!": 9,
	"2012": 9,
	"boarding house reach": 9,
	"ion": 9,
	"rina": 9,
	"4eva is a mighty long time": 9,
	"saturation": 9,
	"a crow looked at me": 9,
	"mouth moods": 9,
	"pure comedy": 9,
	"we got it from here... thank you 4 your service": 9,
	"atrocity exhibition": 9,
	"common as light and love are red valleys of blood": 9,
	"bottomless pit": 9,
	"the glowing man": 9,
	"plays the music of twin peaks": 9,
	"★ [blackstar]": 9,
	"blackstar": 9,
	"m3ll155x": 9,
	"have you in my wilderness": 9,
	"meliora": 9,
	"the epic": 9,
	"towards the megalith": 9,
	"the powers that b": 9,
	"citizen zombie": 9,
	"throat": 9,
	"pom pom": 9,
	"plowing into the field of love": 9,
	"unsilent death": 9,
	"clppng": 9,
	"piñata": 9,
	"teethed glory and injury": 9,
	"the satanist": 9,
	"benji": 9,
	"fetch": 9,
	"virgins": 9,
	"...like clockwork": 9,
	"bbng2": 9,
	"ondatrópica": 9,
	"shaking the habitual": 9,
	"tnght": 9,
	"good kid, m.a.a.d city": 9,
	"natural history": 9,
	"the idler wheel": 9,
	"put your back n 2 it": 9,
	"return of 4eva": 9,
	"gloss drop": 9,
	"helplessness blues": 9,
	"kaputt": 9,
	"public strain": 9,
	"the way out": 9,
	"business casual": 9,
	"this is happening": 9,
	"a sufi and a killer": 9,
	"plastic beach": 9,
	"hot sauce committee pt. 2": 9,
	"new chain": 8,
	"abhorrent evolution": 8,
	"heavy is the head": 8,
	"polyhymnia": 8,
	"little electric chicken heart": 8,
	"[usa]": 8,
	"there existed an addiction to blood": 8,
	"all my heroes are cornballs": 8,
	"sonic citadel": 8,
	"pang": 8,
	"the fall of hobo johnson": 8,
	"the highwomen": 8,
	"ginger": 8,
	"infest the rats' nest": 8,
	"sizzling": 8,
	"miami memory": 8,
	"braindrops": 8,
	"flamboyant": 8,
	"purple mountains": 8,
	"zuu": 8,
	"return to center": 8,
	"schlagenheim": 8,
	"uknowhatimsayin¿": 8,
	"a quiet farwell, 2016-2018": 8,
	"the origin of my depression": 8,
	"pyroclasts": 8,
	"hiding places": 8,
	"nothing great about britain": 8,
	"hi this is flume": 8,
	"trust in the lifeforce of the deep mystery": 8,
	"a long red hot los angeles summer night": 8,
	"bandana": 8,
	"guns": 8,
	"when we all fall asleep, where do we go?": 8,
	"cuz i love you": 8,
	"modern flows, vol. 2": 8,
	"morbid stuff": 8,
	"thank u, next": 8,
	"plastic anniversary": 8,
	"malibu ken": 8,
	"some rap songs": 8,
	"dicaprio 2": 8,
	"the light is leaving us all": 8,
	"new levels new devils": 8,
	"oxnard": 8,
	"norman fucking rockwell!": 8,
	"time 'n' place": 8,
	"el mal querer": 8,
	"aviary": 8,
	"paraffin": 8,
	"room 25": 8,
	"orpheus vs. the sirens": 8,
	"collapse ep": 8,
	"transmission zero": 8,
	"negro swan": 8,
	"twisted crystal": 8,
	"time": 8,
	"ta13oo": 8,
	"trench": 8,
	"hate music last time delete": 8,
	"vile luxury": 8,
	"clear tamei": 8,
	"oil of every pearl's un-insides": 8,
	"streams of thought, vol. 1": 8,
	"ye": 8,
	"daytona": 8,
	"stranger fruit": 8,
	"the sciences": 8,
	"prequelle": 8,
	"春と修羅 (harutosyura)": 8,
	"your queen is a reptile": 8,
	"isolation": 8,
	"dirty computer": 8,
	"a laughing death in meatspace": 8,
	"everything's fine": 8,
	"virtue": 8,
	"veteran": 8,
	"bark your head off, dog": 8,
	"musas vol. 2": 8,
	"twin fantasy (face to face)": 8,
	"firepower": 8,
	"dead magic": 8,
	"you're not alone": 8,
	"in a poem unlimited": 8,
	"saturation iii": 8,
	"all at once": 8,
	"soul of a woman": 8,
	"young martha": 8,
	"laila's wisdom": 8,
	"1992 deluxe": 8,
	"the dusk in us": 8,
	"outrage! is now": 8,
	"neō wax bloom": 8,
	"caustic": 8,
	"poor lily": 8,
	"urgency": 8,
	"saturation ii": 8,
	"take me apart": 8,
	"brick body kids still daydream": 8,
	"written at night": 8,
	"forced witness": 8,
	"relatives in descent": 8,
	"flower boy": 8,
	"wrong one to fuck with": 8,
	"dedicated to bobby jameson": 8,
	"4:44": 8,
	"orc": 8,
	"antisocialites": 8,
	"bravado": 8,
	"peasant": 8,
	"gt ultra": 8,
	"first opus": 8,
	"known unknowns": 8,
	"little dark age": 8,
	"the underside of power": 8,
	"los ángeles": 8,
	"reflections of a floating world": 8,
	"compassion": 8,
	"no shape": 8,
	"pleasure": 8,
	"cubafonía": 8,
	"crack-up": 8,
	"all-amerikkkan bada$$": 8,
	"thin black duke": 8,
	"goths": 8,
	"being you is great, i wish i could be you more often": 8,
	"brutalism": 8,
	"heartless": 8,
	"not the actual events": 8,
	"uyai": 8,
	"run the jewels 3": 8,
	"floss": 8,
	"the long dark blue": 8,
	"forget": 8,
	"flying microtonal banana": 8,
	"process": 8,
	"forever": 6,
	"beyond the fleeting gales": 8,
	"a seat at the table": 8,
	"worry.": 8,
	"abzu": 8,
	"e•mo•tion: side b": 8,
	"bonito generation": 8,
	"honor killed the samurai": 8,
	"godfather": 8,
	"end position": 8,
	"ruminations": 8,
	"blonde": 8,
	"telefone": 8,
	"splendor & misery": 8,
	"remember us to life": 8,
	"scum with boundaries": 8,
	"body war": 8,
	"fires within fires": 8,
	"stage four": 8,
	"preoccupations": 8,
	"my woman": 8,
	"skeleton tree": 8,
	"still brazy": 8,
	"a weird exits": 8,
	"black terry cat": 8,
	"a moon shaped pool": 8,
	"lemonade": 8,
	"you will never be one of us": 8,
	"teens of denial": 8,
	"spirit phone": 8,
	"nonagon infinity": 8,
	"imperial": 8,
	"a sailor's guide to earth": 8,
	"vroom vroom ep": 8,
	"pleiades' dust": 8,
	"murmur": 8,
	"strangers": 8,
	"the impossible kid": 8,
	"feelin kinda free": 8,
	"ritual spirit": 8,
	"weezer (white album)": 8,
	"before a million universes": 8,
	"the life of pablo": 8,
	"jumalten aika": 8,
	"possession": 8,
	"paradise": 8,
	"terminal redux": 8,
	"emotional mugger": 8,
	"ultimate care ii": 8,
	"the documentary 2.5": 8,
	"chinese nü year": 8,
	"so the flies don't come": 8,
	"lovers holiday": 8,
	"purple": 8,
	"prayer for terrene": 8,
	"scratch 'n sniff": 8,
	"6ix commandments": 8,
	"howl": 8,
	"r.e.k.s. (rhythmatic eternal king supreme)": 8,
	"outer isolation": 8,
	"time is up": 8,
	"dirge": 8,
	"λόγος": 8,
	"shit computer": 8,
	"rodeo": 8,
	"evermore: the art of duality": 8,
	"garden of delete": 8,
	"the anthropocene extinction": 8,
	"divers": 8,
	"autumn eternal": 8,
	"live from the dentist office": 8,
	"sun coming down": 8,
	"key markets": 8,
	"guud": 8,
	"every hero needs a villain": 8,
	"opus eponymous": 8,
	"third side of tape": 8,
	"poison season": 8,
	"giles corey": 8,
	"luminiferous": 8,
	"abyss": 8,
	"blood": 8,
	"escape velocity": 8,
	"the eulogy": 8,
	"success": 8,
	"frozen niagara falls": 8,
	"algiers": 8,
	"painted shut": 8,
	"get to heaven": 8,
	"comadre": 8,
	"never were the way she was": 8,
	"if you're reading this it's too late": 8,
	"we cool?": 8,
	"sound & color": 8,
	"multi-love": 8,
	"kinison": 8,
	"white men are black men too": 8,
	"drought": 8,
	"xe": 8,
	"scar sighted": 8,
	"a special episode of": 8,
	"beat the champ": 8,
	"vulnicura": 8,
	"no now": 8,
	"labyrinth constellation": 8,
	"mouth silence": 8,
	"mouth sounds": 8,
	"apex predator": 8,
	"b4.da.$$": 8,
	"homo": 8,
	"i wish my brother rob was here": 8,
	"black messiah": 8,
	"daughters": 8,
	"full of hell & merzbow": 8,
	"i love you, honeybear": 8,
	"black metal": 8,
	"rhythm": 8,
	"lifer": 8,
	"new york telephone": 8,
	"vi: flora": 8,
	"the water[s]": 8,
	"run the jewels 2": 8,
	"sometimes the blues is just a passing bird": 8,
	"perfect hair": 8,
	"race music": 8,
	"roads to the north": 8,
	"you're dead!": 8,
	"annabel dream reader": 8,
	"too bright": 8,
	"connecticut casual": 8,
	"holkham drones": 8,
	"dark comedy": 8,
	"lp1": 8,
	"conjure and command": 8,
	"celestite": 8,
	"trouble in paradise": 8,
	"satan worshipping doom": 8,
	"marrow of the spirit": 8,
	"sacred white noise": 8,
	"dwellings": 8,
	"ultima ii massage": 8,
	"so it goes": 8,
	"broken ankles ep": 8,
	"baby": 8,
	"totem": 8,
	"boy": 8,
	"nikki nack": 8,
	"なんだこれくしょん (nanda collection)": 8,
	"rising sun": 8,
	"the unnatural world": 8,
	"from all purity": 8,
	"lord steppington": 8,
	"eighteen hours of static": 8,
	"mess": 8,
	"fuck off get free we pour light on everything": 8,
	"hot dreams": 8,
	"blood donation": 8,
	"unlearn": 8,
	"nina": 8,
	"ghettoville": 8,
	"no poison no paradise": 8,
	"peep: the aprocalypse": 8,
	"drone logic": 8,
	"how to stop your brain in an accident": 8,
	"melophobia": 8,
	"is survived by": 8,
	"gnk": 8,
	"betteroffdead": 8,
	"psychic": 8,
	"colored sands": 8,
	"the night's gambit": 8,
	"lousy with sylvianbriar": 8,
	"apokalypsis": 8,
	"run the jewels": 8,
	"dream river": 8,
	"tape two": 8,
	"rohnert park": 8,
	"pain is beauty": 8,
	"immunity": 5,
	"midcity": 8,
	"loud city song": 8,
	"sunbather": 8,
	"i see seaweed": 8,
	"one of us is the killer": 8,
	"silence yourself": 8,
	"bbng": 8,
	"kvelertak": 8,
	"meir": 8,
	"twelve reasons to die": 8,
	"random access memories": 8,
	"excavation": 8,
	"knife man": 8,
	"soft will": 8,
	"laid out": 8,
	"wakin on a pretty daze": 8,
	"exai": 8,
	"tape one": 8,
	"m b v": 8,
	"elephants at the door": 8,
	"wildlife": 8,
	"results": 8,
	"made possible": 8,
	"alone together": 8,
	"on acid": 8,
	"hasta la muerte": 8,
	"dripping": 8,
	"i.v.": 8,
	"history will absolve me": 8,
	"sinews": 8,
	"portico quartet": 8,
	"you're nothing": 8,
	"sentenced to life": 8,
	"clash the truth": 8,
	"truant / rough sleeper": 8,
	"rare chandeliers": 8,
	"general dome": 8,
	"we are the 21st century ambassadors of peace & magic": 8,
	"allelujah! don't bend! ascend!": 8,
	"the odds": 8,
	"breakthrough": 8,
	"all we love we leave behind": 8,
	"years past matter": 8,
	"no love deep web": 8,
	"the seer": 8,
	"silencing machine": 8,
	"lonerism": 8,
	"holograms": 8,
	"kin": 8,
	"nocturne": 8,
	"control system": 8,
	"an awesome wave": 8,
	"beams": 8,
	"take the kids off broadway": 8,
	"galaxy garden": 8,
	"harmonicraft": 8,
	"hair": 8,
	"slaughterhouse": 8,
	"r.a.p. music": 8,
	"de vermis mysteriis": 8,
	"zammuto": 8,
	"there's no leaving now": 8,
	"awe naturale": 8,
	"narrow": 8,
	"4eva n a day": 8,
	"bloom": 8,
	"kindred": 8,
	"ƒin": 8,
	"nehru jackets": 8,
	"silent hour / golden mile": 8,
	"echoes of silence": 8,
	"coin coin chapter one: gens de couleur libre": 8,
	"elmatic": 8,
	"sweet heart sweet light": 8,
	"93 million miles": 8,
	"idle labor": 8,
	"live. love. a$ap": 8,
	"exmilitary": 8,
	"oneirology": 8,
	"attack on memory": 8,
	"new history warfare vol. 2: judges": 8,
	"replica": 8,
	"veronica falls": 8,
	"xxx": 8,
	"the golden age of apocalypse": 8,
	"section.80": 8,
	"ritual union": 8,
	"sbtrkt": 8,
	"new brigade": 8,
	"strange mercy": 8,
	"aesthethica": 8,
	"creep on creepin' on": 8,
	"in love with oblivion": 8,
	"black up": 8,
	"holy ghost!": 8,
	"space is only noise": 8,
	"belong": 8,
	"ravedeath, 1972": 8,
	"hardcore will never die, but you will": 8,
	"apollo kids": 8,
	"all eternals deck": 8,
	"special affections": 8,
	"sit down, man": 8,
	"let england shake": 8,
	"valhalla dancehall": 8,
	"all day": 8,
	"sports": 8,
	"small craft on a milk sea": 8,
	"ring": 8,
	"memphis": 8,
	"all delighted people": 8,
	"pattern+grid world": 8,
	"penny sparkle": 8,
	"halcyon digest": 8,
	"cerulean": 8,
	"mount wittenberg orca": 8,
	"how i got over": 8,
	"homeland": 8,
	"the drums": 8,
	"the suburbs": 8,
	"the archandroid": 8,
	"at echo lake": 8,
	"lp4": 8,
	"king of the beach": 8,
	"cosmogramma": 8,
	"before today": 8,
	"snakes for the divine": 8,
	"clinging to a scheme": 8,
	"congratulations": 8,
	"the wild hunt": 8,
	"i am your destruction": 7,
	"past 21 beyond the arctic cell": 7,
	"sterilizer": 7,
	"the beast of left and right": 7,
	"cocody": 7,
	"amongst these splintered minds // leaden thoughts sing softly": 7,
	"idiom wind": 7,
	"please excuse me for being antisocial": 7,
	"e": 7,
	"wwcd": 7,
	"roomful of teeth": 7,
	"grime mc": 7,
	"city morgue vol. 2: as good as dead": 7,
	"generasian": 7,
	"ii": 7,
	"one of the best yet": 7,
	"ghosteen": 7,
	"xyz": 7,
	"kiwanuka": 7,
	"two hands": 7,
	"so much fun": 7,
	"do you feel me?": 7,
	"the lost boy": 7,
	"eve": 7,
	"the first glass beach album": 7,
	"leaving meaning.": 7,
	"jaime": 7,
	"negative space": 7,
	"anima": 7,
	"animated violence mild": 7,
	"1000 gecs": 7,
	"choke": 7,
	"fever": 7,
	"shepherd in a sheepskin vest": 7,
	"come in": 7,
	"magdalene": 7,
	"it wasn't even close": 7,
	"injury reserve": 7,
	"dedicated": 7,
	"fishing for fishies": 7,
	"ventura": 7,
	"dos city": 7,
	"dog whistle": 7,
	"life metal": 7,
	"i also want to die in new orleans": 7,
	"beware of the dogs": 7,
	"future hndrxx presents: the wizrd": 7,
	"doko mien": 7,
	"anx": 7,
	"assume form": 7,
	"american football": 5,
	"i am > i was": 7,
	"streams of thought, vol. 2": 7,
	"kai whiston bitch": 7,
	"sonic ranch": 7,
	"works by tul kupferberg (1923-2010)": 7,
	"mazy fly": 7,
	"a love letter to you 3": 7,
	"fm!": 7,
	"what happens when i try to relax": 7,
	"remind me tomorrow": 7,
	"fetti": 7,
	"velvet": 7,
	"think : peace": 7,
	"drogas wave": 7,
	"am i a girl?": 7,
	"cantos": 7,
	"safe in the hands of love": 7,
	"iridescence": 7,
	"slide": 7,
	"i loved you at your darkest": 7,
	"steel mogu": 7,
	"for my crimes": 7,
	"lower east suite part three": 7,
	"and nothing hurt": 7,
	"rules": 7,
	"whack world": 7,
	"zephyr": 7,
	"hive mind": 7,
	"die lit": 7,
	"bad witch": 7,
	"high as hope": 7,
	"astroworld": 7,
	"sweetener": 7,
	"beware the book of eli": 7,
	"lump": 7,
	"four pieces for mirai": 7,
	"sr3mm": 7,
	"god's favorite customer": 7,
	"the tree of forgiveness": 7,
	"i'm all ears": 7,
	"soil": 7,
	"7": 6,
	"beyondless": 7,
	"singularity": 7,
	"lil boat 2": 7,
	"czarface meets metal face": 7,
	"mark kozelek": 7,
	"now only": 7,
	"american dollar bill": 7,
	"american utopia": 7,
	"ephorize": 7,
	"superorganism": 7,
	"gumboot soup": 7,
	"highly rare": 7,
	"pop 2": 7,
	"freedom's goblin": 7,
	"from a room: volume 2": 7,
	"beerbongs & bentleys": 7,
	"down below": 7,
	"polygondwanaland": 7,
	"no one ever really dies": 7,
	"without warning": 7,
	"ruins": 7,
	"humaniac": 7,
	"snares like a haircut": 7,
	"lil pump": 7,
	"primal heart": 7,
	"utopia": 7,
	"drive it like it's stolen": 7,
	"ash": 7,
	"bicep": 7,
	"mourn": 7,
	"freudian": 7,
	"alice glass": 7,
	"science fiction": 7,
	"turn out the lights": 7,
	"big machines and peculiar beings": 7,
	"watcher": 7,
	"ghost at the finish line": 7,
	"forceps": 7,
	"no youth": 7,
	"eschatological scatology": 7,
	"balkans": 7,
	"after school special": 7,
	"all pigs must die": 7,
	"dark country magic": 7,
	"four more years": 7,
	"desert fires": 7,
	"pharma": 7,
	"snake oil": 7,
	"boy who cried wolf": 7,
	"howling, for the nightmare shall consume": 7,
	"who told you to think??!!?!?!?!": 7,
	"rainbow": 7,
	"savage sinusoid": 7,
	"hiss spun": 7,
	"sleep well beast": 7,
	"hug of thunder": 7,
	"dead cross": 7,
	"after laughter": 7,
	"damn.": 7,
	"bon voyage": 7,
	"satan's graffiti or god's art?": 7,
	"greatest hits": 7,
	"number 1 angel": 7,
	"is this the life we really want?": 7,
	"melodrama": 7,
	"all this i do for glory": 7,
	"har nevo": 7,
	"baile bucanero": 7,
	"rap album two": 7,
	"this old dog": 7,
	"ctrl": 7,
	"duster's lament": 7,
	"dirty projectors": 7,
	"packs": 7,
	"a shadow in time": 7,
	"world eater": 7,
	"hot thoughts": 7,
	"culture": 7,
	"conformicide": 7,
	"metahuman": 7,
	"endless night": 7,
	"50 song memoir": 7,
	"do what thou wilt.": 7,
	"memories are now": 7,
	"why love now": 7,
	"nightmare logic": 7,
	"hang": 7,
	"24k magic": 7,
	"big baby d.r.a.m.": 7,
	"yes lawd!": 7,
	"4nml hsptl": 7,
	"voices": 7,
	"blue suicide": 7,
	"dungeon bastards": 7,
	"negus": 7,
	"jessica rabbit": 7,
	"telling it like it is": 7,
	"prima donna": 7,
	"jeffery": 7,
	"denton after sunset": 7,
	"dissociation": 7,
	"wriggle": 7,
	"iiidrops": 7,
	"wildflower": 7,
	"32 levels": 7,
	"iv": 7,
	"handshakes with snakes": 7,
	"coloring book": 7,
	"the magic": 7,
	"konnichiwa": 7,
	"sleep cycle": 7,
	"tempo": 7,
	"the terrible tale of scurvy jones": 7,
	"lil boat": 7,
	"case/lang/veirs": 7,
	"holy ghost": 7,
	"hella personal film festival": 7,
	"useless": 7,
	"made in the manor": 7,
	"human performance": 7,
	"parasite brain": 7,
	"one day you will ache like i ache": 7,
	"post pop depression": 7,
	"the hope six demolition project": 7,
	"city sun eater in the river of light": 7,
	"malibu": 7,
	"hyperion": 7,
	"sugarbread": 7,
	"värähtelijä": 7,
	"lil me": 7,
	"los suicidas": 7,
	"flockaveli 1.5": 7,
	"king push": 7,
	"tempest": 7,
	"99¢": 7,
	"nevermen": 7,
	"shadow of a doubt": 7,
	"give me my flowers while i can still smell them": 7,
	"25": 7,
	"moth": 7,
	"art angels": 7,
	"stretch music": 7,
	"halfway": 7,
	"corpo-mente": 7,
	"wakedafucup": 7,
	"teens of style": 7,
	"jason... the dragon": 7,
	"death gate": 7,
	"suicide euphoria": 7,
	"paper mâché dream balloon": 7,
	"harmlessness": 7,
	"vega intl. night school": 7,
	"go:od am": 7,
	"the things we do to find people who feel like us": 7,
	"compton: a soundtrack by dr. dre": 7,
	"pyramid of the sun": 7,
	"parting the sea between brightness and me": 7,
	"exhausting fire": 7,
	"self portrait": 7,
	"the agent intellect": 7,
	"innocent country": 7,
	"heavy dancing": 7,
	"fingers, bank pads, and shoe prints": 7,
	"invite the light": 7,
	"e•mo•tion": 7,
	"kunk": 7,
	"la chaise-dyable": 7,
	"twelve reasons to die ii": 7,
	"magnifique": 7,
	"howl of the lonely crowd": 7,
	"live music": 7,
	"currents": 7,
	"illumination": 7,
	"born in the echoes": 7,
	"another one": 7,
	"the children of the night": 7,
	"today, i wrote nothing": 7,
	"in colour": 7,
	"the magic whip": 7,
	"how big how blue how beautiful": 7,
	"if": 7,
	"honkey kong": 7,
	"the ark work": 7,
	"what for?": 7,
	"fantasy empire": 7,
	"supersonic home": 7,
	"at least for now": 7,
	"carrie & lowell": 7,
	"og maco": 7,
	"fashion week": 7,
	"tetsuo & youth": 7,
	"earthee": 7,
	"crusher": 7,
	"short movie": 7,
	"black and brown!": 7,
	"the thought of you": 7,
	"splinters": 7,
	"ferg forever": 7,
	"lost themes": 7,
	"viet cong": 7,
	"the church": 7,
	"no cities to love": 7,
	"clockwork indigo": 7,
	"hell can wait": 7,
	"faith in strangers": 7,
	"a world lit only by fire": 7,
	"la isla bonita": 7,
	"cellar door: terminus ut exordium": 7,
	"dreams worth more than money": 7,
	"strange journey volume three": 7,
	"banco": 7,
	"everything will be alright in the end": 7,
	"mandatory fun": 7,
	"ピカピカふぁんたじん [pika pika fantajin]": 7,
	"antemasque": 7,
	"tyranny": 7,
	"this is all yours": 7,
	"they want my soul": 7,
	"this is my hand": 7,
	"esoteric warfare": 7,
	"1000 forms of fear": 7,
	"crashing diseases and incurable airplanes": 7,
	"once more 'round the sun": 7,
	"more than any other day": 7,
	"ptsd": 7,
	"summit": 7,
	"iii": 7,
	"try not to destroy everything you love": 7,
	"sea when absent": 7,
	"dissed and dismissed": 7,
	"ibibio sound machine": 7,
	"rooms of the house": 7,
	"carbon-based anatomy": 7,
	"sisyphus": 7,
	"strange moosic": 7,
	"welcome to fazoland": 7,
	"in conflict": 7,
	"blood for the master": 7,
	"wasted years": 7,
	"waterfall": 7,
	"singles": 7,
	"present tense": 7,
	"angel guts: red classroom": 7,
	"oxymoron": 7,
	"hokey fright": 7,
	"st. vincent": 7,
	"lost in the dream": 7,
	"indigoism": 7,
	"vacation": 7,
	"bad vibes": 7,
	"nostalgic 64": 7,
	"portals to a better, dead world": 7,
	"spaces": 7,
	"flying colours": 7,
	"julia with blue jeans on": 7,
	"beautiful rewind": 7,
	"the destroyers of all": 7,
	"hubardo": 7,
	"vapor city": 7,
	"fever hunting": 7,
	"kismet": 7,
	"whenever, if ever": 7,
	"the marshall mathers lp 2": 7,
	"old": 7,
	"dour candy": 7,
	"trap lord": 7,
	"dynamics": 7,
	"6 feet beneath the moon": 7,
	"summer knights": 7,
	"the electric lady": 7,
	"ceres & calypso in the deep time": 7,
	"the inheritors": 7,
	"melt yourself down": 7,
	"silver wilkinson": 7,
	"king remembered in time": 7,
	"settle": 7,
	"abandon all life": 7,
	"innocence is kinky": 7,
	"nostalchic": 7,
	"hit the waves": 7,
	"once i was an eagle": 7,
	"entrench": 7,
	"body music": 7,
	"overgrown": 7,
	"modern vampires of the city": 7,
	"new history warfare vol. 3: to see more light": 7,
	"13.0.0.0.0": 7,
	"pressure & time": 7,
	"{awayland}": 7,
	"the next day": 7,
	"matangi": 7,
	"honeys": 7,
	"the man who died in his boat": 7,
	"living with the ancients": 7,
	"floral green": 7,
	"is your love big enough?": 7,
	"light up gold": 7,
	"amok": 7,
	"jessica pratt": 7,
	"movement": 7,
	"duality": 7,
	"unknown rooms: a collection of acoustic songs": 7,
	"fade": 7,
	"honor found in decay": 7,
	"the heist": 7,
	"luxury problems": 7,
	"order of noise": 7,
	"bish bosch": 7,
	"half way home": 7,
	"long.live.a$ap": 7,
	"until the quiet comes": 7,
	"transcendental youth": 7,
	"pink": 7,
	"1999": 7,
	"bend beyond": 7,
	"love this giant": 7,
	"i bet on sky": 7,
	"the haunted man": 7,
	"instrumental 2": 7,
	"channel orange": 7,
	"i know what love isn't": 7,
	"four": 7,
	"live from the underground": 7,
	"yellow & green": 7,
	"wixiw": 7,
	"skelethon": 7,
	"valtari": 7,
	"world, you need a change of mind": 7,
	"wreck": 7,
	"americana": 7,
	"in our heads": 7,
	"sorrow and extinction": 7,
	"off!": 7,
	"clear moon": 7,
	"the horror": 7,
	"noctourniquet": 7,
	"locked down": 7,
	"glimmer": 7,
	"the lion's roar": 7,
	"something": 7,
	"open your heart": 7,
	"totem three": 7,
	"isam": 7,
	"mosaik": 7,
	"paralytic stalks": 7,
	"darker handcraft": 7,
	"glass swords": 7,
	"tramp": 7,
	"king krule": 7,
	"scary monsters and nice sprites": 7,
	"50 words for snow": 7,
	"bad as me": 7,
	"looping state of mind": 7,
	"satin panthers": 7,
	"father, son, holy ghost": 7,
	"the whole love": 7,
	"wild flag": 7,
	"skying": 7,
	"the english riviera": 7,
	"angels of darkness, demons of light i": 7,
	"smother": 7,
	"codes and keys": 7,
	"w h o k i l l": 7,
	"angles": 7,
	"native speaker": 7,
	"in evening air": 7,
	"showroom of compassion": 7,
	"james blake": 7,
	"epic": 7,
	"dye it blonde": 7,
	"lucky shiner": 7,
	"the lady killer": 7,
	"grinderman 2": 7,
	"black city": 7,
	"hurley": 7,
	"wild smile": 7,
	"gemini": 3,
	"maniac meat": 7,
	"pigeons": 7,
	"latin": 7,
	"(ii)": 7,
	"hippies": 7,
	"brothers": 7,
	"together": 7,
	"the monitor": 7,
	"3rd ep": 6,
	"dweller on the threshold": 6,
	"come sunday": 6,
	"red horse": 6,
	"good faith": 6,
	"terror management": 6,
	"lost wisdom pt. 2": 6,
	"is he real?": 6,
	"all mirrors": 6,
	"memory": 6,
	"death atlas": 6,
	"i,i": 6,
	"angel's pulse": 6,
	"the sailor": 6,
	"face stabber": 6,
	"lover": 6,
	"clarity": 6,
	"the plugs i met": 6,
	"a different shade of blue": 6,
	"mirrorland": 6,
	"we are not your kind": 6,
	"planetary clairvoyance": 6,
	"anger management": 6,
	"arizona baby": 6,
	"welcome home": 6,
	"weeping choir": 6,
	"when i get home": 6,
	"death race for love": 6,
	"father of 4": 6,
	"rap or go to the league": 6,
	"father of the bride": 6,
	"weezer (teal album)": 6,
	"everything's for sale": 6,
	"everything not saved will be lost (part 1)": 6,
	"syntheosis": 6,
	"king's mouth": 6,
	"no geography": 6,
	"panorama": 6,
	"stokeley": 6,
	"reflections": 6,
	"buoys": 6,
	"not all heroes wear capes": 6,
	"quiet signs": 6,
	"outer peace": 6,
	"antipositive, pt. 2": 6,
	"city morgue vol. 1: hell or high water": 6,
	"mudboy": 6,
	"budding ornithologists are weary of tired analogies": 6,
	"nina cried power": 6,
	"amo": 6,
	"bottle it in": 6,
	"electric messiah": 6,
	"konoyo": 6,
	"i want to die in new orleans": 6,
	"this is my dinner": 6,
	"k.t.s.e.": 6,
	"errorzone": 6,
	"nasty": 6,
	"nasir": 6,
	"magus": 6,
	"the now now": 6,
	"smote reverser": 6,
	"be the cowboy": 6,
	"lamp lit prose": 6,
	"love yourself 轉 tear": 6,
	"heaven and earth": 6,
	"age of": 6,
	"invasion of privacy": 6,
	"lush": 6,
	"two parts together": 6,
	"tell me how you really feel": 6,
	"gangin": 6,
	"prhyme 2": 6,
	"communion": 6,
	"vacation in hell": 6,
	"cocoa sugar": 6,
	"amen": 6,
	"post-": 6,
	"huncho jack, jack huncho": 6,
	"material control": 6,
	"room inside the world": 6,
	"rome": 6,
	"rainbow mirror": 6,
	"deadstar": 6,
	"who built the moon?": 6,
	"stranger": 6,
	"masseduction": 6,
	"a brief inquiry into online relationships": 6,
	"poppy.computer": 6,
	"krak attack 2: ballad of elli skiff": 6,
	"chemistry of consciousness": 6,
	"higher learning vol. 2": 6,
	"v": 4,
	"paramatma": 6,
	"still striving": 6,
	"always foreign": 6,
	"add violence": 6,
	"the autobiography": 6,
	"you will regret": 6,
	"mareridt": 6,
	"thrice woven": 6,
	"concrete and gold": 6,
	"raskit": 6,
	"american dream": 6,
	"wonderful wonderful": 6,
	"villains": 6,
	"blue chips 7000": 6,
	"as you were": 6,
	"a fever dream": 6,
	"okovi": 6,
	"painted ruins": 6,
	"big fish theory": 6,
	"witness": 6,
	"murder of the universe": 6,
	"renaissance": 6,
	"more scared of you than you are of me": 6,
	"lust for life": 6,
	"trumpeting ecstasy": 6,
	"you only live 2wice": 6,
	"rather you than me": 6,
	"lung": 6,
	"the far field": 6,
	"volume 1: flick your tongue against your teeth and describe the present.": 6,
	"drunk": 6,
	"life will see you now": 6,
	"drogas light": 6,
	"i decided.": 6,
	"english tapas": 6,
	"4 your eyez only": 6,
	"ty segall": 6,
	"i see you": 6,
	"crossover ministry": 6,
	"a fistful of peril": 6,
	"sirens": 6,
	"joanne": 6,
	"the sun's tirade": 6,
	"hardwired...to self-destruct": 6,
	"treasure state": 6,
	"rain temple": 6,
	"paidprogramming2": 6,
	"schmilco": 6,
	"all your happy life": 6,
	"major key": 6,
	"everybody looking": 6,
	"spiritual state": 6,
	"how to be a human being": 6,
	"freetown sound": 6,
	"99.9%": 6,
	"sremmlife 2": 6,
	"the dream is over": 6,
	"hopelessness": 6,
	"nattesferd": 6,
	"metal resistance": 6,
	"bbf hosted by dj escrow": 6,
	"evol": 6,
	"aa": 6,
	"i aka i": 6,
	"this unruly mess i've made": 6,
	"3001: a laced odyssey": 6,
	"butter fly": 6,
	"but you caint use my phone": 6,
	"time & materials": 6,
	"behold.total.rejection": 6,
	"is the is are": 6,
	"the ghosts of highway 20": 6,
	"thumbs": 6,
	"tell me i'm pretty": 6,
	"adore life": 6,
	"mutant": 6,
	"hymns": 6,
	"aquλria": 6,
	"the incredible true story": 6,
	"kannon": 6,
	"what a time to be alive": 6,
	"the documentary 2": 6,
	"leave me alone": 6,
	"90059": 6,
	"fallen": 6,
	"oj simpson": 6,
	"slaves beyond death": 6,
	"the miraculous": 6,
	"back on top": 6,
	"beach music": 6,
	"fading frontier": 6,
	"holographic violence": 6,
	"jesu/sun kil moon": 6,
	"ygg huur": 6,
	"new bermuda": 6,
	"b'lieve i'm goin down": 6,
	"wave[s]": 6,
	"tripper": 6,
	"star wars": 6,
	"la di da di": 6,
	"when you're gone": 6,
	"ds2": 6,
	"anthems for doomed youth": 6,
	"god, money, war": 6,
	"music complete": 6,
	"the book of souls": 6,
	"the beyond / where the giants roam": 6,
	"ten stories": 6,
	"32 zel / planet shrooms": 6,
	"caracal": 6,
	"the expanding flower planet": 6,
	"m": 6,
	"depression cherry": 6,
	"days with dr. yen lo": 6,
	"free tc": 6,
	"the headless ritual": 6,
	"the spits": 6,
	"summertime '06": 6,
	"no": 6,
	"simple songs": 6,
	"i don't like shit, i don't go outside": 6,
	"platform": 6,
	"in the middle of infinity": 6,
	"mutilator defeated at last": 6,
	"asunder, sweet and other distress": 6,
	"hand. cannot. erase.": 6,
	"universal themes": 6,
	"damogen furies": 6,
	"dumb flesh": 6,
	"sol invictus": 6,
	"dark bird is home": 6,
	"why make sense?": 6,
	"tierra y libertad": 6,
	"dark red": 6,
	"this world is not enough": 6,
	"coin coin chapter three: river run thee": 6,
	"man it feels like space again": 6,
	"you're better than this": 6,
	"aureate gloom": 6,
	"death mask": 6,
	"777": 6,
	"2014 forest hills drive": 6,
	"sour soul": 6,
	"sauna": 6,
	"rose mountain": 6,
	"the pale emperor": 6,
	"a better tomorrow": 6,
	"if there's a hell below": 6,
	"mr noah": 6,
	"under pressure": 6,
	"cadillactica": 6,
	"girls in peacetime want to dance": 6,
	"tomorrow's modern boxes": 6,
	"the endless river": 6,
	"clark": 6,
	"xen": 6,
	"seeds": 6,
	"coffins on io": 6,
	"primitive and deadly": 6,
	"syro": 6,
	"i am king": 6,
	"soused": 6,
	"blue": 6,
	"tunnel blanket": 6,
	"dude incredible": 6,
	"caustic window lp": 6,
	"anchor": 6,
	"help": 6,
	"never hungover again": 6,
	"garbage": 6,
	"angels and devils": 6,
	"the physical world": 6,
	"barragán": 6,
	"manipulator": 6,
	"el pintor": 6,
	"foundations of burden": 6,
	"nobody's smiling": 6,
	"our love": 6,
	"good to be home": 6,
	"faces": 6,
	"the serpent & the sphere": 6,
	"ardour": 6,
	"divide and exit": 6,
	"eyehategod": 6,
	"it's album time": 6,
	"jimmy the burnout": 6,
	"i never learn": 6,
	"are we there": 6,
	"home, like noplace is there": 6,
	"tha carter v": 6,
	"nabuma rubberband": 6,
	"cilvia demo": 6,
	"terrestrials": 6,
	"the lack long after": 6,
	"here and nowhere else": 6,
	"dead": 6,
	"alternate/endings": 6,
	"decompositions: volume number one": 6,
	"the underground resistance": 6,
	"the final frontier": 6,
	"awake": 6,
	"no mythologies to follow": 6,
	"beyoncé": 6,
	"tsol": 6,
	"endless fantasy": 6,
	"valonielu": 6,
	"årabrot": 6,
	"government plates": 6,
	"blue chips 2": 6,
	"rave tapes": 6,
	"nature noir": 6,
	"blood tears": 6,
	"vicki leekx": 6,
	"lawless darkness": 6,
	"the blind hole": 6,
	"doris": 6,
	"artpop": 6,
	"my name is my name": 6,
	"koloss": 6,
	"return to annihilation": 6,
	"factory floor": 6,
	"r plus seven": 6,
	"magna carta holy grail": 6,
	"hesitation marks": 6,
	"watching movies with the sound off": 6,
	"legends never die": 6,
	"an object": 6,
	"paracosm": 6,
	"slow focus": 6,
	"acid rap": 6,
	"moody coup": 6,
	"tomorrow's harvest": 6,
	"hanging gardens": 6,
	"mgmt": 6,
	"the north borders": 6,
	"monomania": 6,
	"obsidian": 6,
	"woman": 5,
	"czarface": 6,
	"wolf": 6,
	"quantum leap": 6,
	"adam green & binki shapiro": 6,
	"the terror": 6,
	"oddfellows": 6,
	"california x": 6,
	"afraid of heights": 6,
	"black masses": 6,
	"widowmaker": 6,
	"love is love // return to dust": 6,
	"see the world given to a one love entity": 6,
	"muchacho": 6,
	"wu-block": 6,
	"waiting for something to happen": 6,
	"koi no yokan": 6,
	"book burner": 6,
	"2": 6,
	"metz": 6,
	"kaleidoscope dream": 6,
	"lux": 6,
	"jiaolong": 6,
	"key to the kuffs": 6,
	"local business": 6,
	"babel": 6,
	"shields": 6,
	"total loss": 6,
	"clockwork angels": 6,
	"held": 6,
	"mature themes": 6,
	"centipede hz": 6,
	"instinct": 6,
	"shrines": 6,
	"gossamer": 6,
	"swing lo magellan": 6,
	"oceania": 6,
	"unsound": 6,
	"cancer 4 cure": 6,
	"the bravest man in the universe": 6,
	"ufabulum": 6,
	"with siinai: heartbreaking bravery": 6,
	"spooky action at a distance": 6,
	"kings and them": 6,
	"blunderbuss": 6,
	"mu.zz.le": 6,
	"let's go eat the factory": 6,
	"angels of darkness, demons of light ii": 6,
	"room(s)": 6,
	"severant": 6,
	"radiant door": 6,
	"el camino": 6,
	"cole world: the sideline story": 6,
	"take care": 6,
	"celestial lineage": 6,
	"parallax": 6,
	"lulu": 6,
	"humor risk": 6,
	"you are all i see": 6,
	"on the water": 6,
	"leave home": 6,
	"blackenedwhite": 6,
	"relax": 6,
	"in the mountain in the cloud": 6,
	"all things will unwind": 6,
	"hell: the sequel": 6,
	"the rip tide": 6,
	"slave ambient": 6,
	"within and without": 6,
	"bon iver, bon iver": 6,
	"heavy rocks": 6,
	"what did you expect from the vaccines?": 6,
	"nine types of light": 6,
	"wasting light": 6,
	"the king of limbs": 6,
	"apocalypse": 3,
	"white wilderness": 6,
	"shut up, dude": 6,
	"underneath the pine": 6,
	"becoming a jackal": 6,
	"kiss each other clean": 6,
	"the fool": 6,
	"my beautiful dark twisted fantasy": 6,
	"my father will guide me up a rope to the sky": 6,
	"the age of adz": 6,
	"write about love": 6,
	"transit transit": 6,
	"wilderness heart": 6,
	"everything in between": 6,
	"man on the moon ii: the legend of mr. rager": 6,
	"something for everybody": 6,
	"does it look like i'm here?": 6,
	"innerspeaker": 6,
	"sir lucious left foot: the son of chico dusty": 6,
	"high violet": 6,
	"happy birthday": 6,
	"expo 86": 6,
	"big echo": 6,
	"sisterworld": 6,
	"go": 6,
	"swim": 6,
	"fine line": 5,
	"feet of clay": 5,
	"city as school": 5,
	"everyday life": 5,
	"hitler wears hermes 7": 5,
	"pony": 5,
	"kirk": 5,
	"hollywood's bleeding": 5,
	"juice b crypts": 5,
	"sound & fury": 5,
	"case study  01": 5,
	"birth of violence": 5,
	"house of sugar": 5,
	"the center won't hold": 5,
	"flamagra": 5,
	"crash talk": 5,
	"help us stranger": 5,
	"rammstein": 5,
	"gold & grey": 5,
	"map of the soul : persona": 5,
	"proto": 5,
	"psychodrama": 5,
	"u.f.o.f.": 5,
	"social cues": 5,
	"x 100pre": 5,
	"czarface meets ghostface": 5,
	"championships": 5,
	"white bronco": 5,
	"future & juice wrld present... wrld on drugs": 5,
	"ballads 1": 5,
	"simulation theory": 5,
	"ysiv": 5,
	"life's a trip": 5,
	"head in the clouds": 5,
	"everything is love": 5,
	"electricity is on our side": 5,
	"goodbye & good riddance": 5,
	"queen": 5,
	"jxmtro": 5,
	"stay dangerous": 5,
	"why hasn't everything already disappeared?": 5,
	"ordinary corrupt human love": 5,
	"kod": 5,
	"tranquility base hotel & casino": 5,
	"my dear melancholy,": 5,
	"bobby tarantino ii": 5,
	"sex & food": 5,
	"eat the elephant": 5,
	"song for alpha": 5,
	"new material": 5,
	"time & space": 5,
	"a productive cough": 5,
	"double or nothing": 5,
	"no dope on sundays": 5,
	"godfather ii": 5,
	"vicious": 5,
	"plunge": 5,
	"i can feel you creep into my private life": 5,
	"super slimey": 5,
	"a love letter to you 2": 5,
	"heaven upside down": 5,
	"project baby 2": 5,
	"mr. davis": 5,
	"tau": 5,
	"ken": 5,
	"agnus dei": 5,
	"cursed": 5,
	"sketches of brunswick east": 5,
	"black ken": 5,
	"the booty tape": 5,
	"luciferian towers": 5,
	"i tell a fly": 5,
	"tfcf": 5,
	"good for you": 5,
	"beautiful thugger girls": 5,
	"a deeper understanding": 5,
	"quazarz vs. the jealous machines": 5,
	"the golden age": 5,
	"something to tell you": 5,
	"everybody": 5,
	"planetarium": 5,
	"humanz": 5,
	"at what cost": 5,
	"relaxer": 5,
	"somersault": 5,
	"rocket": 5,
	"arca": 5,
	"future": 5,
	"in mind": 5,
	"sincerely, future pollution": 5,
	"stillness in wonderland": 5,
	"more life": 5,
	"semper femina": 5,
	"cozy tapes vol. 1 friends": 5,
	"oczy mlody": 5,
	"black america again": 5,
	"starboy": 5,
	"autotheism": 5,
	"1992": 5,
	"phantom antichrist": 5,
	"the healing component": 5,
	"22, a million": 5,
	"the altar": 5,
	"summer songs 2": 5,
	"the bible 2": 5,
	"bobby tarantino": 5,
	"blank face lp": 5,
	"hypercaffium spazzinate": 5,
	"there's alot going on": 5,
	"innocence reaches": 5,
	"the human condition": 5,
	"patagonian rats": 5,
	"the colour in anything": 5,
	"the getaway": 5,
	"skin": 5,
	"slime season 3": 5,
	"the bride": 5,
	"too high to riot": 5,
	"love streams": 5,
	"i'm up": 5,
	"oblivion access": 5,
	"painting with": 5,
	"life of pause": 5,
	"leaving": 5,
	"pool": 5,
	"a head full of dreams": 5,
	"it's better this way": 5,
	"purpose": 5,
	"thank your lucky stars": 5,
	"late knight special": 5,
	"all we need": 5,
	"no closer to heaven": 5,
	"circle the wagons": 5,
	"fetty wap": 5,
	"haha": 5,
	"honeymoon": 5,
	"sam baker's album": 5,
	"every open eye": 5,
	"beauty behind the madness": 5,
	"what went down": 5,
	"ego death": 5,
	"wildheart": 5,
	"death magic": 5,
	"at.long.last.a$ap": 5,
	"barter 6": 5,
	"pale horses": 5,
	"payola": 5,
	"choose your weapon": 5,
	"the wonder years": 5,
	"drones": 5,
	"lantern": 5,
	"ratchet": 5,
	"the ecology": 5,
	"blade of the ronin": 5,
	"sometimes i sit and think, and sometimes i just sit": 5,
	"undertow": 5,
	"sprinter": 5,
	"kintsugi": 5,
	"bush": 5,
	"mr. wonderful": 5,
	"strangers to ourselves": 5,
	"gliss riffer": 5,
	"blissfucker": 5,
	"36 seasons": 5,
	"bestiary": 5,
	"no label 2": 5,
	"between bodies": 5,
	"a toothpaste suburb": 5,
	"lords of flatbush": 5,
	"nehruviandoom": 5,
	"royal blood": 5,
	"bestial burden": 5,
	"true that": 5,
	"sonic highways": 5,
	"worlds": 5,
	"wonder where we land": 5,
	"time to die": 5,
	"these days...": 5,
	"world peace is none of your business": 5,
	"lese majesty": 5,
	"goddess": 5,
	"pale communion": 5,
	"christmas island": 5,
	"no peace": 5,
	"a u r o r a": 5,
	"lazaretto": 5,
	"white women": 5,
	"recess": 5,
	"enter the slasher house": 5,
	"salad days": 5,
	"everyday robots": 5,
	"neon icon": 5,
	"transgender dysphoria blues": 5,
	"rival dealer": 5,
	"because the internet": 5,
	"sun structures": 5,
	"burn your fire for no witness": 5,
	"aleph": 5,
	"reflektor": 5,
	"dysnomia": 5,
	"les voyages de l'âme": 5,
	"kiss land": 5,
	"the blackest beautiful": 5,
	"senior": 5,
	"nothing was the same": 5,
	"born sinner": 5,
	"the raven that refused to sing (and other stories)": 5,
	"blue slide park": 5,
	"yeezus": 5,
	"with love": 5,
	"infestissumam": 5,
	"vexovoid": 5,
	"vertikal": 5,
	"comedown machine": 5,
	"floating coffin": 5,
	"the 20/20 experience": 5,
	"bankrupt!": 5,
	"home": 5,
	"mosquito": 5,
	"broke with expensive taste": 5,
	"jesus piece": 5,
	"push the sky away": 5,
	"wiki93": 5,
	"wild water kingdom": 5,
	"instrumental tourist": 5,
	"holy fire": 5,
	"hummingbird": 5,
	"cobra juicy": 5,
	"we don't even live here": 5,
	"piramida": 5,
	"ocean roar": 5,
	"world music": 5,
	"no idols": 5,
	"advaitic songs": 5,
	"food & liquor 2: the great american rap album pt. 1": 5,
	"mysterious phonk: the chronicles of spaceghostpurrp": 5,
	"vicious lies and dangerous rumors": 5,
	"america": 5,
	"confess": 5,
	"r.i.p.": 5,
	"quakers": 5,
	"celebration rock": 5,
	"habits & contradictions": 5,
	"mr. impossible": 5,
	"given to the wild": 5,
	"port of morrow": 5,
	"love at the bottom of the sea": 5,
	"thank you happy birthday": 5,
	"reign of terror": 5,
	"radioactive": 5,
	"old ideas": 5,
	"onwards to the wall": 5,
	"visions": 5,
	"heritage": 5,
	"enough thunder": 5,
	"crazy clown time": 5,
	"audio, video, disco": 5,
	"the hunter": 5,
	"watch the throne": 5,
	"join us": 5,
	"portamento": 5,
	"unknown mortal orchestra": 5,
	"go tell fire to the mountain": 5,
	"i'm with you": 5,
	"ascension": 5,
	"turtleneck & chain": 5,
	"circuital": 5,
	"david comes to life": 5,
	"sun & shade": 5,
	"suck it and see": 5,
	"shaolin vs. wu-tang": 5,
	"yuck": 5,
	"take care, take care, take care": 5,
	"mind bokeh": 5,
	"tomboy": 5,
	"red barked tree": 5,
	"the fall": 5,
	"zonoscope": 5,
	"broken dreams club": 5,
	"face tat": 5,
	"shobaleader one: d'demonstrator": 5,
	"record collection": 5,
	"sidewalks": 5,
	"le noise": 5,
	"the budos band iii": 5,
	"down there": 5,
	"false priest": 5,
	"lisbon": 5,
	"interpol": 5,
	"crazy for you": 5,
	"the bride screamed murder": 5,
	"the people's record": 5,
	"oversteps": 5,
	"sea of cowards": 5,
	"broken bells": 5,
	"a love letter to you 4": 4,
	"hot pink": 4,
	"emmanuel": 4,
	"jesus is king": 4,
	"fear inoculum": 4,
	"k.r.i.t. iz here": 4,
	"sli'merre": 4,
	"hyperspace": 4,
	"i am easy to find": 4,
	"in league with dragons": 4,
	"where polly people go to read": 4,
	"bawskee 2": 4,
	"dummy boy": 4,
	"the last rocket": 4,
	"gallipoli": 4,
	"come over when you're sober, pt. 2": 4,
	"quavo huncho": 4,
	"east atlanta love letter": 4,
	"kamikaze": 4,
	"harverd dropout": 4,
	"from gas to solid / you are my friend": 4,
	"marauder": 4,
	"testing": 4,
	"redemption": 4,
	"scorpion": 4,
	"a girl cried red": 4,
	"?": 4,
	"the scars of man on the once nameless wilderness part i and ii": 4,
	"golden hour": 4,
	"the neighbourhood": 4,
	"culture ii": 4,
	"swell": 4,
	"no shame": 4,
	"weezer (black album)": 4,
	"syre": 4,
	"the thrill of it all": 4,
	"the ooz": 4,
	"reputation": 4,
	"pacific daydream": 4,
	"colors": 4,
	"cozy tapes vol. 2: too cozy": 4,
	"everything now": 4,
	"harry styles": 4,
	"slowdive": 4,
	"painting pictures": 4,
	"emperor of sand": 4,
	"÷": 4,
	"passion, pain & demon slayin'": 4,
	"rheia": 4,
	"the divine feminine": 4,
	"partynextdoor 3 (p3)": 4,
	"the serenity of suffering": 4,
	"aim": 4,
	"amnesty (i)": 4,
	"lil uzi vert vs. the world": 4,
	"genesis": 4,
	"views": 4,
	"mind of mine": 4,
	"gore": 4,
	"the wilderness": 4,
	"majid jordan": 4,
	"a new place 2 drown": 4,
	"anti": 4,
	"i like it when you sleep, for you are so beautiful yet so unaware of it": 4,
	"when it's dark out": 4,
	"dystopia": 4,
	"bad neighbor": 4,
	"skid row": 4,
	"free weezy album": 4,
	"belus": 4,
	"too": 4,
	"surf": 4,
	"all you can do": 4,
	"the most lamentable tragedy": 4,
	"freedom": 4,
	"blurryface": 4,
	"the parallax ii: future sequence": 4,
	"the peach panther": 4,
	"700 fill": 4,
	"another eternity": 4,
	"the album about nothing": 4,
	"eat pray thug": 4,
	"hyperview": 4,
	"kauai": 4,
	"panda bear meets the grim reaper": 4,
	"keep you": 4,
	"stn mtn": 4,
	"portal of sorrow": 4,
	"unknown memory": 4,
	".5: the gray chapter": 4,
	"indigo child": 4,
	"the flesh prevails": 4,
	"...and then you shoot your cousin": 4,
	"z": 4,
	"sunbathing animal": 4,
	"indie cindy": 4,
	"turn blue": 4,
	"ghost stories": 4,
	"morning phase": 4,
	"night time, my time": 4,
	"static": 4,
	"law and order": 4,
	"something else": 4,
	"sempiternal": 4,
	"trouble will find me": 4,
	"ready to die": 4,
	"new moon": 4,
	"floral shoppe": 4,
	"finally rich": 4,
	"zeros": 4,
	"anything in return": 4,
	"(iii)": 4,
	"based on a t.r.u. story": 4,
	"devotion": 4,
	"coexist": 4,
	"life is good": 4,
	"strange clouds": 4,
	"kill for love": 4,
	"acousmatic sorcery": 4,
	"the of tape vol. 2": 4,
	"young & old": 4,
	"purple naked ladies": 4,
	"ambition": 4,
	"metals": 4,
	"hurry up, we're dreaming": 4,
	"when fish ride bicycles": 4,
	"simple math": 4,
	"attention please": 4,
	"cults": 4,
	"goblin": 4,
	"burst apart": 4,
	"blood pressures": 4,
	"ritual": 4,
	"album of the year": 4,
	"the king is dead": 4,
	"play it strange": 4,
	"love remains": 4,
	"crush": 4,
	"come around sundown": 4,
	"surfing the void": 4,
	"total life forever": 4,
	"forgiveness rock record": 4,
	"erys": 3,
	"the life of pi'erre 4": 3,
	"apollo xxi": 3,
	"sea of worry": 3,
	"here comes the cowboy": 3,
	"music inspired by illumination & dr. seuss' the grinch": 3,
	"heard it in a past life": 3,
	"zoo": 3,
	"swimming": 8,
	"good job, you found me": 3,
	"day69": 3,
	"man of the woods": 3,
	"memories don't die": 3,
	"luv is rage 2": 3,
	"issa album": 3,
	"quazarz: born on a gangster star": 3,
	"revolution radio": 3,
	"the perfect luv tape": 3,
	"birds in the trap sing mcknight": 3,
	"lil b.i.g. pac": 3,
	"future present past": 3,
	"junk": 3,
	"warlord": 3,
	"ardipithecus": 3,
	"disharmony": 3,
	"general admission": 3,
	"not to disappear": 3,
	"angels exodus": 3,
	"dealer": 3,
	"pound syndrome": 3,
	"everybody is going to heaven": 3,
	"anika": 3,
	"cherry bomb": 3,
	"love story": 3,
	"living fields": 3,
	"eclipse": 3,
	"owl pharaoh": 3,
	"days before rodeo": 3,
	"green language": 3,
	"reality testing": 3,
	"built on glass": 3,
	"g i r l": 3,
	"love death immortality": 3,
	"atlas": 3,
	"knock madness": 3,
	"am": 3,
	"edward sharpe & the magnetic zeros": 3,
	"true romance": 3,
	"miracle mile": 3,
	"heartthrob": 3,
	"into the future": 3,
	"welcome to: our house": 3,
	"numbers": 3,
	"lords never worry": 3,
	"the 2nd law": 3,
	"god forgives, i don't": 3,
	"born villain": 3,
	"the stoned immaculate": 3,
	"the only place": 3,
	"wzrd": 3,
	"synthetica": 3,
	"resolution": 3,
	"kills": 3,
	"born to die": 3,
	"cerebral ballzy": 3,
	"era extraña": 3,
	"american ghetto": 3,
	"house of balloons": 3,
	"tha carter iv": 3,
	"lasers": 3,
	"different gear, still speeding": 3,
	"treats": 3,
	"tomorrow, in a year": 3,
	"nine": 2,
	"drip or drown 2": 2,
	"skins": 2,
	"the sunset tapes: a cool tape story": 2,
	"nuthin' 2 prove": 2,
	"revival": 2,
	"17": 2,
	"teenage emotions": 2,
	"narkopop": 2,
	"silhouette of a sunkken city": 2,
	"always strive and prosper": 2,
	"and after that, we didn't talk": 2,
	"professional rapper": 2,
	"partynextdoor two": 2,
	"...and star power": 2,
	"ultraviolence": 2,
	"enclosure": 2,
	"cupid deluxe": 2,
	"burials": 2,
	"honest": 2,
	"pbx funicular intaglio zone": 2,
	"indicud": 2,
	"camp": 2,
	"w": 2,
	"sex dreams and denim jeans": 2,
	"king night": 2,
	"93punx": 1,
	"she is coming": 1,
	"confessions of a dangerous mind": 1,
	"red light": 1,
	"swaecation": 1,
	"miley cyrus & her dead petz": 1,
	"instant gratification": 1,
	"the big day": 0,
	"speedin' bullet 2 heaven": 0,
	"homecoming: the live album": 8,
	"jackboys": 5,
	"untitled unmastered.": 8,
	"originals": 8,
	"leak 04-13 (bait ones)": 6,
	"\"awaken, my love!\"": 7,
	"black panther the album music from and inspired by": 6,
	"electric lady sessions": 6,
	"græ": 7,
	"harutosyura": 8,
	"twin fantasy": 8,
	"なんだこれくしょん": 8,
	"works by tuli kupferberg (1923-2010)": 7,
	"99 cents": 7,
	"emotion": 7,
	"emotion: side b": 8,
	"love yourself 轉 'tear'": 6,
	"but you caint use my phone (mixtape)": 6,
	"love is love / return to dust": 6,
	"cozy tapes: vol. 1 friends -": 5,
	"bon iver": 6,
	"live.love.a$ap": 8,
	"everything not saved will be lost part i": 6,
	"hi this is flume (mixtape)": 8,
	"adrian younge presents: 12 reasons to die i": 8,
	"joy as an act of resistance.": 9,
	"magna carta... holy grail": 6,
	"i don't like shit, i don't go outside: an album by earl sweatshirt": 6,
	"windswept adan": 9,
	"shunka ryougen": 7,
	"上出来": 7,
	"años en infierno": 6,
	"promises": 9,
	"miles": 9,
	"cheat codes": 8,
	"faith in persona": 8,
}