top_tracks_2010 = {
    "flying lotus - do the astral plane",
    "duck sauce - barbra streisand - original mix",
    "the pains of being pure at heart - say no to love",
    "ceelo green - fuck you",
    "belle and sebastian - come on sister",
    "crystal stilts - shake the shackles",
    "laurie anderson - another day in america",
    "the tallest man on earth - burden of tomorrow",
    "owen pallett - lewis takes off his shirt",
    "mr twin sister - all around and away we go",
    "diamond rings - all yr songs",
    "the roots & monsters of folk - dear god 2.0",
    "future islands - walking through that door",
    "deerhunter - revival",
    "woods - blood dries darker",
    "the radio dept. - heaven's on fire",
    "here we go magic - collector",
    "pantha du prince - the splendour",
    "washed out - you and i",
    "arcade fire - the suburbs",
    "the national - bloodbuzz ohio",
    "fergus & geronimo - turning blue",
    "ceremony - into the wayside part i/sick",
    "janelle monáe & big boi - tightrope (feat. big boi) - big boi vocal edit",
    "adam green - buddy bradley",
    "civil civic - run overdrive",
    "brandon flowers - was it something i said?",
    "happy birthday - girls fm",
    "devo - fresh",
    "glasser - mirrorage",
    "the books - i didn't know that",
    "chromeo - night by night",
    "women - eyesore",
    "crystal castles - not in love",
    "das racist & heems - who's that brown",
    "anamanaguchi - my skateboard will go on",
    "caribou - odessa",
    "ariel pink - round and round",
    "kanye west - power",
    "mgmt - congratulations",
    "dumbo gets mad - plumy tale",
    "gonjasufi - kowboyz&indians",
    "four tet - love cry",
    "vampire weekend - holiday",
    "big boi & cutty - shutterbugg",
    "beach house - take care",
    "gorillaz & lou reed - some kind of nature (feat. lou reed)",
    "lcd soundsystem - i can change",
}

top_tracks_2011 = {
    "the drums - money",
    "balkans - edita v",
    "wild beasts - reach a bit further",
    "purity ring - belispeak",
    "tyler, the creator - yonkers",
    "m83 - midnight city",
    "beastie boys - make some noise",
    "gotye & kimbra - somebody that i used to know",
    "colin stetson - the righteous wrath of an honorable man",
    "little dragon - nightlight",
    "fucked up - queen of hearts",
    "the pains of being pure at heart - belong",
    "nas - nasty",
    "craft spells - after the moment",
    "the horrors - still life",
    "veronica falls - bad feeling",
    "das racist - michael jackson",
    "wild flag - future crimes",
    "kate bush - wild man",
    "rival sons - pressure and time",
    "metronomy - the look",
    "radiohead - the daily mail",
    "tv on the radio - will do",
    "rustie - ultra thizz",
    "st. vincent - surgeon",
    "sbtrkt & little dragon - wildfire",
    "theophilus london & devonté hynes & solange - flying overseas (feat. devonte hynes and solange knowles)",
    "smith westerns - weekend",
    "foo fighters - walk",
    "crystal stilts - shake the shackles",
    "cunninlynguists - hard as they come (act one) f. freddie gibbs",
    "reks & styles p & termanology & dj corbet & freeway & lil fame of m.o.p. & attica bars - 25th hour - prod. by dj premier",
    "big k.r.i.t. - dreamin'",
    "macklemore & ryan lewis - wing$",
    "john maus - believer",
    "la dispute - king park",
    "the roots & big k.r.i.t. & dice raw - make my",
    "timber timbre - black water",
    "active child - playing house",
    "kendrick lamar - hiiipower",
    "africa hitech - out in the streets",
    "liturgy - returner",
    "battles & matias aguayo - ice cream",
    "bon iver - holocene",
    "holy ghost! - do it again",
    "shabazz palaces - swerve... the reeping of all that is worthwhile (noir not withstanding)",
    "pj harvey - the words that maketh murder",
    "james blake - the wilhelm scream",
    "death grips - takyon (death yon)",
    "fleet foxes - helplessness blues",
}

top_tracks_2012 = {
    "grimes - oblivion",
    "here we go magic - how do i know",
    "david byrne & st. vincent - who",
    "rhye - open",
    "lil b - i own swag",
    "zebra katz & njena reddd foxxx - ima read",
    "the vaccines - post break-up sex",
    "scott walker - epizootics!",
    "squarepusher - dark steering",
    "first aid kit - wolf",
    "boddika & joy orbison - mercy - boddikas vip",
    "dirty projectors - gun has no trigger",
    "alt-j - breezeblocks",
    "danny brown - grown up",
    "action bronson & alchemist - the symbol",
    "joey bada$$ & capital steez - survival tactics",
    "high on fire - fertile green",
    "veronica falls - my heart beats",
    "wild nothing - shadow",
    "michael kiwanuka - home again",
    "angel olsen - the waiting",
    "iamamiwhoami - goods",
    "king krule - rock bottom",
    "holograms - abc city",
    "converge - aimless arrow",
    "lone - crystal caverns 1991",
    "the magnetic fields - andrew in drag",
    "jessie ware - wildest moments",
    "billy woods & masai bey & roc marciano - body of work",
    "matthew dear - her fantasy",
    "soap&skin - voyage voyage",
    "the mars volta - zed and two naughts",
    "el-p - the full retard",
    "holy ghost! - it gets dark",
    "kendrick lamar - swimming pools (drank)",
    "sharon van etten - leonard",
    "perfume genius - hood",
    "desaparecidos - backsell",
    "cloud nothings - stay useless",
    "ab-soul & danny brown & jhené aiko - terrorist threats (feat. danny brown & jhene aiko)",
    "frank ocean - pyramids",
    "dinosaur jr. - watch the corners",
    "fiona apple - every single night",
    "ondatrópica - punkero sonidero",
    "macklemore & ryan lewis & mary lambert - same love (feat. mary lambert)",
    "tnght - bugg'n",
    "killer mike & bun b & t.i. & trouble - big beast (feat. bun b, t.i., and trouble)",
    "gorillaz & andré 3000 - doyathing",
    "spiritualized - hey jane",
    "death grips - the fever (aye aye)",
}

top_tracks_2013 = {
    "machinedrum - eyesdontlie",
    "touché amoré - just exist",
    "denzel curry & yung simmie & robb bank$ - threatz (feat. yung simmie & robb bank$)",
    "yeah yeah yeahs - sacrilege",
    "daft punk & pharrell williams & nile rodgers - get lucky (feat. pharrell williams and nile rodgers)",
    "kanye west - bound 2",
    "lady gaga - applause",
    "eminem - berzerk",
    "run the jewels & big boi - banana clipper",
    "atoms for peace - ingenue",
    "the flaming lips - sun blows up today",
    "cage the elephant - come a little closer",
    "jon hopkins - open eye signal",
    "mgmt - alien days",
    "james blake - retrograde",
    "kvelertak - bruane brenn",
    "janelle monáe & miguel - primetime (feat. miguel)",
    "foxygen - no destruction",
    "chvrches - recover",
    "smith westerns - varsity",
    "earl sweatshirt & vince staples & casey veggies - hive (feat. vince staples & casey veggies)",
    "lorde - royals",
    "the underachievers - the proclamation",
    "dope body - leather head",
    "dope body - youth relic",
    "soap&skin - sugarbread",
    "da mafia 6ix & yelawolf - go hard",
    "disclosure - f for you",
    "black milk - sunday's best",
    "black milk - monday's worst",
    "factory floor - fall back",
    "a$ap ferg & a$ap rocky - shabba (feat. a$ap rocky)",
    "gesaffelstein - pursuit",
    "king krule - easy easy",
    "melt yourself down - fix my life",
    "anamanaguchi - meow",
    "m.i.a. - bring the noize",
    "kurt vile - wakin on a pretty day",
    "billy woods - tinseltown",
    "grave babies - over and under ground",
    "just blaze & baauer & jay-z - higher",
    "vampire weekend - step",
    "kyary pamyu pamyu - インベーダーインベーダー",
    "haim - the wire",
    "iceage - ecstasy",
    "arcade fire - reflektor",
    "mariam the believer - invisible giving",
    "queens of the stone age - my god is the sun",
    "savages - shut up",
    "ariel pink & jorge elbrecht - hang on to life",
    "pusha t - numbers on the boards",
    "the knife - a tooth for an eye",
}

top_tracks_2014 = {
    "\"weird al\" yankovic - handy",
    "my brightest diamond - this is my hand",
    "vince staples - blue suede",
    "og maco - u guessed it",
    "mick jenkins - leonidas",
    "the wytches - wire frame mattress",
    "wildbirds & peacedrums - keep some hope",
    "pusha t - lunch money",
    "la roux - uptight downtown",
    "preoccupations - continental shelf",
    "yacht - works like magic",
    "joey bada$$ - christ conscious",
    "alt-j - left hand free",
    "deafheaven - from the kettle onto the coil",
    "d'angelo - sugah daddy",
    "sir michael rocks - memo",
    "sir michael rocks & casey veggies & iamsu! - bussin",
    "perfume genius - queen",
    "sharon van etten - taking chances",
    "metronomy - love letters",
    "young fathers - get up",
    "paula temple - deathvox",
    "big k.r.i.t. - mt. olympus (reprise)",
    "jay rock - parental advisory",
    "civil civic v r. stevie moore - when you gonna find me a wife?",
    "black milk and badbadnotgood - now or never",
    "holly herndon - chorus",
    "nico segal - sunday candy",
    "schoolboy q - break the bank",
    "a sunny day in glasgow - in love with useless",
    "open mike eagle - dark comedy late show",
    "the voidz - human sadness",
    "flying lotus & kendrick lamar - never catch me",
    "young thug & a$ap ferg & freddie gibbs - old english",
    "tune-yards - water fountain",
    "death grips - inanimate sensation",
    "sun kil moon - the possum",
    "fka twigs - two weeks",
    "run the jewels - oh my darling don't cry",
    "lykke li - love me like i'm not made of stone",
    "ariel pink - put your number in my phone",
    "your old droog - hoodie weather",
    "st. vincent - digital witness",
    "iceage - the lord's favorite",
    "freddie gibbs & madlib & bj the chicago kid - shame (feat. bj the chicago kid)",
    "freddie gibbs & madlib & action bronson & joey bada$$ & ransom - knicks remix",
    "clipping. - knees on the ground",
    "sia - chandelier",
    "future islands - seasons (waiting on you)",
    "timber timbre - hot dreams",
    "swans - oxygen",
    "liars - mess on a mission",
}

top_tracks_2015 = {
    "deerhunter - snakeskin",
    "action bronson - actin crazy",
    "toro y moi - empty nesters",
    "the chemical brothers - go",
    "florence + the machine - ship to wreck",
    "kelela - rewind",
    "liturgy - quetzalcoatl",
    "young thug - best friend",
    "kalifa - rage",
    "david hasselhoff - true survivor - from \"kung fury\"",
    "pusha t - untouchable",
    "chelsea wolfe - carrion flowers",
    "mac miller - 100 grandkids",
    "dope body - obey",
    "unknown mortal orchestra - multi-love",
    "the game & drake - 100 (feat. drake)",
    "alabama shakes - don't wanna fight",
    "chance the rapper & saba - angels (feat. saba)",
    "weezer - do you wanna get high?",
    "sufjan stevens - should have known better",
    "david bowie - blackstar",
    "neon indian - slumlord",
    "tame impala - let it happen",
    "fka twigs - in time",
    "sophie - vyzee",
    "iglooghost - chinchou / melon lantern girl's choir",
    "animal collective - floridada",
    "travis scott - antidote",
    "sleater-kinney - no cities to love",
    "grimes - realiti",
    "the pop group - mad truth",
    "shamir - call it off",
    "julia holter - sea calls me home",
    "carly rae jepsen - emotion",
    "m.i.a. - borders",
    "clarence clarity - bloodbarf",
    "the weeknd - can't feel my face",
    "jeff rosenstock - nausea",
    "nico segal - sunday candy",
    "algiers - irony. utility. pretext.",
    "injury reserve - everybody knows",
    "drake - hotline bling",
    "everything everything - distant past",
    "hannah diamond - hi",
    "missy elliott & pharrell williams - wtf (where they from) [feat. pharrell williams]",
    "baroness - shock me",
    "ghost - cirice",
    "jamie xx & young thug & popcaan - i know there's gonna be (good times)",
    "death grips - on gp",
    "kendrick lamar - the blacker the berry",
}

top_tracks_2016 = {
    "pj harvey - the wheel",
    "the avalanches - frankie sinatra",
    "rae sremmurd & gucci mane - black beatles",
    "riff raff - 4 million",
    "nxworries - lyk dis",
    "sturgill simpson - brace for impact (live a little)",
    "jpegmafia & freaky - i might vote 4 donald trump",
    "the dillinger escape plan - limerent death",
    "childish gambino - redbone",
    "gucci mane - all my children",
    "nick cave & the bad seeds - jesus alone",
    "solange - cranes in the sky",
    "the drones - taman shud",
    "preoccupations - anxiety",
    "clipping. - baby don't sleep",
    "run the jewels - legend has it",
    "rich brian - dat $tick",
    "foxygen - america",
    "king gizzard & the lizard wizard - gamma knife",
    "yung lean - hoover",
    "schoolboy q & jadakiss - groovy tony / eddie kane",
    "a tribe called quest - we the people....",
    "ab-soul - d.r.u.g.s.",
    "iggy pop - gardenia",
    "anohni - drone bomb me",
    "regina spektor - older and taller",
    "missy elliott & pharrell williams - wtf (where they from) [feat. pharrell williams]",
    "kanye west - ultralight beam",
    "weezer - l.a. girlz",
    "denzel curry - ult",
    "vektor - charging the void",
    "kendrick lamar - untitled 07 | levitate",
    "bruno mars - 24k magic",
    "kero kero bonito - break",
    "the weeknd & daft punk - starboy",
    "yg & nipsey hussle - fdt",
    "radiohead - burn the witch",
    "lady gaga - million reasons",
    "chance the rapper & lil wayne & 2 chainz - no problem (feat. lil wayne & 2 chainz)",
    "dram & lil yachty - broccoli",
    "dram - cash machine",
    "car seat headrest - drunk drivers/killer whales",
    "death grips - giving bad people good ideas",
    "beyoncé - formation",
    "young thug & travis scott - pick up the phone",
    "lil yachty & quavo & skippa da flippa & young thug - minnesota",
    "angel olsen - shut up kiss me",
    "hannah diamond - hi",
    "danny brown & kendrick lamar & ab-soul & earl sweatshirt - really doe",
    "injury reserve - oh shit!!!",
    "david bowie - blackstar",
}

top_tracks_2017 = {
    "kimbra - top of the world",
    "yung lean - red bottom sky",
    "the killers - run for cover",
    "kesha - praying",
    "juicy j & offset - flood watch (feat. offset)",
    "playboi carti - magnolia",
    "cardi b - bodak yellow",
    "fleet foxes - third of may / ōdaigahara",
    "ski mask the slump god - catch me outside",
    "kelela - waitin",
    "charli xcx - boys",
    "feist - pleasure",
    "alvvays - plimsoll punks",
    "roger waters - déjà vu",
    "lil pump - gucci gang",
    "rapsody & kendrick lamar & lance skiiiwalker - power",
    "protomartyr - don't go to anacita",
    "vince staples - big fish",
    "st. vincent - pills",
    "big k.r.i.t. - keep the devil off",
    "ibeyi & kamasi washington - deathless",
    "n.e.r.d & rihanna - lemon",
    "lou from paradise - macklemore",
    "ibibio sound machine - the pot is on fire",
    "the mountain goats - rain in soho",
    "iglooghost - white gum",
    "sophie - it's okay to cry",
    "sza - the weekend",
    "ariel pink - feels like heaven",
    "post malone & 21 savage - rockstar",
    "paramore - hard times",
    "mgmt - little dark age",
    "perfume genius - slip away",
    "migos - t-shirt",
    "idles - mother",
    "poppy - computer boy",
    "tyler, the creator & rex orange county & anna of the north - boredom (feat. rex orange county & anna of the north)",
    "lorde - liability",
    "hmltd - to the door",
    "open mike eagle & has-lo - 95 radios",
    "injury reserve - see you sweat",
    "alex cameron & angel olsen - stranger's kiss (duet with angel olsen)",
    "jay-z - the story of o.j.",
    "rina sawayama - cyber stockholm syndrome",
    "kendrick lamar - humble.",
    "mount eerie - real death",
    "algiers - the underside of power",
    "brockhampton - gold",
    "kirin j callinan - bravado",
    "father john misty - pure comedy",
}

top_tracks_2018 = {
    "trippie redd - topanga",
    "hozier & mavis staples - nina cried power (feat. mavis staples)",
    "jon hopkins - emerald rush",
    "sheck wes - mo bamba",
    "eminem - killshot",
    "iceage - catch it",
    "andrew w.k. - music is worth living for",
    "brockhampton - 1998 truman",
    "kurt vile - loading zones",
    "ariana grande - god is a woman",
    "tricot - potage",
    "tricot - on the boom",
    "julia holter - i shall love 2",
    "mgmt - me and michael",
    "screaming females - i'll make you sorry",
    "the voidz - qyurryus",
    "cordae - old niggas",
    "anderson .paak - bubblin",
    "kali uchis & tyler, the creator & bootsy collins - after the storm (feat. tyler, the creator & bootsy collins)",
    "mark ronson & miley cyrus - nothing breaks like a heart (feat. miley cyrus)",
    "jmsn - talk is cheap",
    "petite noir - blame fire",
    "kero kero bonito - make believe",
    "twenty one pilots - jumpsuit",
    "charli xcx & troye sivan - 1999",
    "father john misty - mr. tillman",
    "superorganism - everybody wants to be famous",
    "jack white - corporation",
    "jid & j. cole - off deez (with j. cole)",
    "u.s. girls - pearly gates",
    "grimes & hana - we appreciate power",
    "juice wrld - lucid dreams",
    "ghost - rats",
    "denzel curry - clout cobain | clout co13a1n",
    "travis scott - sicko mode",
    "george clanton - make it forever",
    "rosalía - malamente - cap.1: augurio",
    "dram - best hugs",
    "rico nasty - rage",
    "jpegmafia - 1539 n. calvert",
    "natalia lafourcade & los macorinos - danza de gardenias (feat. los macorinos)",
    "lizzo - boys",
    "kids see ghosts - reborn",
    "idles - danny nedelko",
    "parquet courts - wide awake",
    "death grips - black paint",
    "janelle monáe - make me feel",
    "daughters - satan in the wait",
    "sophie - ponyboy",
    "childish gambino - this is america",
}

top_tracks_2019 = {
    "kai whiston & babii & iglooghost - lockii",
    "dj premier & westside gunn & conway the machine & benny the butcher - headlines (feat. westside gunn, conway & benny)",
    "black midi - talking heads",
    "rammstein - deutschland",
    "black country, new road - sunglasses",
    "clipping. - blood of the fang",
    "angel olsen - all mirrors",
    "squid - houseplants",
    "blueface & cardi b & yg - thotiana (feat. cardi b, yg) [remix]",
    "fka twigs - cellophane",
    "rosalía - a palé",
    "poppy - bloodmoney",
    "ghost - kiss the go-goat",
    "rina sawayama - stfu!",
    "mgmt - in the afternoon",
    "jpegmafia - jesus forgive me, i am a thot",
    "american football & hayley williams - uncomfortably numb (feat. hayley williams)",
    "lana del rey - the greatest",
    "doja cat & rico nasty - tia tamera (feat. rico nasty)",
    "caroline polachek - so hot you're hurting my feelings",
    "michael kiwanuka - piano joint (this kind of love)",
    "purple mountains - darkness and cold",
    "anderson .paak & smokey robinson - make it better (feat. smokey robinson)",
    "injury reserve & aminé - jailbreak the tesla (feat. aminé)",
    "freddie gibbs & madlib - crime pays",
    "denzel curry - ricky",
    "hobo johnson - subaru crosstrek xv",
    "megan thee stallion & ty dolla $ign & nicki minaj - hot girl summer (feat. nicki minaj & ty dolla $ign)",
    "vampire weekend - harmony hall",
    "lil nas x - old town road",
    "quelle chris - obamacare",
    "anamanaguchi - lorem ipsum (arctic anthem)",
    "kirin j callinan - the whole of the moon",
    "xiu xiu - pumpkin attack on mommy and daddy",
    "weyes blood - everyday",
    "slowthai & denzel curry - psycho",
    "lizzo - juice",
    "richard dawson - two halves",
    "liturgy - god of love",
    "billie eilish - bad guy",
    "zack fox & kenny beats - jesus is the one (i got depression)",
    "tkay maidza & jpegmafia - awake",
    "100 gecs & dylan brady & laura les - money machine",
    "lingua ignota - do you doubt me traitor",
    "danny brown - best life",
    "king gizzard & the lizard wizard - planet b",
    "charli xcx & christine and the queens - gone",
    "tyler, the creator - earfquake",
    "dorian electra - career boy",
    "alex cameron - far from born again",
}

top_tracks_2020 = {
    "black country, new road - science fair",
    "juice wrld - righteous",
    "freddie gibbs & hit-boy & big sean - 4 thangs (feat. big sean & hit-boy)",
    "phoebe bridgers - kyoto",
    "pop smoke & rowdy rebel - make it rain",
    "joji - run",
    "run the jewels & el-p & killer mike & greg nice & dj premier - ooh la la (feat. greg nice & dj premier)",
    "viagra boys - creatures",
    "terrace martin & denzel curry & kamasi washington & g perico & daylyt - pig feet (feat. kamasi washington, g perico & daylyt)",
    "chloe x halle - do it",
    "dua lipa - break my heart",
    "roddy ricch - the box",
    "rico nasty - iphone",
    "jpegmafia - bald!",
    "cupcakke - discounts",
    "thundercat - dragonball durag",
    "code orange - underneath",
    "bree runway & baby tate - damn daniel (with yung baby tate)",
    "danny l harle & lil texas - dreaming",
    "liturgy - siheymn's lament",
    "chris stapleton - cold",
    "kirin j callinan - you are going to miss me (when i am gone)",
    "eminem - darkness",
    "perfume genius - on the floor",
    "lingua ignota - o ruthless great divine director",
    "taylor swift & bon iver - exile (feat. bon iver)",
    "rina sawayama - xs",
    "fiona apple - shameika",
    "arca & rosalía - klk",
    "anderson .paak - lockdown",
    "gorillaz & schoolboy q - pac-man (feat. schoolboy q)",
    "charli xcx - forever",
    "tkay maidza - shook",
    "disclosure & slowthai - my high",
    "bring me the horizon - parasite eve",
    "lido pimienta & li saumet - nada",
    "clipping. - say the name",
    "idles - model village",
    "u.s. girls - 4 american dollars",
    "megan thee stallion - girls in the hood",
    "rmr - rascal",
    "lianne la havas - weird fishes",
    "100 gecs & charli xcx & rico nasty & kero kero bonito - ringtone (remix) [feat. charli xcx, rico nasty, kero kero bonito]",
    "hmltd - blank slate",
    "dorian electra & village people & pussy riot - my agenda",
    "blu & exile & blu & exile & jacinto rhines - the feeling",
    "jessie ware - spotlight",
    "the strokes - at the door",
    "cardi b & megan thee stallion - wap (feat. megan thee stallion)",
    "mac miller - good news",
}

top_tracks_2021 = {
    "weezer - all my favorite songs",
    "doja cat & sza - kiss me more (feat. sza)",
    "jid & denzel curry - bruuuh (with denzel curry) - remix",
    "pop smoke - ap - music from the film boogie",
    "pussy riot & dorian electra - toxic",
    "tokischa & rosalía - linda",
    "amber mark - foreign things",
    "black country, new road - concorde",
    "yola - diamond studded shoes",
    "slowthai & a$ap rocky - mazza (feat. a$ap rocky)",
    "lil texas - louder",
    "tkay maidza & baby tate - kim (with baby tate)",
    "meridian brothers & conjunto media luna - la secta",
    "cupcakke - moonwalk",
    "bruno mars & anderson .paak & silk sonic - smokin out the window",
    "alice longyu gao & alice glass - legend",
    "jessie ware - hot n heavy",
    "illuminati hotties - pool hopping",
    "magdalena bay - you lose!",
    "bbno$ & rich brian - edamame",
    "japanese breakfast - be sweet",
    "zack fox - fafo",
    "wet leg - chaise longue",
    "kero kero bonito - the princess and the clock",
    "rico nasty & flo milli - money (feat. flo milli)",
    "kirin j callinan - dumb enough",
    "taylor swift - all too well (10 minute version) (taylor's version) (from the vault)",
    "twin shadow - lonestar",
    "porter robinson - musician",
    "arca & oliver coates - madre",
    "ibeyi & pa salieu - made of gold",
    "sufjan stevens & angelo de augustine - cimmerian shade",
    "injury reserve - knees",
    "rina sawayama & elton john - chosen family (with elton john)",
    "richard dawson & circle - lily",
    "bleachers - how dare you want more",
    "lil nas x - montero (call me by your name)",
    "pinkpantheress - just for me",
    "remi wolf - quiet on set",
    "st. vincent - pay your way in pain",
    "black midi - john l",
    "genesis owusu - gold chains",
    "x?an & dj nic nac - hazard duty pay! - live jpegmafia type demo @ thereislight",
    "lingua ignota - pennsylvania furnace",
    "james blake - say what you will",
    "brockhampton & danny brown - buzzcut (feat. danny brown)",
    "low - days like these",
    "sharon van etten & angel olsen - like i used to",
    "spellling - boys at school",
    "little simz - introvert"
}

top_tracks_2022 = {
    "monaleo & flo milli - we not humping - remix",
    "benny the butcher & j. cole - johnny p's caddy",
    "the beths - expert in a dying field",
    "carly rae jepsen & rufus wainwright - the loneliest time (feat. rufus wainwright)",
    "bree runway - that girl",
    "the smile - you will never work in television again",
    "florence + the machine - king",
    "alex g - runner",
    "paramore - this is why",
    "ibibio sound machine - 17 18 19",
    "100 gecs - doritos & fritos",
    "u.s. girls - so typically now",
    "megan thee stallion - plan b",
    "gorillaz & thundercat - cracker island (feat. thundercat)",
    "toro y moi - the loop",
    "porter robinson & league of legends - everything goes on",
    "jean dawson - porn acting*",
    "pusha t & jay-z & pharrell williams - neck & wrist (feat. jay-z & pharrell williams)",
    "men i trust - girl",
    "quelle chris - alive ain't always living",
    "kilo kish - american gurl",
    "alice longyu gao - make u 3 me",
    "joji - glimpse of us",
    "beyoncé - break my soul",
    "rosalía - hentai",
    "king gizzard & the lizard wizard - hate dancin'",
    "lcd soundsystem - new body rhumba (from the film white noise)",
    "jid & kenny mason - dance now (feat. kenny mason)",
    "alvvays - very online guy",
    "caroline polachek - welcome to my island",
    "jockstrap - greatest hits",
    "daniel rossen - unpeopled space",
    "soul glo - jump!! (or get jumped!!!)((by the future))",
    "black midi - welcome to hell",
    "hemlocke springs - girlfriend",
    "big thief - simulation swarm",
    "jessie ware - free yourself",
    "denzel curry - walkin",
    "phoebe bridgers - sidelines",
    "steve lacy - bad habit",
    "sudan archives - home maker",
    "death's dynamic shroud - judgment bolt",
    "joey bada$$ - survivors guilt",
    "quadeca - born yesterday",
    "conway the machine & wallo267 - stressed (with wallo267)",
    "chat pile - why",
    "natalia lafourcade - de todas las flores",
    "domi & jd beck & anderson .paak - take a chance (feat. anderson .paak)",
    "kendrick lamar - the heart part 5",
    "viagra boys - troglodyte",
}

top_tracks_2010s = {
    "a$ap ferg & a$ap rocky - shabba (feat. a$ap rocky)",
    "lil nas x - old town road",
    "open mike eagle & has-lo - 95 radios",
    "queens of the stone age - my god is the sun",
    "car seat headrest - drunk drivers/killer whales",
    "carly rae jepsen - e·mo·tion",
    "big k.r.i.t. - country sh*t",
    "sia - chandelier",
    "drake - hotline bling",
    "rina sawayama - cyber stockholm syndrome",
    "jeff rosenstock - nausea",
    "george clanton - make it forever",
    "chance the rapper & lil wayne & 2 chainz - no problem (feat. lil wayne & 2 chainz)",
    "lana del rey - fuck it i love you",
    "jamie xx & young thug & popcaan - i know there's gonna be (good times)",
    "fka twigs - two weeks",
    "the weeknd & daft punk - starboy",
    "liturgy - returner",
    "missy elliott & pharrell williams - wtf (where they from) [feat. pharrell williams]",
    "tame impala - elephant",
    "u.s. girls - pearly gates",
    "flying lotus - do the astral plane",
    "injury reserve - oh shit!!!",
    "billie eilish - bad guy",
    "iceage - the lord's favorite",
    "rico nasty - rage",
    "anamanaguchi - my skateboard will go on",
    "arcade fire - reflektor",
    "tkay maidza & jpegmafia - awake",
    "st. vincent - digital witness",
    "lil yachty & quavo & skippa da flippa & young thug - minnesota",
    "lykke li - love me like i'm not made of stone",
    "mgmt - little dark age",
    "travis scott - sicko mode",
    "vampire weekend - cousins",
    "weyes blood - everyday",
    "zack fox & kenny beats - jesus is the one (i got depression)",
    "radiohead - burn the witch",
    "lizzo - boys",
    "denzel curry - clout cobain | clout co13a1n",
    "freddie gibbs & madlib & bj the chicago kid - shame (feat. bj the chicago kid)",
    "lorde - liability",
    "killer mike & bun b & t.i. & trouble - big beast (feat. bun b, t.i., and trouble)",
    "lady gaga - million reasons",
    "jay-z - the story of o.j.",
    "juice wrld - lucid dreams",
    "timber timbre - hot dreams",
    "james blake - the wilhelm scream",
    "dram - best hugs",
    "angel olsen - shut up kiss me",
    "king gizzard & the lizard wizard - planet b",
    "janelle monáe & big boi - tightrope (feat. big boi) - big boi vocal edit",
    "idles - danny nedelko",
    "ghost - cirice",
    "natalia lafourcade & los macorinos - danza de gardenias (feat. los macorinos)",
    "perfume genius - hood",
    "beach house - take care",
    "jpegmafia - 1539 n. calvert",
    "sufjan stevens - should have known better",
    "la dispute - king park",
    "100 gecs & laura les & dylan brady - money machine",
    "frank ocean - pyramids",
    "savages - shut up",
    "beyoncé - formation",
    "battles & matias aguayo - ice cream",
    "hannah diamond - hi",
    "clipping. - knees on the ground",
    "tnght - higher ground",
    "brockhampton - gold",
    "kirin j callinan - bravado",
    "parquet courts - wide awake",
    "ondatrópica - punkero sonidero",
    "danny brown - ain't it funny",
    "kanye west - power",
    "four tet - love cry",
    "yg & nipsey hussle - fdt",
    "lingua ignota - do you doubt me traitor",
    "daughters - satan in the wait",
    "pusha t - numbers on the boards",
    "algiers - the underside of power",
    "pj harvey - the words that maketh murder",
    "charli xcx & christine and the queens - gone",
    "tyler, the creator - earfquake",
    "sophie - ponyboy",
    "liars - mess on a mission",
    "dorian electra - career boy",
    "ariel pink - round and round",
    "joanna newsom - good intentions paving co.",
    "lcd soundsystem - i can change",
    "alex cameron - far from born again",
    "david bowie - blackstar",
    "gorillaz & lou reed - some kind of nature (feat. lou reed)",
    "mount eerie - real death",
    "the knife - a tooth for an eye",
    "swans - oxygen",
    "childish gambino - this is america",
    "father john misty - pure comedy",
    "kendrick lamar - the blacker the berry",
    "fleet foxes - helplessness blues",
    "death grips - hacker",
}
